const GlobalSearch = (() => {
    const CHAVE = "primedocs_buscas_recentes";
    const normalizar = valor => String(valor ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/\s+/g, " ").trim();
    const numeros = valor => String(valor ?? "").replace(/\D/g, "");
    const escapar = valor => String(valor ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
    function recentes(){try{return JSON.parse(localStorage.getItem(CHAVE))||[];}catch{return [];}}
    function salvarRecente(item){const lista=[item,...recentes().filter(r=>!(r.tipo===item.tipo&&String(r.id)===String(item.id)))].slice(0,8);localStorage.setItem(CHAVE,JSON.stringify(lista));}
    function limparRecentes(){localStorage.removeItem(CHAVE);renderResultados("");}
    function coincide(termo,...campos){const base=normalizar(campos.filter(Boolean).join(" ")),digitos=numeros(termo);return base.includes(normalizar(termo))||(digitos.length>=3&&numeros(campos.join(" ")).includes(digitos));}
    function buscar(termo){if(!normalizar(termo))return [];const resultados=[],add=(grupo,tipo,icone,id,titulo,subtitulo,status,pagina,acao,section="")=>resultados.push({grupo,tipo,icone,id,titulo,subtitulo,status,pagina,acao,section});
        Storage.listarClientes().filter(i=>i.ativo!==false&&coincide(termo,i.nome,i.whatsapp,i.telefone,i.email,i.cidade,i.cpfCnpj,(i.tags||[]).join(" "))).slice(0,6).forEach(c=>{const pedidos=Storage.listarPedidos().filter(p=>String(p.clienteId)===String(c.id)),pendente=pedidos.reduce((t,p)=>t+Number(p.valorPendente||0),0);add("Clientes","cliente","user",c.id,c.nome,`${pedidos.length} pedido(s) · ${Utils.moeda(pendente)} pendente`,c.statusRelacionamento||"ativo","clientes","abrirDetalhesCliente");});
        Storage.listarPedidos().filter(p=>p.ativo!==false&&coincide(termo,p.id,p.clienteNome,p.statusPedido,...(p.itens||[]).map(i=>i.nome))).slice(0,6).forEach(p=>add("Pedidos","pedido","package",p.id,`Pedido #${String(p.id).slice(-5)}`,`${p.clienteNome} · ${Utils.moeda(p.valorTotal)}`,window.rotuloStatusPedido?.(p.statusPedido)||STATUS_PEDIDOS[p.statusPedido]||p.statusPedido,"pedidos","abrirDetalhePedido"));
        Storage.listarProdutos().filter(p=>p.ativo!==false&&coincide(termo,p.nome,p.codigo,p.categoria,p.cor)).slice(0,6).forEach(p=>add("Produtos","produto","boxes",p.id,p.nome,`${p.codigo||"Sem código"} · Estoque ${Number(p.estoque||0)}`,p.categoria||"Produto","estoque","abrirDetalhesProduto","produtos"));
        Storage.listarOrdensProducao().filter(o=>o.ativo!==false&&coincide(termo,o.id,o.pedidoId,o.produtoNome,o.clienteNome,o.status,o.origem)).slice(0,6).forEach(o=>add("Produção","producao","factory",o.id,o.produtoNome,o.origem==="estoque"?`Produção para estoque · ${o.quantidade} un.`:`Pedido #${String(o.pedidoId).slice(-5)} · ${o.clienteNome}`,Producao.STATUS_ORDEM[o.status]||o.status,"producao","abrirDetalhesOrdemProducao"));
        Storage.listarImpressoras().filter(i=>i.ativa!==false&&coincide(termo,i.nome,i.modelo,i.fabricante,i.status)).slice(0,6).forEach(i=>add("Impressoras","impressora","printer",i.id,i.nome,`${i.fabricante||""} ${i.modelo||""}`.trim(),window.STATUS_IMPRESSORAS?.[i.status]||i.status,"impressoras","abrirPainelImpressora"));
        Storage.listarFilamentos().filter(f=>f.ativo!==false&&coincide(termo,f.codigo,f.material,f.cor,f.marca,f.status)).slice(0,6).forEach(f=>add("Filamentos","filamento","spool",f.id,`${f.material} ${f.cor}`,`${f.marca||f.codigo||"Rolo"} · ${(Number(f.pesoAtualGramas)||Number(f.pesoAtualKg||0)*1000).toFixed(0)} g`,f.status||"disponível","estoque","","filamentos"));
        (Storage.listarLancamentosFinanceiros?.()||[]).filter(f=>coincide(termo,f.id,f.clienteNome,f.descricao,f.status)).slice(0,6).forEach(f=>add("Financeiro","financeiro","wallet-cards",f.id,f.clienteNome||f.descricao,Utils.moeda(f.valorRestante||f.valor),f.status,"financeiro",""));
        Storage.listarLojas().filter(l=>l.ativo!==false&&coincide(termo,l.nome,l.responsavel,l.whatsapp,l.endereco)).slice(0,4).forEach(l=>add("Consignado","loja","store",l.id,l.nome,l.responsavel||"Loja parceira","Loja parceira","consignado",""));
        Storage.listarConsignados().filter(c=>coincide(termo,c.id,c.lojaNome,c.loja,c.responsavel,...(c.itens||[]).map(i=>i.nome))).slice(0,4).forEach(c=>add("Consignado","consignado","package-open",c.id,c.lojaNome||c.loja||"Consignado",`${(c.itens||[]).length} produto(s) · ${c.data||""}`,"Consignado","consignado",""));
        Storage.listarOrcamentos().filter(o=>o.ativo!==false&&coincide(termo,o.id,o.clienteNome,o.cliente,o.status,...(o.itens||[]).map(i=>i.nome))).slice(0,4).forEach(o=>add("Orçamentos","orcamento","file-text",o.id,o.clienteNome||o.cliente||`Orçamento #${String(o.id).slice(-5)}`,Utils.moeda(o.valorFinal),o.status||"enviado","orcamento",""));
        return resultados;
    }
    function abrir(){Modal.abrir("Pesquisa global",`<div class="globalSearch"><label><i data-lucide="search"></i><input id="globalSearchInput" autocomplete="off" enterkeyhint="search" placeholder="Pesquise em todo o PrimeDocs..." oninput="GlobalSearch.renderResultados(this.value)"><kbd>Esc</kbd></label><div id="globalSearchResults"></div><footer><span>Resultados separados por categoria</span><button onclick="GlobalSearch.limparRecentes()">Limpar recentes</button></footer></div>`);document.querySelector("#modalRoot .modalContainer")?.classList.add("globalSearchModal");renderResultados("");setTimeout(()=>document.getElementById("globalSearchInput")?.focus(),50);lucide.createIcons();}
    function renderResultados(termo){const el=document.getElementById("globalSearchResults");if(!el)return;const itens=buscar(termo);if(!normalizar(termo)){const rec=recentes();el.innerHTML=rec.length?`<section class="searchResultGroup"><h4>Recentes</h4>${rec.map(SearchResultItem.render).join("")}</section>`:`<div class="globalSearchEmpty"><i data-lucide="command"></i><strong>Encontre qualquer informação</strong><p>Pesquise por nome, telefone, pedido, código, cor ou status.</p></div>`;lucide.createIcons();return;}const grupos=[...new Set(itens.map(i=>i.grupo))];el.innerHTML=grupos.length?grupos.map(g=>`<section class="searchResultGroup"><h4>${g}</h4>${itens.filter(i=>i.grupo===g).map(SearchResultItem.render).join("")}</section>`).join(""):`<div class="globalSearchEmpty"><i data-lucide="search-x"></i><strong>Nenhum resultado</strong><p>Tente outro nome, código ou número.</p></div>`;lucide.createIcons();}
    function selecionarCodificado(valor){const item=JSON.parse(decodeURIComponent(valor));salvarRecente(item);Modal.fechar();navegar(item.pagina,item.section?{section:item.section}:{});if(item.acao&&typeof window[item.acao]==="function")setTimeout(()=>window[item.acao](item.id),0);}
    function init(){document.addEventListener("keydown",evento=>{if((evento.ctrlKey||evento.metaKey)&&evento.key.toLowerCase()==="k"){evento.preventDefault();abrir();}if(evento.key==="Escape"&&document.getElementById("globalSearchInput"))Modal.fechar();});}
    return {abrir,buscar,renderResultados,selecionarCodificado,limparRecentes,normalizar,init,escapar};
})();
const SearchResultItem={render(item){const valor=encodeURIComponent(JSON.stringify(item)).replaceAll("'","%27");return `<button class="searchResultItem" onclick="GlobalSearch.selecionarCodificado('${valor}')"><span><i data-lucide="${item.icone}"></i></span><div><strong>${GlobalSearch.escapar(item.titulo)}</strong><small>${GlobalSearch.escapar(item.subtitulo)}</small></div><b>${GlobalSearch.escapar(item.status||"")}</b><i data-lucide="arrow-up-right"></i></button>`;}};
const QuickLink={render({icone="arrow-up-right",rotulo,pagina,onclick=""}){const acao=onclick||`navegar('${pagina}')`;return `<button class="quickLink" onclick="${acao}"><i data-lucide="${icone}"></i><span>${GlobalSearch.escapar(rotulo)}</span></button>`;}};
const ContextActionMenu={abrir(titulo,itens=[]){Modal.abrir(titulo,`<div class="compactActionMenu">${itens.map(item=>`<button class="${item.perigo?'danger':''}" onclick="Modal.fechar();${item.acao}"><i data-lucide="${item.icone||'arrow-up-right'}"></i><span><strong>${GlobalSearch.escapar(item.titulo)}</strong>${item.descricao?`<small>${GlobalSearch.escapar(item.descricao)}</small>`:''}</span></button>`).join('')}</div>`);lucide.createIcons();}};
window.GlobalSearch=GlobalSearch;window.SearchResultItem=SearchResultItem;window.QuickLink=QuickLink;window.ContextActionMenu=ContextActionMenu;GlobalSearch.init();
