let filtrosFilamentos = { material: "", cor: "", marca: "", localizacao: "", status: "" };
let ordenacaoFilamentos = "nome";
let pesquisaFilamentos = "";
let grupoFilamentoAberto = "";

function renderFilamentos() {
    FilamentIntegration.migrarDados();
    const rolos = Storage.listarFilamentos().map(FilamentIntegration.normalizarRolo);
    const ativos = rolos.filter(rolo => rolo.ativo !== false);
    const pendentes = rolos.filter(rolo => rolo.ativo !== false && rolo.migracaoPendente);
    const resumo = calcularResumoGeralFilamentos(ativos);
    app.innerHTML = `<div class="filamentsPage"><button class="back" onclick="navegar('home')"><i data-lucide="arrow-left"></i> Voltar</button>
        <div class="filamentPageHeading"><div>${Page.titulo("🧵 Filamentos", "Rolos físicos organizados por material, cor e marca.")}</div><button class="btn" onclick="AddMultipleRollsModal.abrir()"><i data-lucide="plus"></i> Adicionar rolos</button></div>
        ${pendentes.length ? `<section class="filamentMigrationBanner"><i data-lucide="split"></i><div><strong>${pendentes.length} cadastro(s) antigo(s) aguardam divisão</strong><p>Confirme quantos rolos físicos existem antes de usar esses saldos na produção.</p></div><button onclick="abrirAssistenteMigracaoFilamento('${pendentes[0].id}')">Revisar agora</button></section>` : ""}
        <section class="erpSummaryGrid filamentSummaryGrid">${cardResumoERP("weight",formatarPesoFilamento(resumo.pesoFisico),"Peso físico")}${cardResumoERP("package-check",formatarPesoFilamento(resumo.pesoDisponivel),"Disponível")}${cardResumoERP("bookmark",formatarPesoFilamento(resumo.pesoReservado),"Reservado")}${cardResumoERP("printer",resumo.emUso,"Rolos em uso")}${cardResumoERP("triangle-alert",resumo.baixos,"Baixo estoque")}${cardResumoERP("circle-off",resumo.esgotados,"Esgotados")}</section>
        <section class="erpToolbar filamentToolbar"><label class="erpSearch"><i data-lucide="search"></i><input id="pesquisaFilamento" placeholder="Material, cor, marca, código, impressora ou slot" value="${escaparFilamento(pesquisaFilamentos)}" oninput="atualizarListaFilamentos()"></label><button class="btnSecondary filamentFilterButton" onclick="FilamentFilters.abrir()"><i data-lucide="sliders-horizontal"></i> Filtros ${quantidadeFiltrosFilamentos() ? `<b>${quantidadeFiltrosFilamentos()}</b>` : ""}</button><select id="ordemFilamentos" onchange="ordenacaoFilamentos=this.value;atualizarListaFilamentos()" aria-label="Ordenar grupos"><option value="nome" ${ordenacaoFilamentos==="nome"?"selected":""}>Nome</option><option value="menor" ${ordenacaoFilamentos==="menor"?"selected":""}>Menor estoque</option><option value="maior" ${ordenacaoFilamentos==="maior"?"selected":""}>Maior estoque</option><option value="uso" ${ordenacaoFilamentos==="uso"?"selected":""}>Mais usados</option><option value="recentes" ${ordenacaoFilamentos==="recentes"?"selected":""}>Atualizados recentemente</option><option value="baixo" ${ordenacaoFilamentos==="baixo"?"selected":""}>Baixo estoque</option><option value="rolos" ${ordenacaoFilamentos==="rolos"?"selected":""}>Quantidade de rolos</option></select></section>
        <div id="listaFilamentos" class="filamentGroupsGrid"></div></div>`;
    atualizarListaFilamentos();
    lucide.createIcons();
}

function calcularResumoGeralFilamentos(rolos) {
    return rolos.reduce((resumo, rolo) => {
        const reservado = FilamentIntegration.pesoReservado(rolo.id);
        const disponivel = FilamentIntegration.pesoDisponivel(rolo.id);
        resumo.pesoFisico += FilamentIntegration.pesoAtual(rolo);
        resumo.pesoReservado += reservado;
        resumo.pesoDisponivel += disponivel;
        resumo.emUso += FilamentIntegration.localDoRolo(rolo.id) ? 1 : 0;
        resumo.baixos += rolo.pesoAtualGramas > 0 && rolo.alertaMinimoGramas > 0 && disponivel <= rolo.alertaMinimoGramas ? 1 : 0;
        resumo.esgotados += rolo.esgotado || rolo.pesoAtualGramas <= 0 ? 1 : 0;
        return resumo;
    }, { pesoFisico: 0, pesoReservado: 0, pesoDisponivel: 0, emUso: 0, baixos: 0, esgotados: 0 });
}

function atualizarListaFilamentos() {
    const lista = document.getElementById("listaFilamentos"); if (!lista) return;
    pesquisaFilamentos = document.getElementById("pesquisaFilamento")?.value || pesquisaFilamentos;
    const todos = Storage.listarFilamentos().map(FilamentIntegration.normalizarRolo);
    const termo = normalizarBuscaFilamento(pesquisaFilamentos);
    const exato = todos.find(rolo => normalizarBuscaFilamento(rolo.codigo) === termo && termo);
    let grupos = FilamentIntegration.agruparRolos(todos.filter(rolo => filtrarRoloFilamento(rolo, termo)));
    grupos = ordenarGruposFilamentos(grupos);
    if (!grupos.length) {
        lista.innerHTML = `<div class="erpEmpty filamentEmpty"><i data-lucide="spool"></i><strong>Nenhum grupo encontrado</strong><p>Ajuste a pesquisa ou cadastre novos rolos físicos.</p><button class="btn" onclick="AddMultipleRollsModal.abrir()">Adicionar rolos</button></div>`;
    } else {
        lista.innerHTML = `${exato ? `<button class="filamentExactResult" onclick="FilamentRollDetail.abrir('${exato.id}')"><i data-lucide="scan-search"></i><span><small>CÓDIGO EXATO</small><strong>${escaparFilamento(exato.codigo)}</strong><b>${escaparFilamento(exato.material)} ${escaparFilamento(exato.cor)} · abrir rolo</b></span><i data-lucide="arrow-right"></i></button>` : ""}${grupos.map(FilamentGroupCard.render).join("")}`;
    }
    lucide.createIcons();
}

function filtrarRoloFilamento(rolo, termo) {
    const local = FilamentIntegration.localizacaoDoRolo(rolo.id);
    const texto = normalizarBuscaFilamento([rolo.material,rolo.cor,rolo.marca,rolo.codigo,rolo.acabamento,local.tipo,local.impressoraNome,local.slotAms ? `slot ${local.slotAms}` : ""].join(" "));
    if (termo && !texto.includes(termo)) return false;
    if (filtrosFilamentos.material && rolo.material !== filtrosFilamentos.material) return false;
    if (filtrosFilamentos.cor && rolo.cor !== filtrosFilamentos.cor) return false;
    if (filtrosFilamentos.marca && rolo.marca !== filtrosFilamentos.marca) return false;
    if (filtrosFilamentos.localizacao && local.tipo !== filtrosFilamentos.localizacao) return false;
    if (filtrosFilamentos.status === "em_uso" && !FilamentIntegration.localDoRolo(rolo.id)) return false;
    if (filtrosFilamentos.status === "estoque" && (FilamentIntegration.localDoRolo(rolo.id) || rolo.esgotado || rolo.ativo === false)) return false;
    if (filtrosFilamentos.status === "baixo" && !(rolo.alertaMinimoGramas > 0 && FilamentIntegration.pesoDisponivel(rolo.id) <= rolo.alertaMinimoGramas)) return false;
    if (filtrosFilamentos.status === "esgotado" && !rolo.esgotado) return false;
    if (filtrosFilamentos.status === "inativo" && rolo.ativo !== false) return false;
    if (!filtrosFilamentos.status && rolo.ativo === false) return false;
    return true;
}

function ordenarGruposFilamentos(grupos) {
    return grupos.sort((a,b) => {
        if (ordenacaoFilamentos === "menor") return a.pesoDisponivelTotal - b.pesoDisponivelTotal;
        if (ordenacaoFilamentos === "maior") return b.pesoDisponivelTotal - a.pesoDisponivelTotal;
        if (ordenacaoFilamentos === "uso") return b.emUso - a.emUso;
        if (ordenacaoFilamentos === "recentes") return new Date(b.atualizadoEm || 0) - new Date(a.atualizadoEm || 0);
        if (ordenacaoFilamentos === "baixo") return Number(b.baixoEstoque) - Number(a.baixoEstoque) || a.pesoDisponivelTotal - b.pesoDisponivelTotal;
        if (ordenacaoFilamentos === "rolos") return b.quantidadeRolos - a.quantidadeRolos;
        return `${a.material} ${a.cor} ${a.marca}`.localeCompare(`${b.material} ${b.cor} ${b.marca}`,"pt-BR");
    });
}

const FilamentGroupSummary = { render(grupo) { return `<div class="filamentGroupWeights"><div><span>Físico</span><strong>${formatarPesoFilamento(grupo.pesoFisicoTotal)}</strong></div><div><span>Reservado</span><strong>${formatarPesoFilamento(grupo.pesoReservadoTotal)}</strong></div><div><span>Disponível</span><strong>${formatarPesoFilamento(grupo.pesoDisponivelTotal)}</strong></div></div><div class="filamentGroupCounts"><span><b>${grupo.quantidadeRolos}</b> rolo(s)</span><span><b>${grupo.emUso}</b> em uso</span><span><b>${grupo.noEstoque}</b> no estoque</span>${grupo.esgotados ? `<span><b>${grupo.esgotados}</b> esgotado(s)</span>` : ""}</div>`; } };

const FilamentGroupCard = { render(grupo) {
    const chave = encodeURIComponent(grupo.chave);
    const locais = grupo.rolos.slice(0,3).map(rolo => textoLocalizacaoRolo(rolo));
    return `<article class="filamentGroupCard ${grupo.baixoEstoque?"isLow":""}" role="button" tabindex="0" onclick="abrirGrupoFilamento('${chave}')" onkeydown="if(event.key==='Enter')abrirGrupoFilamento('${chave}')"><header><span class="filamentGroupIcon"><i data-lucide="spool"></i></span><div><span>${escaparFilamento(grupo.material)}</span><h3>${escaparFilamento(grupo.cor)}${grupo.acabamento?` · ${escaparFilamento(grupo.acabamento)}`:""}</h3><p>${escaparFilamento(grupo.marca||"Marca não informada")}${grupo.diametro?` · ${escaparFilamento(grupo.diametro)} mm`:""}</p></div>${grupo.baixoEstoque?`<b class="erpBadge danger">Baixo estoque</b>`:""}</header>${FilamentGroupSummary.render(grupo)}<section class="filamentLocations"><span>LOCALIZAÇÕES</span>${locais.map(local=>`<small><i data-lucide="map-pin"></i>${escaparFilamento(local)}</small>`).join("")}${grupo.rolos.length>3?`<small>+ ${grupo.rolos.length-3} rolo(s)</small>`:""}</section><footer><span>Estoque estimado <strong>${Utils.moeda(grupo.valorEstoque)}</strong></span><button type="button" onclick="event.stopPropagation();abrirGrupoFilamento('${chave}')">Abrir <i data-lucide="arrow-right"></i></button></footer></article>`;
} };

function abrirGrupoFilamento(chaveCodificada) {
    grupoFilamentoAberto = decodeURIComponent(chaveCodificada);
    const grupo = FilamentIntegration.agruparRolos(Storage.listarFilamentos()).find(item => item.chave === grupoFilamentoAberto);
    if (!grupo) return Toast.show("Grupo de filamentos não encontrado.","error");
    Modal.abrir(`${grupo.material} ${grupo.cor} — ${grupo.marca||"Sem marca"}`,`<div class="filamentGroupDetail">${FilamentGroupSummary.render(grupo)}<div class="filamentGroupDetailHeader"><div><span>ROLOS FÍSICOS</span><strong>${grupo.quantidadeRolos} cadastro(s) individual(is)</strong></div><button class="btnSecondary" onclick="adicionarRolosAoGrupo('${encodeURIComponent(grupo.chave)}')"><i data-lucide="plus"></i> Adicionar iguais</button></div><div class="filamentRollList">${grupo.rolos.sort((a,b)=>String(a.codigo).localeCompare(String(b.codigo))).map(FilamentRollCard.render).join("")}</div></div>`);
    document.querySelector("#modalRoot .modalContainer")?.classList.add("filamentGroupModal"); lucide.createIcons();
}

function adicionarRolosAoGrupo(chaveCodificada) {
    const chave = decodeURIComponent(chaveCodificada || "");
    const grupo = FilamentIntegration.agruparRolos(Storage.listarFilamentos()).find(item => item.chave === chave);
    if (!grupo) return Toast.show("Grupo de filamento não encontrado.");
    AddMultipleRollsModal.abrir({
        material: grupo.material,
        cor: grupo.cor,
        marca: grupo.marca,
        acabamento: grupo.acabamento,
        diametro: grupo.diametro
    });
}

const FilamentLocationBadge = { render(rolo) { const local=FilamentIntegration.localizacaoDoRolo(rolo.id);const rotulo=local.tipo==="ams"?`${local.impressoraNome||"Impressora"} · AMS Slot ${local.slotAms}`:local.tipo==="externo"?`${local.impressoraNome||"Impressora"} · Rolo externo`:local.tipo==="inativo"?"Inativo":local.tipo==="esgotado"?"Esgotado":"Estoque";return `<span class="filamentLocationBadge location-${local.tipo}"><i data-lucide="${local.tipo==="ams"?"blocks":local.tipo==="externo"?"printer":"warehouse"}"></i>${escaparFilamento(rotulo)}</span>`; } };

const FilamentRollCard = { render(rolo) { const reservado=FilamentIntegration.pesoReservado(rolo.id),disponivel=FilamentIntegration.pesoDisponivel(rolo.id);return `<article class="filamentRollCard ${rolo.esgotado?"isEmpty":""}"><header><div><span>ROLO</span><strong>${escaparFilamento(rolo.codigo)}</strong></div>${FilamentLocationBadge.render(rolo)}<button class="btn-icon" onclick="abrirAcoesRoloFilamento('${rolo.id}')" aria-label="Ações do rolo"><i data-lucide="ellipsis"></i></button></header><div class="filamentRollNumbers"><div><span>Físico</span><strong>${formatarPesoFilamento(rolo.pesoAtualGramas)}</strong></div><div><span>Reservado</span><strong>${formatarPesoFilamento(reservado)}</strong></div><div><span>Disponível</span><strong>${formatarPesoFilamento(disponivel)}</strong></div></div><footer><button onclick="FilamentRollDetail.abrir('${rolo.id}')"><i data-lucide="eye"></i> Ver detalhes</button><button onclick="AdjustRollWeightModal.abrir('${rolo.id}')"><i data-lucide="scale"></i> Corrigir peso</button></footer></article>`; } };

const FilamentRollDetail = { abrir(id) { const rolo=FilamentIntegration.normalizarRolo(Storage.buscarFilamentoPorId(id));if(!rolo?.id)return Toast.show("Rolo não encontrado.","error");const reservado=FilamentIntegration.pesoReservado(id);Modal.abrir(`Rolo ${rolo.codigo}`,`<div class="filamentRollDetail"><header><div><span>${escaparFilamento(rolo.material)}</span><h3>${escaparFilamento(rolo.cor)} — ${escaparFilamento(rolo.marca||"Sem marca")}</h3><p>${escaparFilamento(rolo.acabamento||"Acabamento não informado")} · ${escaparFilamento(rolo.diametro)} mm</p></div>${FilamentLocationBadge.render(rolo)}</header><div class="filamentRollNumbers"><div><span>Peso inicial</span><strong>${formatarPesoFilamento(rolo.pesoInicialGramas)}</strong></div><div><span>Peso físico</span><strong>${formatarPesoFilamento(rolo.pesoAtualGramas)}</strong></div><div><span>Reservado</span><strong>${formatarPesoFilamento(reservado)}</strong></div><div><span>Disponível</span><strong>${formatarPesoFilamento(FilamentIntegration.pesoDisponivel(id))}</strong></div><div><span>Preço/kg</span><strong>${Utils.moeda(rolo.precoKg)}</strong></div><div><span>Status</span><strong>${rotuloStatusRolo(rolo.status)}</strong></div></div>${rolo.observacoes?`<p class="filamentRollNotes">${escaparFilamento(rolo.observacoes)}</p>`:""}<div class="modalActions"><button class="btnSecondary" onclick="abrirHistoricoRolo('${id}')"><i data-lucide="history"></i> Histórico</button><button class="btnSecondary" onclick="abrirAcoesRoloFilamento('${id}')"><i data-lucide="ellipsis"></i> Ações</button></div></div>`);lucide.createIcons(); } };

function abrirAcoesRoloFilamento(id) { const rolo=FilamentIntegration.normalizarRolo(Storage.buscarFilamentoPorId(id));if(!rolo?.id)return;const local=FilamentIntegration.localDoRolo(id);Modal.abrir(`Ações — ${rolo.codigo}`,`<div class="compactActionMenu"><button onclick="FilamentRollDetail.abrir('${id}')"><i data-lucide="eye"></i><span><strong>Ver detalhes</strong><small>Saldo, localização e informações do rolo</small></span></button><button onclick="abrirEditarRoloFilamento('${id}')"><i data-lucide="pencil"></i><span><strong>Editar cadastro</strong><small>Código, material, preço e alertas</small></span></button><button onclick="AdjustRollWeightModal.abrir('${id}')"><i data-lucide="scale"></i><span><strong>Corrigir peso</strong><small>Registrar pesagem ou correção manual</small></span></button>${local?`<button onclick="removerRoloDoLocal('${id}')"><i data-lucide="package-minus"></i><span><strong>Remover da impressora</strong><small>Voltar o rolo para o estoque</small></span></button>`:`<button onclick="abrirCarregarRoloFilamento('${id}')"><i data-lucide="printer-check"></i><span><strong>Carregar em impressora</strong><small>Escolher AMS, slot ou rolo externo</small></span></button>`}<button class="danger" onclick="MarkRollEmptyModal.abrir('${id}')"><i data-lucide="circle-off"></i><span><strong>Rolo esgotado</strong><small>Zerar saldo, remover e revisar reservas</small></span></button><button onclick="abrirHistoricoRolo('${id}')"><i data-lucide="history"></i><span><strong>Ver histórico</strong><small>Movimentações e correções</small></span></button>${rolo.ativo!==false?`<button class="danger" onclick="inativarRoloFilamento('${id}')"><i data-lucide="archive"></i><span><strong>Inativar</strong></span></button>`:`<button onclick="reativarRoloFilamento('${id}')"><i data-lucide="rotate-ccw"></i><span><strong>Reativar no estoque</strong></span></button>`}</div>`);lucide.createIcons(); }

const AddMultipleRollsModal = { abrir(preenchido={}) { Modal.abrir("Adicionar rolos",`<div class="addRollsIntro"><i data-lucide="copy-plus"></i><div><strong>Cadastre vários rolos iguais de uma vez</strong><p>Cada rolo receberá ID, código, saldo e histórico próprios.</p></div></div><div class="erpFormGrid"><label class="inputGroup"><span>Material *</span><input id="loteMaterial" value="${escaparFilamento(preenchido.material||"")}" placeholder="PETG"></label><label class="inputGroup"><span>Cor *</span><input id="loteCor" value="${escaparFilamento(preenchido.cor||"")}" placeholder="Branco"></label><label class="inputGroup"><span>Marca</span><input id="loteMarca" value="${escaparFilamento(preenchido.marca||"")}" placeholder="Masterprint"></label><label class="inputGroup"><span>Acabamento</span><input id="loteAcabamento" value="${escaparFilamento(preenchido.acabamento||"")}" placeholder="Fosco"></label><label class="inputGroup"><span>Diâmetro (mm)</span><input id="loteDiametro" value="${escaparFilamento(preenchido.diametro||"1.75")}"></label><label class="inputGroup"><span>Quantidade de rolos *</span><input id="loteQuantidade" type="number" min="1" max="100" value="1"></label><label class="inputGroup"><span>Peso inicial por rolo (g) *</span><input id="lotePeso" type="number" min="1" step="1" value="1000"></label><label class="inputGroup"><span>Preço por kg</span><input id="lotePreco" type="number" min="0" step="0.01" value="85"></label><label class="inputGroup"><span>Alerta por rolo (g)</span><input id="loteAlertaRolo" type="number" min="0" value="150"></label><label class="inputGroup"><span>Alerta do grupo (g)</span><input id="loteAlertaGrupo" type="number" min="0" value="1000"></label><label class="inputGroup erpFull"><span>Código inicial opcional</span><input id="loteCodigo" placeholder="PETG-BR-MP-001"></label><label class="inputGroup erpFull"><span>Observações</span><textarea id="loteObservacoes" rows="2"></textarea></label></div><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="salvarRolosEmLote()"><i data-lucide="plus"></i> Cadastrar rolos</button></div>`);document.querySelector("#modalRoot .modalContainer")?.classList.add("addRollsModal");lucide.createIcons(); } };

function salvarRolosEmLote() { try { const valor=id=>document.getElementById(id)?.value||"";const criados=FilamentIntegration.criarRolosEmLote({material:valor("loteMaterial"),cor:valor("loteCor"),marca:valor("loteMarca"),acabamento:valor("loteAcabamento"),diametro:valor("loteDiametro"),quantidade:valor("loteQuantidade"),pesoInicialGramas:valor("lotePeso"),precoKg:valor("lotePreco"),alertaMinimoGramas:valor("loteAlertaRolo"),alertaGrupoGramas:valor("loteAlertaGrupo"),codigoInicial:valor("loteCodigo"),observacoes:valor("loteObservacoes")});Modal.fechar();renderFilamentos();Toast.show(`${criados.length} rolo(s) cadastrado(s) com sucesso!`,"success"); } catch(erro) { Toast.show(erro.message||"Não foi possível cadastrar os rolos.","error"); } }

const AdjustRollWeightModal = { abrir(id) { const rolo=FilamentIntegration.normalizarRolo(Storage.buscarFilamentoPorId(id));if(!rolo?.id)return;Modal.abrir("Corrigir peso do rolo",`<div class="weightCorrectionBefore"><span>Peso atual registrado</span><strong>${formatarPesoFilamento(rolo.pesoAtualGramas)}</strong></div><label class="inputGroup"><span>Novo peso estimado (g)</span><input id="pesoCorrigidoRolo" type="number" min="0" step="1" value="${rolo.pesoAtualGramas}"></label><label class="inputGroup"><span>Motivo</span><select id="motivoPesoRolo"><option value="pesagem_manual">Pesagem manual</option><option value="rolo_acabou">Rolo acabou antes do previsto</option><option value="falha_impressao">Falha de impressão</option><option value="perda_material">Perda de material</option><option value="correcao_cadastro">Correção de cadastro</option><option value="outro">Outro</option></select></label><label class="inputGroup"><span>Observação</span><textarea id="observacaoPesoRolo" rows="3"></textarea></label><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarCorrecaoPesoRolo('${id}')">Salvar correção</button></div>`); } };
function confirmarCorrecaoPesoRolo(id) { try { FilamentIntegration.corrigirPeso(id,document.getElementById("pesoCorrigidoRolo").value,document.getElementById("motivoPesoRolo").value,document.getElementById("observacaoPesoRolo").value);Modal.fechar();renderFilamentos();Toast.show("Peso corrigido e histórico atualizado!","success"); } catch(erro){Toast.show(erro.message,"error");} }

const MarkRollEmptyModal = { abrir(id) { const rolo=FilamentIntegration.normalizarRolo(Storage.buscarFilamentoPorId(id));const reservas=FilamentIntegration.reservasAtivas(id);Modal.abrir("Rolo esgotado",`<div class="emptyRollWarning"><i data-lucide="triangle-alert"></i><div><strong>${escaparFilamento(rolo.codigo)} será marcado como esgotado</strong><p>O peso ficará em 0 g e o rolo será removido da impressora.</p></div></div>${reservas.length?`<div class="materialWarning"><i data-lucide="bookmark"></i><span>Este rolo possui ${reservas.length} reserva(s) em produções futuras.</span></div><div class="compactActionMenu"><button onclick="abrirSubstituirReservasRolo('${id}')"><i data-lucide="replace"></i><span><strong>Substituir por outro rolo</strong><small>Mover reservas para um rolo compatível</small></span></button><button class="danger" onclick="confirmarRoloEsgotado('${id}',true)"><i data-lucide="unlink"></i><span><strong>Liberar reservas e esgotar</strong><small>As operações precisarão ser revisadas</small></span></button><button onclick="Modal.fechar();navegar('producao')"><i data-lucide="factory"></i><span><strong>Revisar operações</strong></span></button></div>`:`<p>Esta ação poderá ser corrigida posteriormente pelo histórico do rolo.</p><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn dangerButton" onclick="confirmarRoloEsgotado('${id}',false)">Marcar como esgotado</button></div>`}`);lucide.createIcons(); } };
async function confirmarRoloEsgotado(id,liberar) { try { await FilamentIntegration.marcarRoloEsgotado(id,{liberar});Modal.fechar();renderFilamentos();Toast.show("Rolo marcado como esgotado.","success"); } catch(erro){if(erro.codigo==="RESERVAS_ATIVAS")return MarkRollEmptyModal.abrir(id);Toast.show(erro.message,"error");} }
function abrirSubstituirReservasRolo(id) { const origem=Storage.buscarFilamentoPorId(id),alternativas=FilamentIntegration.rolosCompativeis(origem).filter(rolo=>String(rolo.id)!==String(id)&&String(rolo.cor).toLowerCase()===String(origem.cor).toLowerCase());Modal.abrir("Substituir rolo reservado",`<label class="inputGroup"><span>Novo rolo compatível</span><select id="roloSubstituto"><option value="">Selecione</option>${alternativas.map(rolo=>`<option value="${rolo.id}">${escaparFilamento(rolo.codigo)} · ${formatarPesoFilamento(FilamentIntegration.pesoDisponivel(rolo.id))} disponível</option>`).join("")}</select></label><div class="modalActions"><button class="btnSecondary" onclick="MarkRollEmptyModal.abrir('${id}')">Voltar</button><button class="btn" onclick="confirmarSubstituicaoReservasRolo('${id}')">Transferir e esgotar</button></div>`); }
async function confirmarSubstituicaoReservasRolo(id) { try { const destino=document.getElementById("roloSubstituto")?.value;if(!destino)throw new Error("Selecione o rolo substituto.");FilamentIntegration.moverReservas(id,destino);await FilamentIntegration.marcarRoloEsgotado(id);Modal.fechar();renderFilamentos();Toast.show("Reservas transferidas e rolo esgotado.","success"); } catch(erro){Toast.show(erro.message,"error");} }

function abrirEditarRoloFilamento(id) { const rolo=FilamentIntegration.normalizarRolo(Storage.buscarFilamentoPorId(id));Modal.abrir(`Editar ${rolo.codigo}`,`<div class="erpFormGrid"><label class="inputGroup"><span>Código *</span><input id="editarRoloCodigo" value="${escaparFilamento(rolo.codigo)}"></label><label class="inputGroup"><span>Material *</span><input id="editarRoloMaterial" value="${escaparFilamento(rolo.material)}"></label><label class="inputGroup"><span>Cor *</span><input id="editarRoloCor" value="${escaparFilamento(rolo.cor)}"></label><label class="inputGroup"><span>Marca</span><input id="editarRoloMarca" value="${escaparFilamento(rolo.marca)}"></label><label class="inputGroup"><span>Acabamento</span><input id="editarRoloAcabamento" value="${escaparFilamento(rolo.acabamento)}"></label><label class="inputGroup"><span>Diâmetro</span><input id="editarRoloDiametro" value="${escaparFilamento(rolo.diametro)}"></label><label class="inputGroup"><span>Preço/kg</span><input id="editarRoloPreco" type="number" min="0" step="0.01" value="${rolo.precoKg}"></label><label class="inputGroup"><span>Alerta do rolo (g)</span><input id="editarRoloAlerta" type="number" min="0" value="${rolo.alertaMinimoGramas}"></label><label class="inputGroup"><span>Alerta do grupo (g)</span><input id="editarGrupoAlerta" type="number" min="0" value="${rolo.alertaGrupoGramas||0}"></label><label class="inputGroup erpFull"><span>Observações</span><textarea id="editarRoloObs" rows="3">${escaparFilamento(rolo.observacoes)}</textarea></label></div><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="salvarEdicaoRoloFilamento('${id}')">Salvar</button></div>`); }
function salvarEdicaoRoloFilamento(id) { try { const anterior=FilamentIntegration.normalizarRolo(Storage.buscarFilamentoPorId(id)),codigo=document.getElementById("editarRoloCodigo").value.trim();if(!codigo)throw new Error("Informe o código do rolo.");if(Storage.listarFilamentos().some(item=>String(item.id)!==String(id)&&String(item.codigo).toLowerCase()===codigo.toLowerCase()))throw new Error("Este código já está em uso.");const atualizado=FilamentIntegration.normalizarRolo({...anterior,codigo,material:document.getElementById("editarRoloMaterial").value.trim(),cor:document.getElementById("editarRoloCor").value.trim(),marca:document.getElementById("editarRoloMarca").value.trim(),acabamento:document.getElementById("editarRoloAcabamento").value.trim(),diametro:document.getElementById("editarRoloDiametro").value.trim(),precoKg:Number(document.getElementById("editarRoloPreco").value)||0,alertaMinimoGramas:Number(document.getElementById("editarRoloAlerta").value)||0,alertaGrupoGramas:Number(document.getElementById("editarGrupoAlerta").value)||0,observacoes:document.getElementById("editarRoloObs").value.trim(),atualizadoEm:new Date().toISOString()});Storage.salvarFilamento(atualizado);FilamentIntegration.registrar("cadastro_atualizado",id,FilamentIntegration.localDoRolo(id)?.impressoraId,"Cadastro do rolo atualizado.");Modal.fechar();renderFilamentos();Toast.show("Rolo atualizado!","success"); } catch(erro){Toast.show(erro.message,"error");} }

function abrirCarregarRoloFilamento(id) { const rolo=Storage.buscarFilamentoPorId(id),impressoras=Storage.listarImpressoras().filter(item=>item.ativa!==false);const destinos=impressoras.flatMap(imp=>{const normal=FilamentIntegration.normalizarImpressora(imp),opcoes=[];if(normal.possuiAms)normal.slotsAms.forEach(slot=>opcoes.push({valor:`${normal.id}|ams|${slot.numero}`,rotulo:`${normal.nome} · AMS Slot ${slot.numero}${slot.filamentoId?" · ocupado":""}`}));opcoes.push({valor:`${normal.id}|externo|0`,rotulo:`${normal.nome} · Rolo externo${normal.roloExternoId?" · ocupado":""}`});return opcoes;});if(!destinos.length)return Toast.show("Cadastre uma impressora antes de carregar o rolo.","error");Modal.abrir(`Carregar ${rolo.codigo}`,`<label class="inputGroup"><span>Destino</span><select id="destinoRoloImpressora"><option value="">Selecione impressora e posição</option>${destinos.map(dest=>`<option value="${dest.valor}">${escaparFilamento(dest.rotulo)}</option>`).join("")}</select></label><p class="erpModalHint">Cada rolo só pode ocupar um local por vez.</p><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarCarregarRoloFilamento('${id}')">Carregar rolo</button></div>`); }
async function confirmarCarregarRoloFilamento(id) { try { const [impressoraId,tipo,slot]=String(document.getElementById("destinoRoloImpressora")?.value||"").split("|");if(!impressoraId)throw new Error("Selecione o destino do rolo.");await FilamentIntegration.carregarRolo(impressoraId,tipo,Number(slot),id);Modal.fechar();renderFilamentos();Toast.show("Rolo carregado na impressora!","success"); } catch(erro){Toast.show(erro.message,"error");} }
async function removerRoloDoLocal(id) { const local=FilamentIntegration.localDoRolo(id);if(!local)return;try{await FilamentIntegration.removerRolo(local.impressoraId,local.tipo,local.slotAms||0);Modal.fechar();renderFilamentos();Toast.show("Rolo devolvido ao estoque.","success");}catch(erro){if(erro.codigo==="RESERVAS_ATIVAS")return Toast.show("O rolo possui reservas futuras. Revise a produção antes de remover.","error");Toast.show(erro.message,"error");} }
function inativarRoloFilamento(id) { const local=FilamentIntegration.localDoRolo(id);if(local)return Toast.show("Remova o rolo da impressora antes de inativar.","error");if(FilamentIntegration.reservasAtivas(id).length)return Toast.show("Este rolo possui reservas futuras.","error");const rolo=FilamentIntegration.normalizarRolo(Storage.buscarFilamentoPorId(id));Storage.salvarFilamento({...rolo,ativo:false,status:"inativo",localizacao:{tipo:"inativo",impressoraId:null,impressoraNome:"",slotAms:null},atualizadoEm:new Date().toISOString()});FilamentIntegration.registrar("rolo_inativado",id,null,"Rolo inativado.");Modal.fechar();renderFilamentos();Toast.show("Rolo inativado."); }
function reativarRoloFilamento(id) { const rolo=FilamentIntegration.normalizarRolo(Storage.buscarFilamentoPorId(id));Storage.salvarFilamento({...rolo,ativo:true,status:rolo.pesoAtualGramas>0?"estoque":"esgotado",localizacao:{tipo:rolo.pesoAtualGramas>0?"estoque":"esgotado",impressoraId:null,impressoraNome:"",slotAms:null},atualizadoEm:new Date().toISOString()});FilamentIntegration.registrar("rolo_reativado",id,null,"Rolo reativado.");Modal.fechar();renderFilamentos();Toast.show("Rolo reativado."); }

function abrirHistoricoRolo(id) { const rolo=Storage.buscarFilamentoPorId(id),eventos=Storage.listarHistoricoFilamentos().filter(evento=>String(evento.filamentoId)===String(id)).sort((a,b)=>new Date(b.criadoEm)-new Date(a.criadoEm));Modal.abrir(`Histórico — ${rolo?.codigo||"Rolo"}`,FilamentHistoryTimeline.render(eventos));lucide.createIcons(); }
const FilamentHistoryTimeline = { render(eventos) { return `<div class="filamentHistoryTimeline">${eventos.length?eventos.map(evento=>`<article><i></i><div><strong>${escaparFilamento(rotuloEventoFilamento(evento.tipo))}</strong><time>${new Date(evento.criadoEm).toLocaleString("pt-BR")}</time><p>${escaparFilamento(evento.descricao||"")}</p>${evento.dados?.pesoAnteriorGramas!==undefined?`<small>${formatarPesoFilamento(evento.dados.pesoAnteriorGramas)} → ${formatarPesoFilamento(evento.dados.pesoNovoGramas)} · ${evento.dados.diferencaGramas>=0?"+":""}${evento.dados.diferencaGramas} g</small>`:""}</div></article>`).join(""):`<div class="erpEmpty compact"><i data-lucide="history"></i><strong>Sem movimentações registradas</strong></div>`}</div>`; } };

const FilamentFilters = { abrir() { const rolos=Storage.listarFilamentos().map(FilamentIntegration.normalizarRolo),unicos=campo=>[...new Set(rolos.map(r=>r[campo]).filter(Boolean))].sort();Modal.abrir("Filtros de filamentos",`<div class="filamentFiltersGrid">${selectFiltroFilamento("Material","filtroFilamentoMaterial",unicos("material"),filtrosFilamentos.material)}${selectFiltroFilamento("Cor","filtroFilamentoCor",unicos("cor"),filtrosFilamentos.cor)}${selectFiltroFilamento("Marca","filtroFilamentoMarca",unicos("marca"),filtrosFilamentos.marca)}<label class="inputGroup"><span>Localização</span><select id="filtroFilamentoLocal"><option value="">Todas</option><option value="estoque" ${filtrosFilamentos.localizacao==="estoque"?"selected":""}>Estoque</option><option value="ams" ${filtrosFilamentos.localizacao==="ams"?"selected":""}>AMS</option><option value="externo" ${filtrosFilamentos.localizacao==="externo"?"selected":""}>Externo</option></select></label><label class="inputGroup erpFull"><span>Situação</span><select id="filtroFilamentoStatus"><option value="">Ativos</option><option value="em_uso" ${filtrosFilamentos.status==="em_uso"?"selected":""}>Em uso</option><option value="estoque" ${filtrosFilamentos.status==="estoque"?"selected":""}>No estoque</option><option value="baixo" ${filtrosFilamentos.status==="baixo"?"selected":""}>Baixo estoque</option><option value="esgotado" ${filtrosFilamentos.status==="esgotado"?"selected":""}>Esgotados</option><option value="inativo" ${filtrosFilamentos.status==="inativo"?"selected":""}>Inativos</option></select></label></div><div class="modalActions"><button class="btnSecondary" onclick="limparFiltrosFilamentos()">Limpar</button><button class="btn" onclick="aplicarFiltrosFilamentos()">Aplicar filtros</button></div>`); } };
function selectFiltroFilamento(rotulo,id,valores,selecionado){return `<label class="inputGroup"><span>${rotulo}</span><select id="${id}"><option value="">Todos</option>${valores.map(valor=>`<option value="${escaparFilamento(valor)}" ${valor===selecionado?"selected":""}>${escaparFilamento(valor)}</option>`).join("")}</select></label>`;}
function aplicarFiltrosFilamentos(){filtrosFilamentos={material:document.getElementById("filtroFilamentoMaterial").value,cor:document.getElementById("filtroFilamentoCor").value,marca:document.getElementById("filtroFilamentoMarca").value,localizacao:document.getElementById("filtroFilamentoLocal").value,status:document.getElementById("filtroFilamentoStatus").value};Modal.fechar();renderFilamentos();}
function limparFiltrosFilamentos(){filtrosFilamentos={material:"",cor:"",marca:"",localizacao:"",status:""};Modal.fechar();renderFilamentos();}
function quantidadeFiltrosFilamentos(){return Object.values(filtrosFilamentos).filter(Boolean).length;}

function abrirAssistenteMigracaoFilamento(id) { const rolo=FilamentIntegration.normalizarRolo(Storage.buscarFilamentoPorId(id)),sugerida=Math.max(1,Math.round(rolo.pesoAtualGramas/1000));Modal.abrir("Dividir cadastro antigo",`<div class="migrationRollOverview"><i data-lucide="split"></i><div><strong>${escaparFilamento(rolo.material)} ${escaparFilamento(rolo.cor)} · ${formatarPesoFilamento(rolo.pesoAtualGramas)}</strong><p>Quantos rolos físicos formam este saldo?</p></div></div><div class="migrationSuggested"><button onclick="confirmarDivisaoFilamentoLegado('${id}',${sugerida},1000)"><strong>${sugerida} rolos de aproximadamente 1 kg</strong><small>Opção recomendada</small></button><button onclick="mostrarMigracaoPersonalizadaFilamento()"><strong>Informar quantidade e peso</strong><small>Ajustar manualmente</small></button><button onclick="manterLoteTemporarioFilamento('${id}')"><strong>Manter como lote temporário</strong><small>Não dividir agora e preservar o saldo</small></button></div><div id="migracaoFilamentoPersonalizada" class="migrationCustom"><label class="inputGroup"><span>Quantidade</span><input id="migracaoQtdRolos" type="number" min="1" value="${sugerida}"></label><label class="inputGroup"><span>Peso aproximado por rolo (g)</span><input id="migracaoPesoRolo" type="number" min="1" value="${Math.ceil(rolo.pesoAtualGramas/sugerida)}"></label><button class="btn" onclick="confirmarMigracaoPersonalizadaFilamento('${id}')">Dividir cadastro</button></div>`);lucide.createIcons(); }
function mostrarMigracaoPersonalizadaFilamento(){document.getElementById("migracaoFilamentoPersonalizada")?.classList.add("isOpen");}
function confirmarMigracaoPersonalizadaFilamento(id){confirmarDivisaoFilamentoLegado(id,document.getElementById("migracaoQtdRolos").value,document.getElementById("migracaoPesoRolo").value);}
function confirmarDivisaoFilamentoLegado(id,qtd,peso){try{const criados=FilamentIntegration.dividirCadastroLegado(id,qtd,peso);Modal.fechar();renderFilamentos();Toast.show(`${criados.length} rolos físicos criados sem perder o saldo original.`,"success");}catch(erro){Toast.show(erro.message,"error");}}
function manterLoteTemporarioFilamento(id){try{FilamentIntegration.manterLoteTemporario(id);Modal.fechar();renderFilamentos();Toast.show("Cadastro mantido como lote temporário.");}catch(erro){Toast.show(erro.message,"error");}}

function textoLocalizacaoRolo(rolo){const local=FilamentIntegration.localizacaoDoRolo(rolo.id);if(local.tipo==="ams")return `${local.impressoraNome||"Impressora"} · AMS Slot ${local.slotAms}`;if(local.tipo==="externo")return `${local.impressoraNome||"Impressora"} · Rolo externo`;if(rolo.esgotado)return "Esgotado";if(rolo.ativo===false)return "Inativo";return "Estoque";}
function formatarPesoFilamento(gramas){const valor=Math.max(0,Number(gramas)||0);return valor>=1000?`${(valor/1000).toLocaleString("pt-BR",{maximumFractionDigits:2})} kg`:`${valor.toLocaleString("pt-BR",{maximumFractionDigits:0})} g`;}
function normalizarBuscaFilamento(valor){return String(valor||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR").trim();}
function rotuloStatusRolo(status){return ({estoque:"No estoque",carregado:"Carregado",em_uso:"Em uso",reservado:"Reservado",baixo_estoque:"Baixo estoque",esgotado:"Esgotado",inativo:"Inativo"})[status]||status;}
function rotuloEventoFilamento(tipo){return ({rolo_cadastrado:"Rolo cadastrado",rolo_carregado:"Carregado em impressora",rolo_removido:"Removido da impressora",reserva_criada:"Reserva criada",rolo_reservado:"Reserva criada",reserva_liberada:"Reserva liberada",rolo_consumido:"Consumo registrado",reservas_liberadas:"Reserva liberada",peso_corrigido:"Peso corrigido",rolo_esgotado:"Rolo esgotado",rolo_inativado:"Rolo inativado",rolo_reativado:"Rolo reativado",reservas_transferidas:"Reservas transferidas",cadastro_atualizado:"Cadastro atualizado",cadastro_legado_dividido:"Cadastro antigo dividido"})[tipo]||String(tipo||"Evento").replaceAll("_"," ");}
function cardResumoERP(icone,valor,descricao){return `<article class="erpSummaryCard"><i data-lucide="${icone}"></i><strong>${valor}</strong><span>${descricao}</span></article>`;}
function escaparFilamento(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}

window.FilamentGroupCard=FilamentGroupCard;window.FilamentRollCard=FilamentRollCard;window.FilamentGroupSummary=FilamentGroupSummary;window.FilamentRollDetail=FilamentRollDetail;window.FilamentLocationBadge=FilamentLocationBadge;window.AddMultipleRollsModal=AddMultipleRollsModal;window.AdjustRollWeightModal=AdjustRollWeightModal;window.MarkRollEmptyModal=MarkRollEmptyModal;window.FilamentHistoryTimeline=FilamentHistoryTimeline;window.FilamentFilters=FilamentFilters;
