let filtrosFinanceiro = { termo:"", status:"", origem:"", cliente:"", periodo:"", inicio:"", fim:"" };
let periodoFinanceiroRascunho = "";

function renderFinanceiro() {
    const lista=Financeiro.sincronizar(),resumo=Financeiro.calcularResumo(lista);
    app.innerHTML=`<button class="back" onclick="navegar('home')"><i data-lucide="arrow-left"></i> Voltar</button><div class="financePageHeader"><div>${Page.titulo("💰 Financeiro","Contas a receber sincronizadas automaticamente com toda a operação.")}</div><button class="btnSecondary financeFilterTrigger" type="button" onclick="abrirFiltrosFinanceiro()"><i data-lucide="sliders-horizontal"></i><span>Filtros</span></button></div>
        ${renderChipsFinanceiro()}
        <section class="financeSummaryGrid">${cardFinanceiroResumo("calendar-clock",Utils.moeda(resumo.hoje),"Receber hoje")}${cardFinanceiroResumo("calendar-days",Utils.moeda(resumo.semana),"Esta semana")}${cardFinanceiroResumo("calendar-range",Utils.moeda(resumo.mes),"Este mês")}${cardFinanceiroResumo("triangle-alert",Utils.moeda(resumo.atraso),"Em atraso","danger")}${cardFinanceiroResumo("badge-check",Utils.moeda(resumo.recebidoMes),"Recebido no mês","success")}</section>
        <div id="listaFinanceiro" class="financeList"></div>`;
    atualizarListaFinanceiro();lucide.createIcons();
}

function cardFinanceiroResumo(icone,valor,rotulo,estado=""){return `<article class="financeSummaryCard ${estado}"><i data-lucide="${icone}"></i><strong>${valor}</strong><span>${rotulo}</span></article>`;}
function abrirFiltrosFinanceiro(){
    const clientes=Storage.listarClientes().filter(c=>c.ativo!==false).sort((a,b)=>String(a.nome||"").localeCompare(String(b.nome||""),"pt-BR"));
    periodoFinanceiroRascunho=filtrosFinanceiro.periodo;
    Modal.abrir("Filtros do Financeiro",`<div class="financeFilterSheet"><label class="erpSearch"><i data-lucide="search"></i><input id="buscaFinanceiroModal" placeholder="Cliente ou descrição" value="${escaparFinanceiro(filtrosFinanceiro.termo)}"></label><div class="financeFilterRow"><label>Status<select id="statusFinanceiroModal"><option value="">Todos os status</option>${Object.entries(STATUS_FINANCEIRO).map(([v,l])=>`<option value="${v}" ${filtrosFinanceiro.status===v?'selected':''}>${l}</option>`).join("")}</select></label><label>Origem<select id="origemFinanceiroModal"><option value="">Todas as origens</option><option value="pedido" ${filtrosFinanceiro.origem==='pedido'?'selected':''}>Pedido</option><option value="consignado" ${filtrosFinanceiro.origem==='consignado'?'selected':''}>Consignado</option></select></label><label>Cliente<select id="clienteFinanceiroModal"><option value="">Todos os clientes</option>${clientes.map(c=>`<option value="${escaparFinanceiro(c.id)}" ${String(filtrosFinanceiro.cliente)===String(c.id)?'selected':''}>${escaparFinanceiro(c.nome)}</option>`).join("")}</select></label></div><div><span class="financeFilterLabel">Período</span><div class="financePeriodTabs">${[["","Todos"],["hoje","Hoje"],["semana","Semana"],["mes","Mês"],["ano","Ano"],["personalizado","Personalizado"]].map(([v,l])=>`<button type="button" onclick="selecionarPeriodoFinanceiro('${v}')" class="${periodoFinanceiroRascunho===v?'active':''}" data-periodo-financeiro="${v}">${l}</button>`).join("")}</div></div><div id="periodoFinanceiroPersonalizado" class="financeCustomPeriod" ${periodoFinanceiroRascunho==='personalizado'?'':'hidden'}><label>De<input id="financeiroDataInicio" type="date" value="${escaparFinanceiro(filtrosFinanceiro.inicio)}"></label><label>Até<input id="financeiroDataFim" type="date" value="${escaparFinanceiro(filtrosFinanceiro.fim)}"></label></div><div class="financeFilterActions"><button class="btnGhost" type="button" onclick="limparFiltrosFinanceiro()">Limpar filtros</button><button class="btnSecondary" type="button" onclick="Modal.fechar()">Cancelar</button><button class="btn" type="button" onclick="aplicarFiltrosFinanceiro()">Aplicar</button></div></div>`);
    lucide.createIcons();
}
function selecionarPeriodoFinanceiro(periodo){periodoFinanceiroRascunho=periodo;document.querySelectorAll('[data-periodo-financeiro]').forEach(b=>b.classList.toggle('active',b.dataset.periodoFinanceiro===periodo));const personalizado=document.getElementById('periodoFinanceiroPersonalizado');if(personalizado)personalizado.hidden=periodo!=='personalizado';}
function aplicarFiltrosFinanceiro(){filtrosFinanceiro={termo:document.getElementById('buscaFinanceiroModal')?.value.trim()||'',status:document.getElementById('statusFinanceiroModal')?.value||'',origem:document.getElementById('origemFinanceiroModal')?.value||'',cliente:document.getElementById('clienteFinanceiroModal')?.value||'',periodo:periodoFinanceiroRascunho,inicio:document.getElementById('financeiroDataInicio')?.value||'',fim:document.getElementById('financeiroDataFim')?.value||''};Modal.fechar();renderFinanceiro();}
function limparFiltrosFinanceiro(){filtrosFinanceiro={termo:"",status:"",origem:"",cliente:"",periodo:"",inicio:"",fim:""};periodoFinanceiroRascunho="";Modal.fechar();renderFinanceiro();}
function renderChipsFinanceiro(){const cliente=Storage.buscarClientePorId?.(filtrosFinanceiro.cliente)?.nome;const periodo=({hoje:'Hoje',semana:'Semana atual',mes:'Mês atual',ano:'Ano atual',personalizado:'Período personalizado'})[filtrosFinanceiro.periodo];const chips=[periodo,filtrosFinanceiro.termo?`Busca: ${filtrosFinanceiro.termo}`:'',filtrosFinanceiro.status?`Status: ${STATUS_FINANCEIRO[filtrosFinanceiro.status]||filtrosFinanceiro.status}`:'',filtrosFinanceiro.origem?`Origem: ${filtrosFinanceiro.origem==='pedido'?'Pedido':'Consignado'}`:'',cliente?`Cliente: ${cliente}`:''].filter(Boolean);return chips.length?`<section class="financeActiveFilters">${chips.map(c=>`<span>${escaparFinanceiro(c)}</span>`).join('')}<button type="button" onclick="limparFiltrosFinanceiro()">Limpar</button></section>`:'';}
function atualizarListaFinanceiro(){
    const el=document.getElementById('listaFinanceiro');if(!el)return;
    const {termo,status,origem,cliente,periodo,inicio,fim}=filtrosFinanceiro,hoje=Utils.hoje(),fimSemana=somarDiasFinanceiro(hoje,6),mes=hoje.slice(0,7),ano=hoje.slice(0,4);
    const noPeriodo=i=>!periodo||periodo==='hoje'&&i.vencimento===hoje||periodo==='semana'&&i.vencimento>=hoje&&i.vencimento<=fimSemana||periodo==='mes'&&String(i.vencimento||'').startsWith(mes)||periodo==='ano'&&String(i.vencimento||'').startsWith(ano)||periodo==='personalizado'&&(!inicio||i.vencimento>=inicio)&&(!fim||i.vencimento<=fim);
    const lista=Financeiro.sincronizar().filter(i=>(!status||i.status===status)&&(!origem||i.origem===origem)&&(!cliente||String(i.clienteId)===String(cliente))&&[i.clienteNome,i.descricao].join(' ').toLocaleLowerCase('pt-BR').includes(termo.toLocaleLowerCase('pt-BR'))).filter(noPeriodo).sort((a,b)=>{const prioridade={atrasado:0,pendente:1,parcial:2,pago:3,cancelado:4};return prioridade[a.status]-prioridade[b.status]||timestampFinanceiro(a.vencimento)-timestampFinanceiro(b.vencimento);});
    el.innerHTML=lista.length?lista.map(renderCardFinanceiro).join(''):`<div class="erpEmpty"><i data-lucide="wallet-cards"></i><strong>Nenhum lançamento encontrado</strong><p>As contas são criadas automaticamente por Pedidos e Conferências.</p></div>`;lucide.createIcons();
}
function renderCardFinanceiro(i){return `<article class="financeCard status-${i.status}"><div class="financeCardTop"><span class="financeOriginIcon"><i data-lucide="${i.origem==='pedido'?'package':'store'}"></i></span><div><small>${i.origem==='pedido'?'PEDIDO':'CONSIGNADO'}</small><h3>${escaparFinanceiro(i.clienteNome)}</h3><p>${escaparFinanceiro(i.descricao)}</p></div><span class="financeStatus ${i.status}">${STATUS_FINANCEIRO[i.status]||i.status}</span></div><div class="financeValues"><div><span>Valor</span><strong>${Utils.moeda(i.valor)}</strong></div><div><span>Pago</span><strong>${Utils.moeda(i.valorPago)}</strong></div><div class="remaining"><span>Restante</span><strong>${Utils.moeda(i.valorRestante)}</strong></div></div><div class="financeMeta"><span><i data-lucide="calendar"></i> ${formatarDataBR(i.vencimento)}</span><span><i data-lucide="credit-card"></i> ${escaparFinanceiro(i.formaPagamento||'Não definida')}</span></div><div class="financeActions">${!["pago","cancelado"].includes(i.status)?`<button class="btn" onclick="abrirRecebimentoFinanceiro('${i.id}')"><i data-lucide="hand-coins"></i> Receber</button>`:''}<button class="btnSecondary" onclick="editarLancamentoFinanceiro('${i.id}')"><i data-lucide="pencil"></i> Editar</button><button class="btnGhost" onclick="abrirHistoricoFinanceiro('${i.id}')"><i data-lucide="history"></i> Histórico</button></div></article>`;}

function abrirRecebimentoFinanceiro(id){const i=Storage.buscarLancamentoFinanceiroPorId(id);if(!i)return;Modal.abrir('Registrar recebimento',`<div class="receiveHero"><span>Restante</span><strong>${Utils.moeda(i.valorRestante)}</strong><small>${escaparFinanceiro(i.clienteNome)}</small></div><label class="inputGroup"><span>Valor recebido</span><input id="valorRecebimento" type="number" min="0.01" max="${i.valorRestante}" step="0.01" value="${i.valorRestante.toFixed(2)}"></label><label class="inputGroup"><span>Forma de pagamento</span><select id="formaRecebimento">${FORMAS_PAGAMENTO.map(f=>`<option value="${f}" ${i.formaPagamento===f?'selected':''}>${f}</option>`).join('')}</select></label><label class="inputGroup"><span>Observação</span><textarea id="obsRecebimento" rows="2"></textarea></label><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarRecebimentoFinanceiro('${id}')">Confirmar recebimento</button></div>`);}
function confirmarRecebimentoFinanceiro(id){const resultado=Financeiro.registrarRecebimento(id,document.getElementById('valorRecebimento')?.value,document.getElementById('formaRecebimento')?.value,document.getElementById('obsRecebimento')?.value.trim());if(!resultado)return Toast.show('Informe um valor válido.');Modal.fechar();renderFinanceiro();Toast.show(resultado.status==='pago'?'Conta recebida e origem atualizada!':'Recebimento parcial registrado!');}
function editarLancamentoFinanceiro(id){const i=Storage.buscarLancamentoFinanceiroPorId(id);if(!i)return;Modal.abrir('Editar lançamento',`<div class="financeReadOnly"><span>Origem</span><strong>${escaparFinanceiro(i.descricao)}</strong><small>O valor é atualizado automaticamente pelo módulo de origem.</small></div><label class="inputGroup"><span>Vencimento</span><input id="editarVencimentoFinanceiro" type="date" value="${i.vencimento||''}"></label><label class="inputGroup"><span>Forma de pagamento</span><select id="editarFormaFinanceiro"><option value="">Não definida</option>${FORMAS_PAGAMENTO.map(f=>`<option value="${f}" ${i.formaPagamento===f?'selected':''}>${f}</option>`).join('')}</select></label><label class="inputGroup"><span>Observação</span><textarea id="editarObsFinanceiro" rows="3">${escaparFinanceiro(i.observacao||'')}</textarea></label><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="salvarEdicaoFinanceiro('${id}')">Salvar</button></div>`);}
function salvarEdicaoFinanceiro(id){Financeiro.salvarEdicao(id,{vencimento:document.getElementById('editarVencimentoFinanceiro')?.value,formaPagamento:document.getElementById('editarFormaFinanceiro')?.value,observacao:document.getElementById('editarObsFinanceiro')?.value.trim()});Modal.fechar();renderFinanceiro();Toast.show('Lançamento atualizado!');}
function abrirHistoricoFinanceiro(id){const i=Storage.buscarLancamentoFinanceiroPorId(id);if(!i)return;const eventos=[{tipo:'criação',data:i.dataCriacao,valor:i.valor},...(i.historico||[])];Modal.abrir('Histórico financeiro',`<div class="financeHistoryHeader"><strong>${escaparFinanceiro(i.clienteNome)}</strong><span>${escaparFinanceiro(i.descricao)}</span></div><div class="financeHistory">${eventos.sort((a,b)=>timestampFinanceiro(b.data)-timestampFinanceiro(a.data)).map(e=>`<div><span><i data-lucide="${e.tipo==='recebimento'?'badge-check':'plus'}"></i></span><div><strong>${e.tipo==='recebimento'?'Recebimento':'Conta criada'} · ${Utils.moeda(e.valor)}</strong><small>${new Date(e.data).toLocaleString('pt-BR')}${e.formaPagamento?` · ${e.formaPagamento}`:''}</small>${e.observacao?`<p>${escaparFinanceiro(e.observacao)}</p>`:''}</div></div>`).join('')}</div>`);lucide.createIcons();}
