const STATUS_IMPRESSORAS = { livre: "Livre", imprimindo: "Imprimindo", pausada: "Pausada", manutencao: "Manutenção", offline: "Offline" };
let trocaRoloPendente = null;

function renderImpressoras() {
    FilamentIntegration.migrarDados();
    const lista = Storage.listarImpressoras().filter(item => item.ativa !== false);
    const busca = String(document.getElementById("buscaImpressora")?.value || "").toLocaleLowerCase("pt-BR");
    const filtro = document.getElementById("filtroImpressora")?.value || "";
    const filtradas = lista.filter(item => (!filtro || item.status === filtro) && [item.nome, item.modelo, item.fabricante].join(" ").toLocaleLowerCase("pt-BR").includes(busca));
    const hoje=Utils.hoje(),horasHoje=Storage.listarLotesExecucao().filter(l=>String(l.iniciadoEm||"").startsWith(hoje)).reduce((t,l)=>t+Number(l.tempoRealMinutos||Producao.calcularTempoDecorrido(l)||0),0)/60;
    app.innerHTML = `
        <button class="back" onclick="navegar('home')"><i data-lucide="arrow-left"></i> Voltar</button>
        ${Page.titulo("🖨️ Impressoras", "Máquinas, disponibilidade e manutenção em um só lugar.")}
        <section class="erpSummaryGrid printerSummaryGrid">
            ${cardResumoERP("circle-check", lista.filter(i => i.status === "livre").length, "Livres")}
            ${cardResumoERP("printer", lista.filter(i => i.status === "imprimindo").length, "Imprimindo")}
            ${cardResumoERP("pause", lista.filter(i => i.status === "pausada").length, "Pausadas")}
            ${cardResumoERP("wrench", lista.filter(i => i.status === "manutencao").length, "Em manutenção")}
            ${cardResumoERP("power", lista.filter(i => i.status === "offline").length, "Offline")}
            ${cardResumoERP("clock-3", `${horasHoje.toFixed(1)} h`, "Produção hoje")}
        </section>
        <section class="erpToolbar printerToolbar">
            <label class="erpSearch"><i data-lucide="search"></i><input id="buscaImpressora" value="${escaparImpressora(busca)}" placeholder="Nome, modelo ou fabricante" oninput="renderImpressoras()"></label>
            <select id="filtroImpressora" onchange="renderImpressoras()"><option value="">Todos os status</option>${Object.entries(STATUS_IMPRESSORAS).map(([v,l]) => `<option value="${v}" ${v === filtro ? "selected" : ""}>${l}</option>`).join("")}</select>
            <button class="btn erpAddButton" onclick="abrirModalImpressora()"><i data-lucide="plus"></i> Nova impressora</button>
        </section>
        <div class="erpCardGrid printerGrid">${filtradas.length ? filtradas.map(cardImpressora).join("") : `<div class="erpEmpty"><i data-lucide="printer"></i><strong>Nenhuma impressora encontrada</strong><p>Cadastre a primeira máquina para preparar a produção.</p></div>`}</div>`;
    lucide.createIcons();
}

function cardImpressora(item) {
    item = FilamentIntegration.normalizarImpressora(item);
    const limite = Math.max(0, Number(item.limiteManutencaoHoras) || 0);
    const desde = Math.max(0, Number(item.horasDesdeManutencao) || 0);
    const manutencao = limite ? Math.min(100, (desde / limite) * 100) : 0;
    const loteAtual = item.operacaoAtualId ? Storage.buscarLoteExecucaoPorId(item.operacaoAtualId) : null;
    const operacao = loteAtual ? Storage.buscarOperacaoProducaoPorId(loteAtual.operacaoId) : (item.operacaoAtualId ? Storage.buscarOperacaoProducaoPorId(item.operacaoAtualId) : null);
    const ordem = operacao ? Storage.buscarOrdemProducaoPorId(operacao.ordemProducaoId) : null,fila=(item.filaOperacoes||[]).map(id=>Storage.buscarLoteExecucaoPorId(id)).filter(Boolean),decorrido=loteAtual?Producao.calcularTempoDecorrido(loteAtual):0,restante=loteAtual?Math.max(0,Number(loteAtual.tempoPrevistoMinutos||0)-decorrido):0,termino=loteAtual?new Date(Date.now()+restante*60000):null,manutencaoAtiva=Storage.listarManutencoes().find(m=>String(m.impressoraId)===String(item.id)&&m.status==="em_andamento");
    return `<article class="erpEntityCard printerCard visualPrinterCard status-${item.status}" onclick="abrirPainelImpressora('${item.id}')" role="button" tabindex="0">
        <div class="erpEntityTop printerCardIdentity"><div class="printerIcon"><i data-lucide="printer"></i></div><div><h3>${escaparImpressora(item.nome)}</h3><p>${escaparImpressora([item.fabricante,item.modelo].filter(Boolean).join(" · ") || "Modelo não informado")}</p></div><span class="erpBadge printer-${item.status}">${STATUS_IMPRESSORAS[item.status] || item.status}</span></div>
        ${item.status==="manutencao"?`<section class="printerOperationPanel maintenance"><span>MANUTENÇÃO</span><strong>${escaparImpressora(manutencaoAtiva?.observacoes||manutencaoAtiva?.tipo||"Manutenção em andamento")}</strong><div><small>Início</small><b>${manutencaoAtiva?.inicio?new Date(manutencaoAtiva.inicio).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"Não informado"}</b></div></section>`:`<section class="printerOperationPanel ${loteAtual?"running":"idle"}"><span>${loteAtual?"OPERAÇÃO ATUAL":"PRÓXIMA OPERAÇÃO"}</span><strong>${escaparImpressora(ordem?.produtoNome||operacao?.nome||(fila.length?Storage.buscarOperacaoProducaoPorId(fila[0]?.operacaoId)?.nome:"Nenhuma operação na fila"))}</strong>${ordem?`<p>Pedido #${String(ordem.pedidoId).slice(-5)} · Cliente: ${escaparImpressora(ordem.clienteNome)}</p>`:""}${loteAtual?`<div class="printerRuntime"><span>${formatarMinutosProducao(decorrido)} de ${formatarMinutosProducao(loteAtual.tempoPrevistoMinutos)}</span><strong>${Producao.calcularProgressoLote(loteAtual)}%</strong></div><div class="productionProgress"><i><b style="width:${Producao.calcularProgressoLote(loteAtual)}%"></b></i></div><small>Previsão de término: ${termino.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small>`:`<p>${fila.length?`${fila.length} operação(ões) aguardando`:'Impressora disponível para nova produção'}</p>`}</section>`}
        ${resumoAlimentacaoImpressora(item)}
        <div class="productMetrics printerMetrics"><div><span>Mesa</span><strong>${escaparImpressora(item.tamanhoMesa || "-")}</strong></div><div><span>Bico</span><strong>${escaparImpressora(item.bico || "-")}</strong></div><div><span>Horas totais</span><strong>${Number(item.horasTotais || 0).toFixed(1)} h</strong></div><div><span>Próxima manutenção</span><strong>${item.proximaManutencao ? formatarDataBR(item.proximaManutencao) : "-"}</strong></div></div>
        <div class="maintenanceMeter"><div><span>Uso desde manutenção</span><strong>${desde.toFixed(1)} / ${limite || "-"} h</strong></div><i><b style="width:${manutencao}%"></b></i></div>
        <div class="erpCardActions printerActions" onclick="event.stopPropagation()">${loteAtual?`<button class="primaryAction" onclick="navegar('producao')"><i data-lucide="factory"></i> Abrir produção</button>${item.status==="imprimindo"?`<button onclick="pausarLoteUI('${loteAtual.id}')"><i data-lucide="pause"></i> Pausar</button>`:`<button onclick="retomarLoteUI('${loteAtual.id}')"><i data-lucide="play"></i> Retomar</button>`}`:item.status==="manutencao"?`<button class="primaryAction" onclick="concluirManutencaoImpressora('${item.id}')"><i data-lucide="check"></i> Concluir manutenção</button>`:`<button class="primaryAction" onclick="abrirPainelImpressora('${item.id}')"><i data-lucide="list-ordered"></i> Ver fila</button><button onclick="navegar('producao')"><i data-lucide="play"></i> Iniciar operação</button>`}<button onclick="abrirGerenciarFilamentosImpressora('${item.id}')"><i data-lucide="spool"></i> Filamentos</button><button class="printerMoreButton" onclick="abrirMenuImpressora('${item.id}')" aria-label="Mais ações"><i data-lucide="ellipsis"></i></button></div>
    </article>`;
}

function abrirModalImpressora(id = null) {
    const item = id ? FilamentIntegration.normalizarImpressora(Storage.buscarImpressoraPorId(id)) : null;
    Modal.abrir(item ? "Editar impressora" : "Nova impressora", `<div class="erpFormGrid">
        ${Input.text("Nome *", "impNome", "Ex: Bambu A1", item?.nome || "")}
        ${Input.text("Modelo", "impModelo", "A1", item?.modelo || "")}
        ${Input.text("Fabricante", "impFabricante", "Bambu Lab", item?.fabricante || "")}
        ${Input.text("Tamanho da mesa", "impMesa", "256 × 256 × 256 mm", item?.tamanhoMesa || "")}
        ${Input.text("Bico", "impBico", "0.4 mm", item?.bico || "")}
        ${Input.text("Materiais permitidos", "impMateriais", "PLA, PETG, TPU", (item?.materiaisPermitidos || []).join(", "))}
        <label class="inputGroup"><span>Status</span><select id="impStatus">${Object.entries(STATUS_IMPRESSORAS).map(([v,l]) => `<option value="${v}" ${(item?.status || "livre") === v ? "selected" : ""}>${l}</option>`).join("")}</select></label>
        ${Input.number("Horas totais", "impHoras", item?.horasTotais || 0)}
        ${Input.number("Horas desde manutenção", "impHorasManutencao", item?.horasDesdeManutencao || 0)}
        ${Input.number("Limite para manutenção (h)", "impLimite", item?.limiteManutencaoHoras || 500)}
        <label class="favoriteToggle erpFull"><input id="impPossuiAms" type="checkbox" ${item?.possuiAms ? "checked" : ""} onchange="alternarCamposAmsImpressora()"><span>Possui AMS ou alimentador multicolor</span></label>
        <label id="impSlotsAmsGroup" class="inputGroup ${item?.possuiAms ? "" : "isHidden"}"><span>Quantidade de slots AMS</span><input id="impQtdSlots" type="number" min="1" max="16" value="${item?.quantidadeSlotsAms || 4}"></label>
        <label class="inputGroup"><span>Última manutenção</span><input id="impUltima" type="date" value="${item?.ultimaManutencao || ""}"></label>
        <label class="inputGroup"><span>Próxima manutenção</span><input id="impProxima" type="date" value="${item?.proximaManutencao || ""}"></label>
        <label class="inputGroup erpFull"><span>Observações</span><textarea id="impObs" rows="3">${escaparImpressora(item?.observacoes || "")}</textarea></label>
        <div class="modalActions erpFull"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="salvarImpressora('${item?.id || ""}')">Salvar</button></div>
    </div>`); lucide.createIcons();
}

function salvarImpressora(id) {
    const anterior = id ? Storage.buscarImpressoraPorId(id) : null;
    const nome = document.getElementById("impNome")?.value.trim();
    if (!nome) return Toast.show("Informe o nome da impressora.");
    const agora = new Date().toISOString();
    const possuiAms=document.getElementById("impPossuiAms").checked,qtdSlots=possuiAms?Math.max(1,Number(document.getElementById("impQtdSlots").value)||4):0;
    const slotsRemovidos=(anterior?.slotsAms||[]).filter(slot=>slot.filamentoId&&(!possuiAms||Number(slot.numero)>qtdSlots));
    if(slotsRemovidos.length)return Toast.show("Remova os rolos dos slots que serão desativados antes de alterar o AMS.");
    Storage.salvarImpressora(FilamentIntegration.normalizarImpressora({ ...anterior, id: anterior?.id || `imp-${Date.now()}`, nome, modelo: document.getElementById("impModelo").value.trim(), fabricante: document.getElementById("impFabricante").value.trim(), tamanhoMesa: document.getElementById("impMesa").value.trim(), bico: document.getElementById("impBico").value.trim(), materiaisPermitidos: document.getElementById("impMateriais").value.split(",").map(v => v.trim()).filter(Boolean), status: document.getElementById("impStatus").value, operacaoAtualId: anterior?.operacaoAtualId || null, horasTotais: Number(document.getElementById("impHoras").value) || 0, horasDesdeManutencao: Number(document.getElementById("impHorasManutencao").value) || 0, limiteManutencaoHoras: Number(document.getElementById("impLimite").value) || 500, possuiAms, quantidadeSlotsAms:qtdSlots, ultimaManutencao: document.getElementById("impUltima").value, proximaManutencao: document.getElementById("impProxima").value, observacoes: document.getElementById("impObs").value.trim(), ativa: true, criadoEm: anterior?.criadoEm || agora, atualizadoEm: agora }));
    Modal.fechar(); renderImpressoras(); Toast.show("Impressora salva!");
}

function alterarStatusImpressora(id, status) { const item = Storage.buscarImpressoraPorId(id); if (!item) return; item.status = status; item.atualizadoEm = new Date().toISOString(); Storage.salvarImpressora(item); renderImpressoras(); Toast.show("Status atualizado."); }
function iniciarManutencaoImpressora(id) { const item = Storage.buscarImpressoraPorId(id); if (!item) return; const agora = new Date().toISOString(); item.status = "manutencao"; item.atualizadoEm = agora; Storage.salvarImpressora(item); Storage.salvarManutencao({ id: `man-${Date.now()}`, impressoraId: id, tipo: "preventiva", status: "em_andamento", inicio: agora, observacoes: "", pecasTrocadas: [], criadoEm: agora }); renderImpressoras(); Toast.show("Manutenção iniciada."); }
function concluirManutencaoImpressora(id) { const item = Storage.buscarImpressoraPorId(id); if (!item) return; Modal.abrir("Concluir manutenção", `<label class="inputGroup"><span>Tipo</span><select id="manTipo"><option value="preventiva">Preventiva</option><option value="corretiva">Corretiva</option><option value="limpeza">Limpeza</option></select></label>${Input.text("Peças trocadas", "manPecas", "Bico, tubo PTFE...")}<label class="inputGroup"><span>Observações</span><textarea id="manObs" rows="4"></textarea></label><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarConclusaoManutencao('${id}')">Concluir</button></div>`); }
function confirmarConclusaoManutencao(id) { const item = Storage.buscarImpressoraPorId(id); const lista = Storage.listarManutencoes(); const ativa = [...lista].reverse().find(m => String(m.impressoraId) === String(id) && m.status === "em_andamento"); const agora = new Date().toISOString(); if (ativa) Storage.salvarManutencao({ ...ativa, tipo: document.getElementById("manTipo").value, status: "concluida", fim: agora, observacoes: document.getElementById("manObs").value.trim(), pecasTrocadas: document.getElementById("manPecas").value.split(",").map(v => v.trim()).filter(Boolean), atualizadoEm: agora }); item.status = "livre"; item.horasDesdeManutencao = 0; item.ultimaManutencao = Utils.hoje(); item.atualizadoEm = agora; Storage.salvarImpressora(item); Modal.fechar(); renderImpressoras(); Toast.show("Manutenção concluída."); }
function verHistoricoImpressora(id) { const item = Storage.buscarImpressoraPorId(id); const manutencoes = Storage.listarManutencoes().filter(m => String(m.impressoraId) === String(id)).sort((a,b) => new Date(b.inicio) - new Date(a.inicio)); const eventos = Storage.listarHistoricoProducao().filter(e => String(e.impressoraId) === String(id)).sort((a,b) => new Date(b.criadoEm) - new Date(a.criadoEm)); Modal.abrir(`Histórico — ${item?.nome || "Impressora"}`, `<div class="historyList">${[...manutencoes.map(m => ({data:m.inicio,titulo:`Manutenção ${m.tipo}`,texto:m.observacoes || m.status})),...eventos.map(e => ({data:e.criadoEm,titulo:e.tipo,texto:e.descricao}))].sort((a,b)=>new Date(b.data)-new Date(a.data)).map(e=>`<article><i data-lucide="history"></i><div><strong>${escaparImpressora(e.titulo)}</strong><span>${new Date(e.data).toLocaleString("pt-BR")}</span><p>${escaparImpressora(e.texto)}</p></div></article>`).join("") || `<div class="erpEmpty compact">Nenhum histórico registrado.</div>`}</div>`); lucide.createIcons(); }
function alternarCamposAmsImpressora(){document.getElementById("impSlotsAmsGroup")?.classList.toggle("isHidden",!document.getElementById("impPossuiAms")?.checked);}
function resumoAlimentacaoImpressora(item){const slots=item.slotsAms||[],ocupados=slots.filter(s=>s.filamentoId),externo=item.roloExternoId?Storage.buscarFilamentoPorId(item.roloExternoId):null,cores=ocupados.map(s=>s.cor).filter(Boolean);const baixos=[...ocupados.map(s=>Storage.buscarFilamentoPorId(s.filamentoId)),externo].filter(Boolean).filter(r=>FilamentIntegration.pesoDisponivel(r.id)<=Number(r.alertaMinimoKg||0)*1000);return `<section class="printerFilamentSummary"><header><span>${item.possuiAms?`AMS · ${ocupados.length} de ${slots.length} slots ocupados`:"Sem AMS"}</span>${baixos.length?`<b>${baixos.length} baixo estoque</b>`:""}</header><strong>${cores.length?cores.map(escaparImpressora).join(" • "):externo?`${escaparImpressora(externo.material)} ${escaparImpressora(externo.cor)} externo`:"Nenhum rolo carregado"}</strong></section>`;}
function abrirGerenciarFilamentosImpressora(id){const item=FilamentIntegration.normalizarImpressora(Storage.buscarImpressoraPorId(id));if(!item)return Toast.show("Impressora não encontrada.");Modal.abrir(`Filamentos — ${item.nome}`,`${PrinterFilamentSetup.render(item)}<div class="filamentSetupHistory"><button class="btnSecondary" onclick="abrirHistoricoFilamentosImpressora('${id}')"><i data-lucide="history"></i> Histórico de trocas</button></div>`);lucide.createIcons();}
function abrirModalTrocarRolo(impressoraId,tipo,slotNumero){const impressora=FilamentIntegration.normalizarImpressora(Storage.buscarImpressoraPorId(impressoraId));const atualId=tipo==="ams"?impressora.slotsAms.find(s=>Number(s.numero)===Number(slotNumero))?.filamentoId:impressora.roloExternoId;const rolos=Storage.listarFilamentos().map(FilamentIntegration.normalizarRolo).filter(r=>r.ativo!==false&&r.status!=="inativo"&&FilamentIntegration.pesoAtual(r)>0);trocaRoloPendente={impressoraId,tipo,slotNumero,atualId};Modal.abrir(`${atualId?"Trocar":"Carregar"} rolo — ${tipo==="ams"?`Slot ${slotNumero}`:"Externo"}`,`<label class="inputGroup"><span>Rolo físico</span><select id="novoRoloImpressora"><option value="">Selecione</option>${rolos.map(r=>{const local=FilamentIntegration.localDoRolo(r.id);return `<option value="${r.id}" ${String(r.id)===String(atualId)?"selected":""} ${local&&String(r.id)!==String(atualId)?"disabled":""}>${escaparImpressora(r.material)} ${escaparImpressora(r.cor)} — ${escaparImpressora(r.marca||r.codigo)} — ${FilamentIntegration.pesoDisponivel(r.id).toFixed(0)}g livres de ${FilamentIntegration.pesoAtual(r).toFixed(0)}g${local?` · em ${escaparImpressora(local.impressoraNome)}`:""}</option>`}).join("")}</select></label><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarTrocaRoloImpressora()">Confirmar</button></div>`);}
async function confirmarTrocaRoloImpressora(reservas="cancelar"){const novo=document.getElementById("novoRoloImpressora")?.value||trocaRoloPendente?.novoId;if(!novo)return Toast.show("Selecione um rolo.");trocaRoloPendente.novoId=novo;try{await FilamentIntegration.carregarRolo(trocaRoloPendente.impressoraId,trocaRoloPendente.tipo,trocaRoloPendente.slotNumero,novo,{reservas});Modal.fechar();document.querySelector(".productionTabs")?renderProducao():renderImpressoras();Toast.show("Rolo carregado com sucesso!");}catch(e){if(e.codigo==="RESERVAS_ATIVAS")return abrirConflitoReservaTroca();console.error(e);Toast.show(e.message||"Não foi possível carregar o rolo.");}}
function abrirConflitoReservaTroca(){Modal.abrir("Rolo com reservas",`<div class="materialWarning"><i data-lucide="triangle-alert"></i><span>Este rolo possui reservas em operações futuras.</span></div><div class="compactActionMenu"><button onclick="confirmarTrocaRoloImpressora('mover')"><i data-lucide="move"></i><span><strong>Mover reservas</strong><small>Transferir para o novo rolo compatível</small></span></button><button class="danger" onclick="confirmarTrocaRoloImpressora('liberar')"><i data-lucide="unlink"></i><span><strong>Liberar reservas</strong><small>As operações precisarão ser revisadas</small></span></button><button onclick="Modal.fechar();navegar('producao')"><i data-lucide="factory"></i><span><strong>Revisar operações afetadas</strong><small>Abrir a fila de produção sem trocar o rolo</small></span></button><button onclick="Modal.fechar()"><i data-lucide="x"></i><span><strong>Cancelar troca</strong></span></button></div>`);lucide.createIcons();}
async function removerRoloImpressoraUI(impressoraId,tipo,slotNumero,reservas="cancelar"){try{await FilamentIntegration.removerRolo(impressoraId,tipo,slotNumero,{reservas});Modal.fechar();document.querySelector(".productionTabs")?renderProducao():renderImpressoras();Toast.show("Rolo removido.");}catch(e){if(e.codigo==="RESERVAS_ATIVAS"){trocaRoloPendente={impressoraId,tipo,slotNumero,novoId:null};return Modal.abrir("Rolo com reservas",`<p>Este rolo possui reservas em operações futuras.</p><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn dangerButton" onclick="removerRoloImpressoraUI('${impressoraId}','${tipo}',${slotNumero},'liberar')">Liberar reservas e remover</button></div>`);}Toast.show(e.message);}}
function abrirHistoricoFilamentosImpressora(id){const eventos=Storage.listarHistoricoFilamentos().filter(e=>String(e.impressoraId)===String(id)).sort((a,b)=>new Date(b.criadoEm)-new Date(a.criadoEm));Modal.abrir("Histórico de filamentos",`<div class="historyList">${eventos.map(e=>`<article><i data-lucide="spool"></i><div><strong>${escaparImpressora(e.descricao)}</strong><span>${new Date(e.criadoEm).toLocaleString("pt-BR")}</span></div></article>`).join("")||`<div class="erpEmpty compact">Nenhuma troca registrada.</div>`}</div>`);lucide.createIcons();}
function abrirPainelImpressora(id){const imp=FilamentIntegration.normalizarImpressora(Storage.buscarImpressoraPorId(id));if(!imp)return;const atual=imp.operacaoAtualId?Storage.buscarLoteExecucaoPorId(imp.operacaoAtualId):null,fila=(imp.filaOperacoes||[]).map(i=>Storage.buscarLoteExecucaoPorId(i)).filter(Boolean),tempoFila=fila.reduce((t,l)=>t+Number(l.tempoPrevistoMinutos||0),0);Modal.abrir(`${imp.nome} — Painel operacional`,`<div class="printerDetailPanel">${atual?`<section class="printerDetailCurrent"><span>EM EXECUÇÃO</span><strong>${escaparImpressora(Storage.buscarOperacaoProducaoPorId(atual.operacaoId)?.nome||"Operação")}</strong><p>${formatarMinutosProducao(Producao.calcularTempoDecorrido(atual))} de ${formatarMinutosProducao(atual.tempoPrevistoMinutos)} · ${Producao.calcularProgressoLote(atual)}%</p><button class="btn" onclick="Modal.fechar();navegar('producao')">Abrir produção</button></section>`:`<div class="erpEmpty compact"><i data-lucide="coffee"></i><strong>Impressora livre</strong><p>Inicie a próxima operação quando estiver preparada.</p></div>`}<section class="printerQueuePanel"><header><div><span>FILA</span><h3>Próximas operações</h3></div><strong>${formatarMinutosProducao(tempoFila)}</strong></header>${fila.length?fila.map((l,i)=>{const op=Storage.buscarOperacaoProducaoPorId(l.operacaoId),podeReordenar=l.status==="em_fila";return `<article><b>${i+1}</b><div><strong>${escaparImpressora(op?.nome||"Operação")}</strong><small>${l.quantidade} un. · ${formatarMinutosProducao(l.tempoPrevistoMinutos)}</small>${l.status==="aguardando_preparacao"?`<span>Preparação necessária</span>`:""}${FilamentReservationSummary.render(l)}</div><aside>${podeReordenar&&i>0?`<button onclick="moverFilaImpressoraUI('${l.id}',-1,'${id}')" aria-label="Subir"><i data-lucide="arrow-up"></i></button>`:""}${podeReordenar&&i<fila.length-1?`<button onclick="moverFilaImpressoraUI('${l.id}',1,'${id}')" aria-label="Descer"><i data-lucide="arrow-down"></i></button>`:""}<button onclick="Modal.fechar();realocarLoteUI('${l.id}')" aria-label="Mover"><i data-lucide="move"></i></button><button class="danger" onclick="Modal.fechar();removerFilaUI('${l.id}')" aria-label="Remover"><i data-lucide="trash-2"></i></button></aside></article>`}).join(""):`<div class="erpEmpty compact">Nenhuma operação na fila.</div>`}</section><div class="printerDetailLinks"><button onclick="abrirGerenciarFilamentosImpressora('${id}')"><i data-lucide="spool"></i> Filamentos</button><button onclick="verHistoricoImpressora('${id}')"><i data-lucide="history"></i> Histórico</button></div></div>`);lucide.createIcons();}
function moverFilaImpressoraUI(loteId,direcao,impressoraId){try{Producao.moverLoteFila(loteId,direcao);abrirPainelImpressora(impressoraId);Toast.show("Fila reordenada.");}catch(e){Toast.show(e.message);}}
function abrirMenuImpressora(id){const imp=Storage.buscarImpressoraPorId(id);if(!imp)return;Modal.abrir(`Ações — ${imp.nome}`,`<div class="compactActionMenu"><button onclick="Modal.fechar();abrirModalImpressora('${id}')"><i data-lucide="pencil"></i><span><strong>Editar</strong><small>Dados técnicos e manutenção</small></span></button><button onclick="Modal.fechar();abrirPainelImpressora('${id}')"><i data-lucide="list-ordered"></i><span><strong>Ver fila</strong><small>Operações e conflitos</small></span></button><button onclick="Modal.fechar();verHistoricoImpressora('${id}')"><i data-lucide="history"></i><span><strong>Histórico</strong><small>Produções e manutenções</small></span></button>${imp.status!=="manutencao"?`<button onclick="Modal.fechar();iniciarManutencaoImpressora('${id}')"><i data-lucide="wrench"></i><span><strong>Iniciar manutenção</strong><small>Indisponibilizar temporariamente</small></span></button>`:""}</div>`);lucide.createIcons();}
const PrinterStatusCard={render:cardImpressora};const PrinterQueue={abrir:abrirPainelImpressora};window.PrinterStatusCard=PrinterStatusCard;window.PrinterQueue=PrinterQueue;window.STATUS_IMPRESSORAS=STATUS_IMPRESSORAS;
function escaparImpressora(v) { return String(v ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;"); }
