let pedidoEditandoId = null;
let itensPedidoEdicao = [];
let buscaPedidosAtual = "";
let filtrosPedidos = { status: "", pagamento: "", cliente: "", periodo: "", atraso: false, producao: false, prontos: false };
let acaoPedidoPendente = null;

function renderPedidos() {
    Producao.migrarDados();
    const todos=Storage.listarPedidos().filter(p=>p.ativo!==false);
    const pedidos=filtrarPedidos(todos);
    const conta=s=>todos.filter(p=>p.statusPedido===s).length;
    const pendentes=todos.filter(p=>!['entregue','cancelado'].includes(p.statusPedido)).length;
    const receber=todos.reduce((t,p)=>t+Number(p.valorPendente||0),0);
    app.innerHTML=`<button class="back" onclick="navegar('home')"><i data-lucide="arrow-left"></i> Voltar</button>${Page.titulo("📋 Pedidos","Produção, entrega e pagamentos em um só lugar.")}
        <section class="erpSummaryGrid">${cardResumoERP("printer",conta("em_producao"),"Em produção")}${cardResumoERP("package-check",conta("pronto"),"Prontos")}${cardResumoERP("clock-3",pendentes,"Pendentes")}${cardResumoERP("circle-check",conta("entregue"),"Entregues")}${cardResumoERP("wallet",Utils.moeda(receber),"Valor a receber")}</section>
        <section class="erpToolbar"><label class="erpSearch"><i data-lucide="search"></i><input id="pesquisaPedido" placeholder="Cliente, produto ou pedido" value="${escaparPedido(buscaPedidosAtual)}" oninput="buscaPedidosAtual=this.value;atualizarListaPedidos()"></label><button class="btnSecondary orderFilterButton" onclick="abrirFiltrosPedidos()"><i data-lucide="sliders-horizontal"></i> Filtros${contarFiltrosPedidos()?` <b>${contarFiltrosPedidos()}</b>`:""}</button><button class="btn erpAddButton" onclick="abrirModalPedido()"><i data-lucide="plus"></i> Novo pedido</button></section>
        <div id="chipsFiltrosPedidos" class="orderFilterChips">${renderChipsFiltrosPedidos()}</div>
        <div id="listaPedidos" class="erpCardGrid orderGrid">${renderCardsPedidos(pedidos)}</div>`;lucide.createIcons();
}

function atualizarListaPedidos(){
    buscaPedidosAtual=document.getElementById("pesquisaPedido")?.value||buscaPedidosAtual;
    const lista=filtrarPedidos(Storage.listarPedidos().filter(p=>p.ativo!==false));
    const el=document.getElementById("listaPedidos");if(el)el.innerHTML=renderCardsPedidos(lista);lucide.createIcons();
}
function filtrarPedidos(lista){const termo=buscaPedidosAtual.toLocaleLowerCase("pt-BR"),hoje=Utils.hoje(),inicioPeriodo=filtrosPedidos.periodo==='hoje'?hoje:filtrosPedidos.periodo==='semana'?new Date(Date.now()-7*864e5).toISOString().slice(0,10):filtrosPedidos.periodo==='mes'?new Date(Date.now()-30*864e5).toISOString().slice(0,10):"";return lista.filter(p=>(!termo||[p.id,p.clienteNome,...(p.itens||[]).map(i=>i.nome)].join(" ").toLocaleLowerCase("pt-BR").includes(termo))&&(!filtrosPedidos.status||p.statusPedido===filtrosPedidos.status)&&(!filtrosPedidos.pagamento||statusPagamentoPedido(p)===filtrosPedidos.pagamento)&&(!filtrosPedidos.cliente||String(p.clienteId)===String(filtrosPedidos.cliente))&&(!inicioPeriodo||String(p.dataPedido||p.criadoEm)>=inicioPeriodo)&&(!filtrosPedidos.atraso||(p.dataEntregaPrevista&&p.dataEntregaPrevista<hoje&&!['entregue','cancelado'].includes(p.statusPedido)))&&(!filtrosPedidos.producao||p.statusPedido==='em_producao')&&(!filtrosPedidos.prontos||p.statusPedido==='pronto')).sort((a,b)=>new Date(b.criadoEm)-new Date(a.criadoEm));}
function renderCardsPedidos(lista){if(!lista.length)return `<div class="erpEmpty orderEmpty"><i data-lucide="clipboard-list"></i><strong>Nenhum pedido neste filtro</strong><p>Quando um pedido chegar a esta etapa, ele aparecerá aqui.</p>${filtrosPedidos.prontos?`<button class="btnSecondary" onclick="navegar('producao')">Ver produção</button>`:""}</div>`;const ordens=Storage.listarOrdensProducao();return lista.map(p=>{const temOrdem=ordens.some(o=>String(o.pedidoId)===String(p.id)&&o.status!=="cancelada"),tipos=(p.itens||[]).length,pecas=(p.itens||[]).reduce((t,i)=>t+Number(i.quantidade||0),0),pagamento=statusPagamentoPedido(p);return `<article class="erpEntityCard orderCard orderStatus-${p.statusPedido}" role="button" tabindex="0" onclick="abrirDetalhePedido('${p.id}')" onkeydown="if(event.key==='Enter')abrirDetalhePedido('${p.id}')">
    <header class="orderCardHeader"><div class="orderNumber">#${String(p.id).slice(-5)}</div><div><h3>${escaparPedido(p.clienteNome)}</h3><p>${formatarDataBR(p.dataPedido)} · prazo ${formatarDataBR(p.dataEntregaPrevista)}</p></div><div class="orderStatusStack"><span class="erpBadge status-${p.statusPedido}">${rotuloStatusPedido(p.statusPedido)}</span><span class="erpBadge payment-${pagamento}">${rotuloPagamentoPedido(pagamento)}</span></div></header>
    <div class="orderCounts"><span><i data-lucide="boxes"></i><strong>${tipos}</strong> tipo(s)</span><span><i data-lucide="package"></i><strong>${pecas}</strong> peça(s)</span></div>
    <div class="orderFinance"><div><span>Total</span><strong>${Utils.moeda(p.valorTotal)}</strong></div><div><span>Pago</span><strong>${Utils.moeda(p.valorPago)}</strong></div><div class="remaining"><span>Pendente</span><strong>${Utils.moeda(p.valorPendente)}</strong></div></div>
    <div class="erpCardActions orderSmartActions">${renderAcoesPrincipaisPedido(p,temOrdem)}<button class="orderMoreButton" aria-label="Mais ações" onclick="event.stopPropagation();abrirMenuPedido('${p.id}')"><i data-lucide="ellipsis"></i></button></div></article>`;}).join("");}
function renderAcoesPrincipaisPedido(p,temOrdem){const stop="event.stopPropagation();";if(['aguardando_orcamento','aguardando_aceite'].includes(p.statusPedido))return `<button class="primaryAction" onclick="${stop}solicitarStatusPedido('${p.id}','aprovado')"><i data-lucide="check"></i> Aprovar</button><button onclick="${stop}abrirModalPedido('${p.id}')">Editar</button>`;if(p.statusPedido==='aprovado')return `<button class="primaryAction" onclick="${stop}abrirPreviaProducaoPedido('${p.id}')"><i data-lucide="play"></i> Iniciar produção</button><button onclick="${stop}abrirItensPedido('${p.id}')">Ver itens</button>`;if(p.statusPedido==='em_producao')return `<button class="primaryAction" onclick="${stop}navegar('producao',{pedidoId:'${p.id}'})"><i data-lucide="factory"></i> Ver produção</button><button onclick="${stop}abrirItensPedido('${p.id}')">Ver itens</button>`;if(p.statusPedido==='pronto')return `<button class="primaryAction" onclick="${stop}solicitarStatusPedido('${p.id}','entregue')"><i data-lucide="package-check"></i> Entregar</button><button onclick="${stop}abrirItensPedido('${p.id}')">Ver itens</button>`;if(p.statusPedido==='entregue')return `<button class="primaryAction" onclick="${stop}duplicarPedido('${p.id}')"><i data-lucide="copy"></i> Duplicar</button><button onclick="${stop}abrirItensPedido('${p.id}')">Ver itens</button>`;if(p.statusPedido==='cancelado')return `<button class="primaryAction" onclick="${stop}solicitarStatusPedido('${p.id}','aprovado')"><i data-lucide="rotate-ccw"></i> Reativar</button><button onclick="${stop}abrirItensPedido('${p.id}')">Ver itens</button>`;return `<button class="primaryAction" onclick="${stop}${temOrdem?`navegar('producao',{pedidoId:'${p.id}'})`:`abrirPreviaProducaoPedido('${p.id}')`}">Abrir</button><button onclick="${stop}abrirItensPedido('${p.id}')">Ver itens</button>`;}
function statusPagamentoPedido(p){return p.statusPagamento==='pago'?'pago':p.dataEntregaPrevista&&p.dataEntregaPrevista<Utils.hoje()&&Number(p.valorPendente||0)>0?'atrasado':p.statusPagamento||'pendente';}
function rotuloStatusPedido(status){return {aguardando_orcamento:'Aguardando aceite',aguardando_aceite:'Aguardando aceite',aprovado:'Aprovado',em_producao:'Em produção',pronto:'Pronto',entregue:'Entregue',cancelado:'Cancelado'}[status]||STATUS_PEDIDOS[status]||status;}
function rotuloPagamentoPedido(status){return {pendente:'Pendente',parcial:'Parcial',pago:'Pago',atrasado:'Atrasado'}[status]||status;}

function alterarStatusPedido(id,status){executarMudancaStatusPedido(id,status);}
function solicitarStatusPedido(id,status){const p=Storage.buscarPedidoPorId(id);if(!p)return;const dados={entregue:['Marcar pedido como entregue?',`O pedido #${String(id).slice(-5)} será finalizado como entregue.`],cancelado:['Cancelar este pedido?','A produção e o histórico permanecerão disponíveis.'],aprovado:[p.statusPedido==='cancelado'?'Reativar este pedido?':'Aprovar este pedido?',p.statusPedido==='cancelado'?'O pedido voltará para o fluxo de produção.':'O pedido ficará disponível para iniciar produção.']}[status];if(!dados)return executarMudancaStatusPedido(id,status);acaoPedidoPendente={tipo:'status',id,status};Modal.abrir(dados[0],`<p class="confirmationText">${dados[1]}</p><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn ${status==='cancelado'?'dangerButton':''}" onclick="confirmarAcaoPedido()">Confirmar</button></div>`);}
function executarMudancaStatusPedido(id,status){const p=Storage.buscarPedidoPorId(id);if(!p)return;const anterior=p.statusPedido;p.statusPedido=status;p.atualizadoEm=new Date().toISOString();registrarEventoPedido(p,status==='entregue'?'pedido_entregue':status==='cancelado'?'pedido_cancelado':anterior==='cancelado'?'pedido_reativado':status==='aprovado'?'orcamento_aprovado':'status_alterado',rotuloStatusPedido(status),`Status alterado de ${rotuloStatusPedido(anterior)} para ${rotuloStatusPedido(status)}.`);Storage.salvarPedido(p);Financeiro.sincronizar();gerarNotificacoesOperacionais();Modal.fechar();renderPedidos();Toast.show("Status atualizado!");}
function inativarPedido(id){acaoPedidoPendente={tipo:'inativar',id};Modal.abrir("Inativar este pedido?",`<p class="confirmationText">O pedido sairá da lista principal, mas seus dados serão preservados.</p><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn dangerButton" onclick="confirmarAcaoPedido()">Inativar</button></div>`);}
function confirmarAcaoPedido(){const a=acaoPedidoPendente;acaoPedidoPendente=null;if(!a)return Modal.fechar();if(a.tipo==='status')return executarMudancaStatusPedido(a.id,a.status);if(a.tipo==='inativar'){Storage.excluirPedido(a.id);Financeiro.sincronizar();Modal.fechar();renderPedidos();Toast.show("Pedido inativado.");}}

function abrirFiltrosPedidos(){const clientes=Storage.listarClientes().filter(c=>c.ativo!==false).sort((a,b)=>String(a.nome).localeCompare(String(b.nome),'pt-BR'));Modal.abrir("Filtrar pedidos",`<div class="erpFormGrid orderFiltersSheet"><label class="inputGroup"><span>Status do pedido</span><select id="filtroPedidoStatus"><option value="">Todos</option>${Object.entries(STATUS_PEDIDOS).map(([v,l])=>`<option value="${v}" ${filtrosPedidos.status===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="inputGroup"><span>Pagamento</span><select id="filtroPedidoPagamento"><option value="">Todos</option>${[['pendente','Pendente'],['parcial','Parcial'],['pago','Pago'],['atrasado','Atrasado']].map(([v,l])=>`<option value="${v}" ${filtrosPedidos.pagamento===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="inputGroup"><span>Cliente</span><select id="filtroPedidoCliente"><option value="">Todos</option>${clientes.map(c=>`<option value="${c.id}" ${String(filtrosPedidos.cliente)===String(c.id)?'selected':''}>${escaparPedido(c.nome)}</option>`).join('')}</select></label><label class="inputGroup"><span>Período</span><select id="filtroPedidoPeriodo">${[['','Todo o período'],['hoje','Hoje'],['semana','Últimos 7 dias'],['mes','Últimos 30 dias']].map(([v,l])=>`<option value="${v}" ${filtrosPedidos.periodo===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="favoriteToggle"><input id="filtroPedidoAtraso" type="checkbox" ${filtrosPedidos.atraso?'checked':''}><span>Somente atrasados</span></label><label class="favoriteToggle"><input id="filtroPedidoProducao" type="checkbox" ${filtrosPedidos.producao?'checked':''}><span>Em produção</span></label><label class="favoriteToggle"><input id="filtroPedidoProntos" type="checkbox" ${filtrosPedidos.prontos?'checked':''}><span>Prontos para entrega</span></label></div><div class="modalActions"><button class="btnSecondary" onclick="limparFiltrosPedidos()">Limpar</button><button class="btn" onclick="aplicarFiltrosPedidos()">Aplicar filtros</button></div>`);}
function aplicarFiltrosPedidos(){filtrosPedidos={status:document.getElementById('filtroPedidoStatus').value,pagamento:document.getElementById('filtroPedidoPagamento').value,cliente:document.getElementById('filtroPedidoCliente').value,periodo:document.getElementById('filtroPedidoPeriodo').value,atraso:document.getElementById('filtroPedidoAtraso').checked,producao:document.getElementById('filtroPedidoProducao').checked,prontos:document.getElementById('filtroPedidoProntos').checked};Modal.fechar();renderPedidos();}
function limparFiltrosPedidos(){filtrosPedidos={status:"",pagamento:"",cliente:"",periodo:"",atraso:false,producao:false,prontos:false};Modal.fechar();renderPedidos();}
function contarFiltrosPedidos(){return Object.values(filtrosPedidos).filter(Boolean).length;}
function renderChipsFiltrosPedidos(){const chips=[];if(filtrosPedidos.status)chips.push(rotuloStatusPedido(filtrosPedidos.status));if(filtrosPedidos.pagamento)chips.push(rotuloPagamentoPedido(filtrosPedidos.pagamento));if(filtrosPedidos.cliente)chips.push(Storage.buscarClientePorId(filtrosPedidos.cliente)?.nome||'Cliente');if(filtrosPedidos.periodo)chips.push({hoje:'Hoje',semana:'7 dias',mes:'30 dias'}[filtrosPedidos.periodo]);if(filtrosPedidos.atraso)chips.push('Atrasados');if(filtrosPedidos.producao)chips.push('Em produção');if(filtrosPedidos.prontos)chips.push('Prontos');return chips.map(c=>`<span>${escaparPedido(c)}<button onclick="limparFiltrosPedidos()" aria-label="Limpar filtros"><i data-lucide="x"></i></button></span>`).join('');}

function abrirMenuPedido(id){const p=Storage.buscarPedidoPorId(id);if(!p)return;const itens=[];const add=(icone,titulo,descricao,acao,classe='')=>itens.push(`<button class="${classe}" onclick="${acao}"><i data-lucide="${icone}"></i><span><strong>${titulo}</strong><small>${descricao}</small></span></button>`);if(!['pronto','entregue','cancelado'].includes(p.statusPedido))add('pencil','Editar pedido','Alterar dados e itens',`Modal.fechar();abrirModalPedido('${id}')`);if(['aguardando_orcamento','aguardando_aceite','aprovado'].includes(p.statusPedido))add('ban','Cancelar pedido','Preservar dados e interromper o fluxo',`Modal.fechar();solicitarStatusPedido('${id}','cancelado')`,'danger');if(['em_producao','pronto'].includes(p.statusPedido))add('factory','Ver produção','Ordens, filas e execução',`Modal.fechar();navegar('producao',{pedidoId:'${id}'})`);if(['pronto','entregue'].includes(p.statusPedido))add('receipt','Gerar recibo','Preparar comprovante do pedido',`Modal.fechar();gerarReciboPedido('${id}')`);add('history','Histórico','Abrir timeline completa',`Modal.fechar();abrirTimelinePedido('${id}')`);add('copy','Duplicar','Criar um novo pedido baseado neste',`Modal.fechar();duplicarPedido('${id}')`);if(!['em_producao'].includes(p.statusPedido))add('archive','Inativar','Retirar da lista principal',`Modal.fechar();inativarPedido('${id}')`,'danger');Modal.abrir(`Pedido #${String(id).slice(-5)}`,`<div class="compactActionMenu">${itens.join('')}</div>`);lucide.createIcons();}
function abrirDetalhePedido(id){const p=Storage.buscarPedidoPorId(id);if(!p)return;const ordens=Storage.listarOrdensProducao().filter(o=>String(o.pedidoId)===String(id)&&o.status!=='cancelada'),pecas=(p.itens||[]).reduce((t,i)=>t+Number(i.quantidade||0),0);Modal.abrir(`Pedido #${String(id).slice(-5)}`,`<div class="orderQuickDetail"><header><div><span>CLIENTE</span><h3>${escaparPedido(p.clienteNome)}</h3><p>${formatarDataBR(p.dataPedido)} · prazo ${formatarDataBR(p.dataEntregaPrevista)}</p></div><div class="orderStatusStack"><span class="erpBadge status-${p.statusPedido}">${rotuloStatusPedido(p.statusPedido)}</span><span class="erpBadge payment-${statusPagamentoPedido(p)}">${rotuloPagamentoPedido(statusPagamentoPedido(p))}</span></div></header><div class="orderDetailMetrics"><div><span>Itens</span><strong>${(p.itens||[]).length}</strong></div><div><span>Peças</span><strong>${pecas}</strong></div><div><span>Total</span><strong>${Utils.moeda(p.valorTotal)}</strong></div><div><span>Pendente</span><strong>${Utils.moeda(p.valorPendente)}</strong></div></div><button class="orderItemsOpen" onclick="abrirItensPedido('${id}')"><i data-lucide="boxes"></i><span><strong>Ver itens do pedido</strong><small>Quantidades, valores, peso e tempo</small></span><i data-lucide="chevron-right"></i></button><section class="orderProductionSummary"><div><span>PRODUÇÃO</span><strong>${ordens.length?`${ordens.length} ordem(ns) relacionada(s)`:'Ainda não iniciada'}</strong></div>${ordens.length?`<button onclick="Modal.fechar();navegar('producao',{pedidoId:'${id}'})">Abrir produção</button>`:''}</section><section><div class="orderDetailSectionTitle"><span>LINHA DO TEMPO</span><button onclick="abrirTimelinePedido('${id}')">Ver completa</button></div>${renderTimelinePedido(obterTimelinePedido(p).slice(0,4))}</section><div class="orderDetailActions">${renderAcoesPrincipaisPedido(p,ordens.length>0)}<button class="orderMoreButton" onclick="abrirMenuPedido('${id}')"><i data-lucide="ellipsis"></i></button></div></div>`);lucide.createIcons();}
function abrirItensPedido(id){const p=Storage.buscarPedidoPorId(id);if(!p)return;const resumo=calcularResumoItensPedido(p),editavel=!['pronto','entregue','cancelado'].includes(p.statusPedido)&&!Storage.listarOrdensProducao().some(o=>String(o.pedidoId)===String(id)&&['em_producao','em_fila'].includes(o.status));Modal.abrir(`Itens — Pedido #${String(id).slice(-5)}`,`<div class="orderItemsQuick"><header><strong>${escaparPedido(p.clienteNome)}</strong><div><span>${resumo.tipos} tipos</span><span>${resumo.pecas} peças</span><span>${resumo.peso?`${resumo.peso.toFixed(0)} g previstos`:'Peso não informado'}</span><span>${resumo.tempo?formatarMinutosProducao(resumo.tempo):'Tempo não informado'}</span></div></header><div class="orderItemsQuickList">${(p.itens||[]).map(item=>renderItemRapidoPedido(item)).join('')}</div><footer><strong>Total do pedido</strong><span>${Utils.moeda(p.valorTotal)}</span></footer><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Fechar</button>${editavel?`<button class="btn" onclick="Modal.fechar();abrirModalPedido('${id}')">Editar pedido</button>`:''}${Storage.listarOrdensProducao().some(o=>String(o.pedidoId)===String(id))?`<button class="btn" onclick="Modal.fechar();navegar('producao',{pedidoId:'${id}'})">Ver produção</button>`:''}</div></div>`);lucide.createIcons();}
function renderItemRapidoPedido(item){const produto=item.produtoId?Storage.buscarProdutoPorId(item.produtoId):null,qtd=Number(item.quantidade||0),peso=Number(item.pesoPrevistoGramas??produto?.peso??0),receita=produto?Producao.obterReceita(produto):[],tempo=Number(item.tempoPrevistoMinutos||receita.reduce((t,o)=>t+Number(o.tempoMinutos||o.tempoPrevistoMinutos||0),0));return `<article><div><h4>${escaparPedido(item.nome)}</h4><p>${produto?`${escaparPedido(produto.codigo||'Sem código')} · ${escaparPedido(produto.categoria||'Sem categoria')}`:'Produto personalizado'}</p></div><dl><div><dt>Quantidade</dt><dd>${qtd}</dd></div><div><dt>Valor unitário</dt><dd>${Utils.moeda(item.valorUnitario)}</dd></div><div><dt>Subtotal</dt><dd>${Utils.moeda(Number(item.valorTotal||qtd*Number(item.valorUnitario||0)))}</dd></div>${tempo?`<div><dt>Tempo previsto</dt><dd>${formatarMinutosProducao(tempo)} por lote</dd></div>`:''}${peso?`<div><dt>Peso previsto</dt><dd>${peso.toFixed(1)} g por unidade</dd></div>`:''}</dl>${produto?`<button onclick="Modal.fechar();abrirDetalhesProduto('${produto.id}')"><i data-lucide="external-link"></i> Abrir produto</button>`:''}${item.observacao?`<small>${escaparPedido(item.observacao)}</small>`:''}</article>`;}
function calcularResumoItensPedido(p){return (p.itens||[]).reduce((r,i)=>{const produto=i.produtoId?Storage.buscarProdutoPorId(i.produtoId):null,q=Number(i.quantidade||0),peso=Number(i.pesoPrevistoGramas??produto?.peso??0),tempo=Number(i.tempoPrevistoMinutos||0);r.tipos++;r.pecas+=q;r.peso+=peso*q;r.tempo+=tempo*q;return r;},{tipos:0,pecas:0,peso:0,tempo:0});}
function registrarEventoPedido(pedido,tipo,titulo,descricao,origem='pedido'){pedido.timeline=Array.isArray(pedido.timeline)?pedido.timeline:[];const chave=`${tipo}-${titulo}-${pedido.atualizadoEm||''}`;if(!pedido.timeline.some(e=>e.chave===chave))pedido.timeline.push({id:`hist-ped-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,chave,pedidoId:pedido.id,tipo,titulo,descricao,criadoEm:new Date().toISOString(),usuarioId:window.PrimeFirebase?.auth?.currentUser?.uid||null,origem});return pedido;}
function obterTimelinePedido(p){const eventos=[...(p.timeline||[])],ordens=Storage.listarOrdensProducao().filter(o=>String(o.pedidoId)===String(p.id)),ordemIds=new Set(ordens.map(o=>String(o.id)));Storage.listarHistoricoProducao().filter(e=>String(e.pedidoId)===String(p.id)||ordemIds.has(String(e.ordemProducaoId))).forEach(e=>eventos.push({id:e.id,tipo:e.tipo,titulo:e.descricao||rotuloEventoPedido(e.tipo),descricao:e.descricao||'',criadoEm:e.criadoEm,origem:'produção'}));Storage.listarPagamentos().filter(pg=>String(pg.pedidoId)===String(p.id)).forEach(pg=>eventos.push({id:pg.id,tipo:'pagamento_registrado',titulo:'Pagamento registrado',descricao:Utils.moeda(pg.valor),criadoEm:pg.criadoEm||pg.data,origem:'financeiro'}));if(!eventos.some(e=>e.tipo==='pedido_criado'))eventos.push({id:`criado-${p.id}`,tipo:'pedido_criado',titulo:'Pedido criado',descricao:`Pedido para ${p.clienteNome}`,criadoEm:p.criadoEm||p.dataPedido,origem:'sistema'});const vistos=new Set();return eventos.filter(e=>{const chave=`${e.tipo}|${e.criadoEm}|${e.titulo}`;if(vistos.has(chave))return false;vistos.add(chave);return true;}).sort((a,b)=>new Date(b.criadoEm)-new Date(a.criadoEm));}
function rotuloEventoPedido(tipo){return {operacao_alocada:'Produção criada',impressao_iniciada:'Produção iniciada',impressao_concluida:'Produção concluída',pedido_pronto:'Pedido pronto',falha:'Falha de produção'}[tipo]||'Movimentação registrada';}
function renderTimelinePedido(eventos){return eventos.length?`<div class="orderTimeline">${eventos.map(e=>`<article><i></i><div><time>${formatarDataHoraPedido(e.criadoEm)}</time><strong>${escaparPedido(e.titulo||rotuloEventoPedido(e.tipo))}</strong><p>${escaparPedido(e.descricao||'')}</p><span>${escaparPedido(e.origem||'sistema')}</span></div></article>`).join('')}</div>`:`<div class="erpEmpty compact">Nenhuma movimentação registrada.</div>`;}
function abrirTimelinePedido(id){const p=Storage.buscarPedidoPorId(id);if(!p)return;Modal.abrir(`Histórico — Pedido #${String(id).slice(-5)}`,renderTimelinePedido(obterTimelinePedido(p)));}
function formatarDataHoraPedido(valor){const d=new Date(valor);return Number.isNaN(d.getTime())?'-':d.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}
function duplicarPedido(id){const p=Storage.buscarPedidoPorId(id);if(!p)return;const agora=new Date().toISOString(),novo={...p,id:`ped-${Date.now()}`,statusPedido:'aguardando_aceite',statusPagamento:'pendente',valorPago:0,valorPendente:Number(p.valorTotal||0),dataPedido:Utils.hoje(),dataEntregaPrevista:Utils.hoje(),timeline:[],criadoEm:agora,atualizadoEm:agora,ativo:true,itens:(p.itens||[]).map((i,n)=>({...i,id:`item-${Date.now()}-${n}`}))};registrarEventoPedido(novo,'pedido_criado','Pedido duplicado',`Criado a partir do pedido #${String(id).slice(-5)}.`,'sistema');Storage.salvarPedido(novo);Modal.fechar();renderPedidos();Toast.show('Pedido duplicado!');}
function gerarReciboPedido(id){if(window.PDF?.gerarReciboPedido)return PDF.gerarReciboPedido(Storage.buscarPedidoPorId(id));Toast.show('A geração de recibo ficará disponível no próximo refinamento.');}

function abrirModalPedido(id=null,clienteIdInicial=null){const p=id?Storage.buscarPedidoPorId(id):null;if(p&&['pronto','entregue','cancelado'].includes(p.statusPedido))return Toast.show("Este pedido está bloqueado para edição. Reative-o ou revise o histórico.");pedidoEditandoId=p?.id||null;itensPedidoEdicao=(p?.itens||[]).map(i=>({...i}));const clientes=Storage.listarClientes().filter(c=>c.ativo!==false).sort((a,b)=>String(a.nome).localeCompare(String(b.nome),"pt-BR"));const clienteSelecionado=p?.clienteId||clienteIdInicial;Modal.abrir(p?"Editar pedido":"Novo pedido",`<div class="orderForm">
    <div class="erpFormGrid"><label class="inputGroup"><span>Cliente *</span><select id="pedidoCliente"><option value="">Selecione</option>${clientes.map(c=>`<option value="${c.id}" ${String(c.id)===String(clienteSelecionado)?"selected":""}>${escaparPedido(c.nome)}</option>`).join("")}</select></label><button class="btnSecondary quickClientButton" onclick="alternarClienteRapido()"><i data-lucide="user-plus"></i> Cadastrar cliente</button>
    <div id="clienteRapidoPedido" class="quickClientFields erpFull" hidden>${Input.text("Nome *","clienteRapidoNome","Nome do cliente")}${Input.text("WhatsApp","clienteRapidoWhatsapp","(00) 00000-0000")}</div>
    <label class="inputGroup"><span>Data do pedido</span><input id="pedidoData" type="date" value="${p?.dataPedido||Utils.hoje()}"></label><label class="inputGroup"><span>Previsão de entrega</span><input id="pedidoEntrega" type="date" value="${p?.dataEntregaPrevista||Utils.hoje()}"></label>
    <label class="inputGroup"><span>Status</span><select id="pedidoStatus">${Object.entries(STATUS_PEDIDOS).map(([v,l])=>`<option value="${v}" ${(p?.statusPedido||"aguardando_orcamento")===v?"selected":""}>${l}</option>`).join("")}</select></label><label class="inputGroup"><span>Valor pago</span><input id="pedidoValorPago" type="number" min="0" step="0.01" value="${Number(p?.valorPago||0)}"></label></div>
    <section class="orderItemsEditor"><div class="budgetItemsHeader"><div><span>ITENS</span><h3>Produtos do pedido</h3></div></div><label class="erpSearch"><i data-lucide="search"></i><input id="buscaProdutoPedido" placeholder="Buscar produto cadastrado" oninput="renderProdutosPedidoDisponiveis()"></label><div id="produtosPedidoDisponiveis" class="orderProductChoices"></div><button class="btnSecondary" onclick="adicionarItemPersonalizadoPedido()"><i data-lucide="sparkles"></i> Produto personalizado</button><div id="itensPedidoEditor" class="orderEditorItems"></div><div id="totalPedidoEditor" class="orderEditorTotal"></div></section>
    <label class="inputGroup"><span>Observações</span><textarea id="pedidoObservacoes" rows="3">${escaparPedido(p?.observacoes||"")}</textarea></label>
    <div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="salvarPedido()">Salvar pedido</button></div></div>`);renderProdutosPedidoDisponiveis();renderItensPedidoEditor();lucide.createIcons();}

function alternarClienteRapido(){const el=document.getElementById("clienteRapidoPedido");if(el)el.hidden=!el.hidden;}
function renderProdutosPedidoDisponiveis(){const el=document.getElementById("produtosPedidoDisponiveis");if(!el)return;const termo=(document.getElementById("buscaProdutoPedido")?.value||"").toLocaleLowerCase("pt-BR");const produtos=Storage.listarProdutos().filter(p=>p.ativo!==false&&[p.nome,p.codigo].join(" ").toLocaleLowerCase("pt-BR").includes(termo)).sort((a,b)=>(b.favorito?1:0)-(a.favorito?1:0)||String(a.nome).localeCompare(String(b.nome),"pt-BR")).slice(0,6);el.innerHTML=produtos.map(p=>`<button onclick="adicionarProdutoPedido('${p.id}')"><span>${escaparPedido(p.nome)}</span><strong>${Utils.moeda(p.preco)}</strong></button>`).join("")||`<small>Nenhum produto encontrado.</small>`;}
function adicionarProdutoPedido(id){const ex=itensPedidoEdicao.find(i=>String(i.produtoId)===String(id)&&!i.personalizado);if(ex)ex.quantidade+=1;else{const p=Storage.buscarProdutoPorId(id);if(!p)return;itensPedidoEdicao.push({produtoId:p.id,nome:p.nome,quantidade:1,valorUnitario:Number(p.preco)||0,valorTotal:Number(p.preco)||0,personalizado:false,observacao:""});}renderItensPedidoEditor();}
function adicionarItemPersonalizadoPedido(){itensPedidoEdicao.push({produtoId:null,nome:"",quantidade:1,valorUnitario:0,valorTotal:0,personalizado:true,observacao:""});renderItensPedidoEditor();}
function renderItensPedidoEditor(){const el=document.getElementById("itensPedidoEditor");if(!el)return;el.innerHTML=itensPedidoEdicao.map((i,n)=>`<article class="orderEditorItem"><input value="${escaparPedido(i.nome)}" ${i.personalizado?`oninput="editarItemPedido(${n},'nome',this.value)"`:"readonly"} placeholder="Nome do produto"><div><label>Qtd.<input type="number" min="1" value="${i.quantidade}" oninput="editarItemPedido(${n},'quantidade',this.value)"></label><label>Valor unit.<input type="number" min="0" step="0.01" value="${i.valorUnitario}" oninput="editarItemPedido(${n},'valorUnitario',this.value)"></label><strong>${Utils.moeda(i.quantidade*i.valorUnitario)}</strong><button onclick="removerItemPedido(${n})"><i data-lucide="trash-2"></i></button></div><textarea placeholder="Observação do item" oninput="editarItemPedido(${n},'observacao',this.value)">${escaparPedido(i.observacao||"")}</textarea></article>`).join("")||`<div class="erpEmpty compact">Nenhum item adicionado.</div>`;atualizarTotalPedidoEditor();lucide.createIcons();}
function editarItemPedido(n,c,v){const i=itensPedidoEdicao[n];if(!i)return;i[c]=['quantidade','valorUnitario'].includes(c)?Math.max(c==='quantidade'?1:0,Number(v)||0):v;i.valorTotal=i.quantidade*i.valorUnitario;atualizarTotalPedidoEditor();}
function removerItemPedido(n){itensPedidoEdicao.splice(n,1);renderItensPedidoEditor();}
function atualizarTotalPedidoEditor(){const total=itensPedidoEdicao.reduce((t,i)=>t+Number(i.quantidade||0)*Number(i.valorUnitario||0),0);const el=document.getElementById("totalPedidoEditor");if(el)el.innerHTML=`<span>Total do pedido</span><strong>${Utils.moeda(total)}</strong>`;}

function abrirPreviaProducaoPedido(id){const pedido=Storage.buscarPedidoPorId(id);if(!pedido)return Toast.show("Pedido não encontrado.");const existentes=Storage.listarOrdensProducao().filter(o=>String(o.pedidoId)===String(id)&&o.status!=="cancelada");const itens=(pedido.itens||[]).map((item,index)=>({...item,id:item.id||`${pedido.id}-item-${index}`}));Modal.abrir("Iniciar produção",`<div class="productionPreview"><div class="recipeSimpleHint"><i data-lucide="info"></i><span>Selecione os itens. Quantidades, tempos, materiais e dependências serão multiplicados automaticamente.</span></div><div class="productionItemSelection">${itens.map(item=>{const existe=existentes.some(o=>String(o.itemPedidoId)===String(item.id));return `<label class="productionSelectItem ${existe?"isDisabled":""}"><input type="checkbox" name="itemProducao" value="${item.id}" ${existe?"disabled":"checked"} onchange="atualizarPreviaProducaoPedido('${id}')"><span><strong>${item.quantidade}× ${escaparPedido(item.nome)}</strong><small>${existe?"Ordem já criada":item.personalizado?"Produção personalizada":(Storage.buscarProdutoPorId(item.produtoId)?.tipoProducao==="composta"?"Receita composta":"Produção simples")}</small></span></label>`}).join("")}</div><div id="previewOperacoesPedido"></div><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarCriacaoOrdensPedido('${id}')"><i data-lucide="factory"></i> Criar ordens</button></div></div>`);atualizarPreviaProducaoPedido(id);lucide.createIcons();}
function atualizarPreviaProducaoPedido(id){const pedido=Storage.buscarPedidoPorId(id);const ids=[...document.querySelectorAll('input[name="itemProducao"]:checked')].map(el=>el.value);const grupos=Producao.gerarPreviaPedido(pedido,ids);const el=document.getElementById("previewOperacoesPedido");if(!el)return;el.innerHTML=grupos.length?`<div class="productionPreviewGroups">${grupos.map(g=>`<article><header><strong>${g.item.quantidade}× ${escaparPedido(g.item.nome)}</strong><span>${g.operacoes.length} operação(ões)</span></header>${g.operacoes.map(op=>`<div><i data-lucide="${op.tipo==='impressao'?'printer':'circle-dot'}"></i><span>${escaparPedido(op.nome)}<small>${Producao.TIPOS[op.tipo]} · ${op.quantidadeTotal}× · ${Math.round(op.tempoPrevistoMinutos)} min · ${Number(op.pesoPrevistoGramas).toFixed(1)} g${op.materiais?.length?` · ${op.materiais.length} material(is)`:""}</small>${op.materiais?.length?`<small>${op.materiais.map(m=>`${escaparPedido(m.material||"Material")} ${escaparPedido(m.cor||"")} ${Number(m.pesoGramas||0)}g`).join(" · ")}</small>`:""}</span></div>`).join("")}</article>`).join("")}</div>`:`<div class="erpEmpty compact">Selecione ao menos um item.</div>`;lucide.createIcons();}
function confirmarCriacaoOrdensPedido(id){const ids=[...document.querySelectorAll('input[name="itemProducao"]:checked')].map(el=>el.value);if(!ids.length)return Toast.show("Selecione ao menos um item.");try{const ordens=Producao.criarOrdensDoPedido(id,ids),pedido=Storage.buscarPedidoPorId(id);if(pedido){pedido.atualizadoEm=new Date().toISOString();registrarEventoPedido(pedido,'producao_criada','Produção criada',`${ordens.length} ordem(ns) de produção gerada(s).`,'produção');Storage.salvarPedido(pedido);}Modal.fechar();Financeiro.sincronizar();renderPedidos();Toast.show(`${ordens.length} ordem(ns) de produção criada(s)!`);}catch(erro){console.error("Erro ao criar produção",erro);Toast.show(erro.message||"Não foi possível criar as ordens.");}}

function escaparPedido(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}

function salvarPedido(){
    let cliente=Storage.buscarClientePorId(document.getElementById("pedidoCliente")?.value);
    const nomeRapido=document.getElementById("clienteRapidoNome")?.value.trim();
    if(!cliente&&nomeRapido){
        const agoraCliente=new Date().toISOString();
        cliente={id:`cli-${Date.now()}`,nome:nomeRapido,whatsapp:document.getElementById("clienteRapidoWhatsapp")?.value.trim()||"",telefone:"",email:"",cpfCnpj:"",cidade:"",endereco:"",instagram:"",observacoes:"",tipo:"particular",ativo:true,criadoEm:agoraCliente,atualizadoEm:agoraCliente};
        Storage.salvarCliente(cliente);
    }
    if(!cliente)return Toast.show("Selecione ou cadastre um cliente.");
    if(!itensPedidoEdicao.length||itensPedidoEdicao.some(i=>!i.nome))return Toast.show("Adicione e preencha os itens.");
    const anterior=pedidoEditandoId?Storage.buscarPedidoPorId(pedidoEditandoId):null;
    itensPedidoEdicao=itensPedidoEdicao.map((item,index)=>({...item,id:item.id||`${pedidoEditandoId||"novo"}-item-${Date.now()}-${index}`}));
    const total=itensPedidoEdicao.reduce((t,i)=>{i.valorTotal=Number(i.quantidade)*Number(i.valorUnitario);return t+i.valorTotal;},0);
    const pago=Math.min(total,Number(document.getElementById("pedidoValorPago")?.value)||0);
    const agora=new Date().toISOString();
    const diferencaPago=pago-Number(anterior?.valorPago||0);
    const pedido={id:anterior?.id||`ped-${Date.now()}`,clienteId:cliente.id,clienteNome:cliente.nome,clienteWhatsapp:cliente.whatsapp||"",dataPedido:document.getElementById("pedidoData").value,dataEntregaPrevista:document.getElementById("pedidoEntrega").value,itens:itensPedidoEdicao,statusPedido:document.getElementById("pedidoStatus").value,statusPagamento:pago<=0?"pendente":pago>=total?"pago":"parcial",valorTotal:total,valorPago:pago,valorPendente:total-pago,observacoes:document.getElementById("pedidoObservacoes").value.trim(),ativo:true,criadoEm:anterior?.criadoEm||agora,atualizadoEm:agora};
    pedido.timeline=Array.isArray(anterior?.timeline)?[...anterior.timeline]:[];
    registrarEventoPedido(pedido,anterior?'pedido_editado':'pedido_criado',anterior?'Pedido editado':'Pedido criado',anterior?'Dados, itens ou valores do pedido foram atualizados.':`Pedido criado para ${cliente.nome}.`);
    if(diferencaPago>0)registrarEventoPedido(pedido,'pagamento_registrado','Pagamento registrado',Utils.moeda(diferencaPago),'financeiro');
    Storage.salvarPedido(pedido);
    if(diferencaPago>0)Storage.salvarPagamento({id:`pag-${Date.now()}`,clienteId:cliente.id,clienteNome:cliente.nome,pedidoId:pedido.id,valor:diferencaPago,data:Utils.hoje(),tipo:"pedido",criadoEm:agora});
    Financeiro.sincronizar();
    gerarNotificacoesOperacionais();
    Modal.fechar();renderPedidos();Toast.show("Pedido salvo!");
}
