let producaoView = "aguardando";
let producaoTimer = null;
let alocacaoOperacaoId = null;
let alocacaoQuantidades = {};
let alocacaoLoteBaseId = null;

function renderProducao() {
    Producao.migrarDados();
    clearInterval(producaoTimer);
    const ordens = Storage.listarOrdensProducao().filter(o => o.ativo !== false);
    const lotes = Storage.listarLotesExecucao();
    const impressoras = Storage.listarImpressoras().filter(i => i.ativa !== false);
    const hoje = Utils.hoje();
    const atrasadas = lotes.filter(l => ["em_execucao", "pausada"].includes(l.status) && Producao.calcularTempoDecorrido(l) > Number(l.tempoPrevistoMinutos || 0)).length;
    const falhasHoje = lotes.filter(l => l.status === "falhou" && String(l.concluidoEm || "").startsWith(hoje)).length;
    const operacoes = Storage.listarOperacoesProducao();
    const horasPendentes = lotes.filter(l => !["concluido", "falhou", "cancelado"].includes(l.status)).reduce((t,l)=>t+Number(l.tempoPrevistoMinutos||0),0)/60;
    const aguardando = operacoes.filter(o => ["aguardando", "aguardando_dependencia", "aguardando_alocacao"].includes(o.status)).length;
    const montagemPendente = operacoes.filter(o => o.tipo === "montagem" && !["concluida", "cancelada"].includes(o.status)).length;
    app.innerHTML = `<button class="back" onclick="navegar('home')"><i data-lucide="arrow-left"></i> Voltar</button><div class="productionPageHeading">${Page.titulo("🏭 Produção", "Execução real, impressoras, filas e consumo de filamentos.")}<button class="btn productionNewButton" onclick="abrirNovaProducao()"><i data-lucide="plus"></i> Nova produção</button></div>
        <section class="erpSummaryGrid productionSummary">${cardResumoERP("hourglass",aguardando,"Aguardando")}${cardResumoERP("activity",lotes.filter(l=>l.status==="em_execucao").length,"Em execução")}${cardResumoERP("circle-check",impressoras.filter(i=>i.status==="livre").length,"Impressoras livres")}${cardResumoERP("timer-off",atrasadas,"Atrasadas")}${cardResumoERP("blocks",montagemPendente,"Montagem pendente")}${cardResumoERP("triangle-alert",falhasHoje,"Falhas hoje")}${cardResumoERP("clock",`${horasPendentes.toFixed(1)} h`,"Horas pendentes")}</section>
        <nav class="productionTabs" aria-label="Status da produção">${[["aguardando","Aguardando"],["preparando","Preparando"],["fila","Em fila"],["imprimindo","Imprimindo"],["montagem","Montagem"],["acabamento","Acabamento"],["pronto","Pronto"],["falhas","Falhas"]].map(([v,l])=>`<button class="${producaoView===v?"isActive":""}" onclick="alterarVisaoProducao('${v}')">${l}</button>`).join("")}</nav>
        <div id="conteudoProducao">${renderVisaoProducao(ordens,lotes,impressoras)}</div>`;
    lucide.createIcons();
    producaoTimer = setInterval(atualizarContadoresProducao, 30000);
}

function alterarVisaoProducao(visao){producaoView=visao;renderProducao();}

function abrirNovaProducao(){
    Modal.abrir("Nova produção",`<div class="productionOriginChoices"><button type="button" onclick="Modal.fechar();navegar('pedidos')"><span><i data-lucide="shopping-bag"></i></span><div><strong>Produzir pedido</strong><small>Abra um pedido aprovado e envie os itens para produção.</small></div><i data-lucide="arrow-up-right"></i></button><button type="button" onclick="abrirProducaoEstoque()"><span><i data-lucide="warehouse"></i></span><div><strong>Produzir para estoque</strong><small>Fabrique produtos sem criar pedido ou lançamento financeiro.</small></div><i data-lucide="arrow-right"></i></button></div>`);
    lucide.createIcons();
}

function abrirProducaoEstoque(){
    const produtos=Storage.listarProdutos().filter(produto=>produto.ativo!==false).sort((a,b)=>Number(b.favorito)-Number(a.favorito)||String(a.nome).localeCompare(String(b.nome),"pt-BR"));
    if(!produtos.length)return Toast.show("Cadastre um produto antes de iniciar uma produção para estoque.","error");
    Modal.abrir("Produzir para estoque",`<div class="stockProductionForm"><div class="stockProductionNotice"><i data-lucide="info"></i><p>Esta produção usa a mesma receita, fila, impressoras, AMS e consumo de filamento. Ao concluir todas as operações, o estoque do produto será atualizado automaticamente.</p></div><div class="erpFormGrid"><label class="inputGroup erpFull"><span>Produto</span><select id="produtoEstoqueProducao" onchange="atualizarPreviaProducaoEstoque()">${produtos.map(produto=>`<option value="${produto.id}">${produto.favorito?"★ ":""}${escaparProducao(produto.nome)} · estoque ${Number(produto.estoque||0)}</option>`).join("")}</select></label><label class="inputGroup"><span>Quantidade</span><input id="quantidadeEstoqueProducao" type="number" min="1" step="1" value="1" inputmode="numeric" oninput="atualizarPreviaProducaoEstoque()"></label></div><section id="previaProducaoEstoque" class="stockProductionPreview"></section><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarProducaoEstoque()"><i data-lucide="factory"></i> Criar e alocar</button></div></div>`);
    document.querySelector("#modalRoot .modalContainer")?.classList.add("stockProductionModal");
    atualizarPreviaProducaoEstoque();lucide.createIcons();
}

function atualizarPreviaProducaoEstoque(){
    const produto=Storage.buscarProdutoPorId(document.getElementById("produtoEstoqueProducao")?.value);
    const quantidade=Math.max(1,Math.floor(Number(document.getElementById("quantidadeEstoqueProducao")?.value)||1));
    const el=document.getElementById("previaProducaoEstoque");if(!produto||!el)return;
    const operacoes=Producao.obterReceita(produto);
    el.innerHTML=`<header><div><span>OPERAÇÕES NECESSÁRIAS</span><strong>${operacoes.length} etapa(s) para ${quantidade} unidade(s)</strong></div><b>${escaparProducao(produto.nome)}</b></header><div>${operacoes.map((op,index)=>`<article><span>${index+1}</span><div><strong>${escaparProducao(op.nome)}</strong><small>${Producao.TIPOS[op.tipo]||op.tipo} · ${Math.round((((Number(op.tempoHoras)||0)*60+(Number(op.tempoMinutos)||0))*quantidade))} min · ${((Number(op.pesoTotalGramas)||0)*quantidade).toFixed(1)} g</small></div><i data-lucide="${op.tipo==="impressao"?"printer":"blocks"}"></i></article>`).join("")}</div>`;
    lucide.createIcons();
}

function confirmarProducaoEstoque(){
    try{
        const produtoId=document.getElementById("produtoEstoqueProducao")?.value;
        const quantidade=Math.max(1,Math.floor(Number(document.getElementById("quantidadeEstoqueProducao")?.value)||0));
        const ordem=Producao.criarOrdemParaEstoque(produtoId,quantidade);
        Modal.fechar();producaoView="aguardando";renderProducao();
        const primeiraImpressao=Storage.listarOperacoesProducao().find(op=>String(op.ordemProducaoId)===String(ordem.id)&&op.tipo==="impressao"&&!(op.dependencias||[]).length);
        if(primeiraImpressao)abrirModalAlocarOperacao(primeiraImpressao.id);
        else Toast.show("Produção criada. Inicie a primeira operação para continuar.","success");
    }catch(erro){console.error("[PrimeDocs] Produção para estoque:",erro);Toast.show(erro.message||"Não foi possível criar a produção para estoque.","error");}
}

function renderVisaoProducao(ordens,lotes,impressoras){
    const operacoes = Storage.listarOperacoesProducao();
    if(producaoView==="preparando") return renderLotesLista(lotes.filter(l=>l.status==="aguardando_preparacao"),"Nenhuma operação aguardando preparação.");
    if(producaoView==="fila") return renderLotesLista(lotes.filter(l=>["em_fila","pronta_para_iniciar","aguardando_alocacao"].includes(l.status)),"Nenhuma operação na fila.");
    if(producaoView==="imprimindo") { const ativos=lotes.filter(l=>["em_execucao","pausada"].includes(l.status)); return `<div class="productionPrinterGrid">${ativos.map(cardLoteAtivo).join("")||estadoVazioProducao("coffee","Nenhuma impressora em produção. Quando uma operação for iniciada, ela aparecerá aqui.")}</div>`; }
    if(producaoView==="falhas") return renderLotesLista(lotes.filter(l=>l.status==="falhou"),"Nenhuma falha registrada.");
    if(producaoView==="pronto") return `<div class="erpCardGrid productionGrid">${ordens.filter(o=>o.status==="concluida").map(cardOrdemProducao).join("")||estadoVazioProducao("package-check","Nenhuma ordem pronta.")}</div>`;
    if(["montagem","acabamento"].includes(producaoView)) { const ids=new Set(operacoes.filter(o=>o.tipo===producaoView&&!["concluida","cancelada"].includes(o.status)).map(o=>String(o.ordemProducaoId))); return `<div class="erpCardGrid productionGrid">${ordens.filter(o=>ids.has(String(o.id))).map(cardOrdemProducao).join("")||estadoVazioProducao("blocks",`Nenhuma operação de ${producaoView} pendente.`)}</div>`; }
    const idsComLote = new Set(lotes.filter(l=>l.status!=="cancelado").map(l=>String(l.ordemProducaoId)));
    const pendentes = ordens.filter(o=>o.status!=="concluida" && (!idsComLote.has(String(o.id)) || operacoes.some(op=>String(op.ordemProducaoId)===String(o.id)&&["aguardando","aguardando_dependencia","aguardando_alocacao"].includes(op.status))));
    return `<div class="erpCardGrid productionGrid">${pendentes.map(cardOrdemProducao).join("")||estadoVazioProducao("circle-check","Nenhuma operação aguardando. A produção está em dia.")}</div>`;
}

function estadoVazioProducao(icone,texto){return `<div class="erpEmpty"><i data-lucide="${icone}"></i><strong>${texto}</strong></div>`;}

function cardOrdemProducao(ordem){const operacoes=Storage.listarOperacoesProducao().filter(o=>String(o.ordemProducaoId)===String(ordem.id)).sort((a,b)=>Number(a.ordem||0)-Number(b.ordem||0));const lotes=Storage.listarLotesExecucao().filter(l=>String(l.ordemProducaoId)===String(ordem.id)&&l.status!=="cancelado"),concluidas=operacoes.filter(o=>o.status==="concluida").length,progresso=operacoes.length?Math.round(concluidas/operacoes.length*100):0,proxima=operacoes.find(o=>o.status!=="concluida"),lote=proxima?lotes.find(l=>String(l.operacaoId)===String(proxima.id)):null,impressora=lote?Storage.buscarImpressoraPorId(lote.impressoraId):null,estoque=ordem.origem==="estoque";return `<article class="erpEntityCard productionCard visualProductionCard"><div class="erpEntityTop"><div class="orderNumber ${estoque?"isStock":""}">${estoque?'<i data-lucide="warehouse"></i>':`#${String(ordem.pedidoId).slice(-5)}`}</div><div><h3>${escaparProducao(ordem.produtoNome)}</h3><p>${estoque?"Estoque interno":escaparProducao(ordem.clienteNome)} · ${ordem.quantidade} unidade(s)</p></div><span class="erpBadge status-${ordem.status}">${Producao.STATUS_ORDEM[ordem.status]||ordem.status}</span></div><div class="productionCardContext"><div><span>Operação atual</span><strong>${escaparProducao(proxima?.nome||"Produção concluída")}</strong></div><div><span>Impressora</span><strong>${escaparProducao(impressora?.nome||"Não alocada")}</strong></div><div><span>${estoque?"Destino":"Prazo"}</span><strong>${estoque?"Estoque do produto":ordem.prazo?formatarDataBR(ordem.prazo):"Sem prazo"}</strong></div></div><div class="productionProgress"><div><span>${concluidas} de ${operacoes.length} operações</span><strong>${progresso}%</strong></div><i><b style="width:${progresso}%"></b></i></div><div class="productionOpsPreview">${operacoes.slice(0,4).map(op=>`<span class="${op===proxima?'isCurrent':''}"><i data-lucide="${op.tipo==='impressao'?'printer':'circle-dot'}"></i>${escaparProducao(op.nome)} <small>${op.quantidade}×</small></span>`).join("")}</div><div class="erpCardActions productionContextActions">${acaoContextualOrdem(ordem,proxima,lote)}<button onclick="abrirDetalhesOrdemProducao('${ordem.id}')"><i data-lucide="workflow"></i> Ver ordem</button></div></article>`;}

function acaoContextualOrdem(ordem,operacao,lote){if(!operacao)return ordem.origem==="estoque"?`<button class="primaryAction" onclick="navegar('produtos')"><i data-lucide="warehouse"></i> Ver estoque</button>`:`<button class="primaryAction" onclick="navegar('pedidos')"><i data-lucide="package-check"></i> Ver pedido</button>`;if(operacao.tipo!=="impressao"){if(["aguardando","pronta_para_iniciar"].includes(operacao.status))return `<button class="primaryAction" onclick="executarAcaoManual('${operacao.id}','iniciar')"><i data-lucide="play"></i> Iniciar ${operacao.tipo}</button>`;if(operacao.status==="em_execucao")return `<button class="primaryAction" onclick="executarAcaoManual('${operacao.id}','concluir')"><i data-lucide="check"></i> Concluir ${operacao.tipo}</button>`;return `<button class="primaryAction" onclick="abrirDetalhesOrdemProducao('${ordem.id}')"><i data-lucide="git-merge"></i> Ver dependências</button>`;}if(!lote||lote.status==="aguardando_alocacao")return `<button class="primaryAction" onclick="abrirModalAlocarOperacao('${operacao.id}'${lote?`,'${lote.id}'`:''})"><i data-lucide="printer-check"></i> Alocar</button>`;if(lote.status==="aguardando_preparacao")return `<button class="primaryAction" onclick="abrirPreparacaoLote('${lote.id}')"><i data-lucide="spool"></i> Preparar</button>`;if(["pronta_para_iniciar","em_fila"].includes(lote.status))return `<button class="primaryAction" onclick="iniciarLoteUI('${lote.id}')"><i data-lucide="play"></i> Iniciar</button>`;if(["em_execucao","pausada"].includes(lote.status))return `<button class="primaryAction" onclick="abrirDetalhesOrdemProducao('${ordem.id}')"><i data-lucide="activity"></i> Abrir produção</button>`;return `<button class="primaryAction" onclick="abrirDetalhesOrdemProducao('${ordem.id}')"><i data-lucide="eye"></i> Ver detalhes</button>`;}

function abrirDetalhesOrdemProducao(id){const ordem=Storage.buscarOrdemProducaoPorId(id);if(!ordem)return Toast.show("Ordem não encontrada.");const operacoes=Storage.listarOperacoesProducao().filter(o=>String(o.ordemProducaoId)===String(id)).sort((a,b)=>a.ordem-b.ordem);const porId=new Map(operacoes.map(o=>[String(o.id),o])),estoque=ordem.origem==="estoque";Modal.abrir(`Ordem — ${ordem.produtoNome}`,`<div class="productionOrderMeta"><div><span>${estoque?"Origem":"Pedido"}</span><strong>${estoque?"Produção para estoque":`#${String(ordem.pedidoId).slice(-5)}`}</strong></div><div><span>${estoque?"Destino":"Cliente"}</span><strong>${estoque?"Estoque do produto":escaparProducao(ordem.clienteNome)}</strong></div><div><span>Quantidade</span><strong>${ordem.quantidade} un.</strong></div><div><span>Progresso</span><strong>${Number(ordem.progresso||0)}%</strong></div></div><div class="operationExecutionList">${operacoes.map((op,i)=>cardOperacaoDetalhe(op,i,porId)).join("")}</div>`);lucide.createIcons();}

function cardOperacaoDetalhe(op,index,porId){const lotes=Storage.listarLotesExecucao().filter(l=>String(l.operacaoId)===String(op.id)&&l.status!=="cancelado");const dependencias=(op.dependencias||[]).map(dep=>porId.get(String(dep))?.nome||dep);const manual=op.tipo!=="impressao";let acao="";if(manual){if(["aguardando","pronta_para_iniciar"].includes(op.status))acao=`<button class="btn" onclick="executarAcaoManual('${op.id}','iniciar')">Iniciar tarefa</button>`;else if(op.status==="em_execucao")acao=`<button class="btn" onclick="executarAcaoManual('${op.id}','concluir')">Concluir tarefa</button>`;}else if(!lotes.length)acao=`<button class="btn" onclick="abrirModalAlocarOperacao('${op.id}')">Alocar</button>`;return `<article class="operationExecutionCard"><header><div class="operationIndex">${index+1}</div><div><strong>${escaparProducao(op.nome)}</strong><p>${Producao.TIPOS[op.tipo]||op.tipo} · ${op.quantidade}× · ${Math.round(Number(op.tempoPrevistoMinutos)||0)} min</p></div><span class="erpBadge status-${op.status}">${Producao.STATUS_OPERACAO[op.status]||op.status}</span></header>${dependencias.length?`<small>Depende de: ${dependencias.map(escaparProducao).join(", ")}</small>`:""}<div class="operationLots">${lotes.map(cardLoteCompacto).join("")}</div><footer>${acao}<button class="btnSecondary" onclick="abrirHistoricoOperacao('${op.id}')">Histórico</button></footer></article>`;}

function cardLoteCompacto(lote){const impressora=Storage.buscarImpressoraPorId(lote.impressoraId);const progresso=Producao.calcularProgressoLote(lote);return `<article class="executionLot"><div><strong>${lote.quantidade} un. · ${escaparProducao(impressora?.nome||"Sem impressora")}</strong><span>${rotuloStatusLote(lote.status)} · ${Math.round(lote.tempoPrevistoMinutos||0)} min</span></div><div class="miniProgress"><b style="width:${progresso}%"></b></div><div class="lotActions">${botoesLote(lote)}</div></article>`;}

function botoesLote(lote){const menu=`<button class="btnGhost lotMore" onclick="abrirMenuLote('${lote.id}')" aria-label="Mais ações"><i data-lucide="ellipsis"></i></button>`;if(lote.status==="aguardando_alocacao")return `<button class="btn" onclick="abrirModalAlocarOperacao('${lote.operacaoId}','${lote.id}')">Alocar tentativa</button>`;if(lote.status==="aguardando_preparacao")return `<button class="btn" onclick="abrirPreparacaoLote('${lote.id}')"><i data-lucide="spool"></i> Preparar filamentos</button>${menu}`;if(["pronta_para_iniciar","em_fila"].includes(lote.status))return `<button class="btn" onclick="iniciarLoteUI('${lote.id}')">Iniciar</button>${menu}`;if(lote.status==="em_execucao")return `<button class="btn" onclick="abrirModalConcluirLote('${lote.id}')">Concluir</button>${menu}`;if(lote.status==="pausada")return `<button class="btn" onclick="retomarLoteUI('${lote.id}')">Retomar</button>${menu}`;if(lote.status==="falhou")return `<button class="btn" onclick="novaTentativaUI('${lote.id}')">Nova tentativa</button><button class="btnGhost" onclick="abrirResultadoLote('${lote.id}')">Resultado</button>`;return `<button class="btnGhost" onclick="abrirResultadoLote('${lote.id}')">Ver detalhes</button>`;}

function abrirMenuLote(id){const lote=Storage.buscarLoteExecucaoPorId(id);if(!lote)return;let itens="";if(["pronta_para_iniciar","em_fila","aguardando_preparacao"].includes(lote.status))itens=`${lote.status==="aguardando_preparacao"?`<button onclick="Modal.fechar();abrirPreparacaoLote('${id}')"><i data-lucide="spool"></i><span><strong>Gerenciar filamentos</strong><small>Carregar os rolos reservados</small></span></button>`:""}${lote.status==="em_fila"?`<button onclick="Modal.fechar();moverFilaUI('${id}',-1)"><i data-lucide="arrow-up"></i><span><strong>Subir na fila</strong><small>Antecipar esta impressão</small></span></button><button onclick="Modal.fechar();moverFilaUI('${id}',1)"><i data-lucide="arrow-down"></i><span><strong>Descer na fila</strong><small>Adiar esta impressão</small></span></button>`:""}<button onclick="Modal.fechar();realocarLoteUI('${id}')"><i data-lucide="move"></i><span><strong>Mover de impressora</strong><small>Libera a reserva atual e realoca</small></span></button><button class="danger" onclick="Modal.fechar();removerFilaUI('${id}')"><i data-lucide="trash-2"></i><span><strong>Remover da fila</strong><small>Cancela o lote e libera reservas</small></span></button>`;if(lote.status==="em_execucao")itens=`<button onclick="Modal.fechar();pausarLoteUI('${id}')"><i data-lucide="pause"></i><span><strong>Pausar</strong><small>Manter impressora e reservas vinculadas</small></span></button><button class="danger" onclick="Modal.fechar();abrirModalFalhaLote('${id}')"><i data-lucide="triangle-alert"></i><span><strong>Registrar falha</strong><small>Informar perdas e consumo real</small></span></button>`;if(lote.status==="pausada")itens=`<button onclick="Modal.fechar();abrirModalConcluirLote('${id}')"><i data-lucide="check"></i><span><strong>Concluir</strong><small>Confirmar consumo e liberar impressora</small></span></button><button class="danger" onclick="Modal.fechar();abrirModalFalhaLote('${id}')"><i data-lucide="triangle-alert"></i><span><strong>Registrar falha</strong></span></button>`;Modal.abrir("Ações do lote",`<div class="compactActionMenu">${itens}<button onclick="Modal.fechar();abrirResultadoLote('${id}')"><i data-lucide="eye"></i><span><strong>Ver detalhes</strong><small>Tempos, consumo e custos</small></span></button></div>`);lucide.createIcons();}

function abrirModalAlocarOperacao(operacaoId,loteBaseId=""){const {operacao,ordem,pedido}=Producao.contextoOperacao(operacaoId);const loteBase=loteBaseId?Storage.buscarLoteExecucaoPorId(loteBaseId):null;alocacaoOperacaoId=operacaoId;alocacaoLoteBaseId=loteBaseId||null;alocacaoQuantidades={};const contexto=ordem.origem==="estoque"?"Produção para estoque":`Pedido #${String(ordem.pedidoId).slice(-5)} · ${escaparProducao(pedido?.clienteNome||ordem.clienteNome)}`;Modal.abrir(loteBase?"Alocar nova tentativa":"Alocar operação",`<div class="allocationIntro"><strong>${escaparProducao(operacao.nome)}</strong><span>${escaparProducao(ordem.produtoNome)} · ${contexto}</span><div><b>${loteBase?.quantidade||operacao.quantidade} un.</b><b>${Math.round(loteBase?.tempoPrevistoMinutos||operacao.tempoPrevistoMinutos||0)} min</b><b>${Number(loteBase?.pesoPrevistoGramas||operacao.pesoPrevistoGramas||0).toFixed(1)} g</b></div></div><div id="allocationBody"></div><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarAlocacaoOperacao()">Confirmar alocação</button></div>`);renderAlocacaoBody();}

function renderAlocacaoBody(){const {operacao}=Producao.contextoOperacao(alocacaoOperacaoId);const loteBase=alocacaoLoteBaseId?Storage.buscarLoteExecucaoPorId(alocacaoLoteBaseId):null;const alvo=loteBase?.quantidade||operacao.quantidade;const operacaoAlvo=loteBase?{...operacao,quantidade:alvo,filamentosSelecionados:loteBase.filamentosSelecionados||operacao.filamentosSelecionados}:operacao;const impressoras=Storage.listarImpressoras().filter(i=>i.ativa!==false).sort((a,b)=>FilamentIntegration.analisarImpressora(a,operacaoAlvo).pontuacao-FilamentIntegration.analisarImpressora(b,operacaoAlvo).pontuacao);const el=document.getElementById("allocationBody");if(!el)return;el.innerHTML=`<div class="allocationBalance"><span>Distribuído</span><strong>${Object.values(alocacaoQuantidades).reduce((t,v)=>t+Number(v||0),0)} / ${alvo}</strong></div><section class="allocationGroup"><h4>Impressoras sugeridas</h4>${impressoras.map(i=>cardImpressoraAlocacao(i,operacaoAlvo)).join("")||estadoVazioProducao("printer","Nenhuma impressora cadastrada")}</section>`;lucide.createIcons();}

function cardImpressoraAlocacao(impressora,operacao){const analise=FilamentIntegration.analisarImpressora(impressora,operacao);const compativel=Producao.impressoraCompativel(impressora,operacao);const indisponivel=analise.indisponivel||!compativel||!analise.possuiEstoque;const preferencial=String(operacao.impressoraPreferencialId||"")===String(impressora.id);const qtd=Number(alocacaoQuantidades[impressora.id]||0);const atual=impressora.operacaoAtualId?Storage.buscarLoteExecucaoPorId(impressora.operacaoAtualId):null;const liberaEm=atual?Math.max(0,Number(atual.tempoPrevistoMinutos||0)-Producao.calcularTempoDecorrido(atual)):0;return `<article class="allocationPrinter ${indisponivel?"isDisabled":""} ${preferencial?"isPreferred":""}" data-allocation-printer="${impressora.id}"><header><div><strong>${escaparProducao(impressora.nome)} ${preferencial?`<small>Preferencial</small>`:""}</strong><span>${escaparProducao(impressora.modelo||"")} · ${impressora.possuiAms?`${impressora.quantidadeSlotsAms||4} slots AMS`:"rolo externo"}</span></div><span class="compatibilitySeal score-${analise.pontuacao}">${analise.selo}</span></header>${MaterialCompatibilityStatus.render(analise)}${atual?`<p>Ocupada · libera em ${formatarMinutosProducao(liberaEm)}</p>`:""}<label class="allocationQuantity"><span>Quantidade neste lote</span><input type="number" min="0" max="${operacao.quantidade}" value="${qtd}" ${indisponivel?"disabled":""} onchange="atualizarQuantidadeAlocacao('${impressora.id}',this.value)"></label>${qtd>0?`<div class="allocationMaterials">${(operacao.filamentosSelecionados||[]).map(m=>seletorFilamentoAlocacao(impressora,m,qtd,operacao.quantidade)).join("")}</div>`:""}</article>`;}

function seletorFilamentoAlocacao(impressora,material,qtd,total){const necessidade={...material,pesoPrevistoGramas:Number(material.pesoPrevistoGramas||0)*qtd/Math.max(1,total)};const carregado=FilamentIntegration.roloNoCarregamento(impressora,necessidade);const selecionado=carregado?.rolo?.id||material.filamentoPreferencialId||"";return `<div class="allocationFilament"><div><strong>${escaparProducao(material.material)} ${escaparProducao(material.cor)}</strong><span>${necessidade.pesoPrevistoGramas.toFixed(1)} g necessários</span></div>${FilamentRollSelect.render(necessidade,{selecionado,atributos:`data-material-id="${material.materialReceitaId}" required`})}${carregado?`<small class="loadedRollHint"><i data-lucide="check-circle"></i> Já carregado: ${carregado.tipoCarregamento==="ams"?`Slot ${carregado.slotAms}`:"rolo externo"}</small>`:`<small class="preparationHint"><i data-lucide="triangle-alert"></i> O rolo escolhido deverá ser carregado antes de iniciar.</small>`}</div>`;}

function capturarSelecoesAlocacao(){const distribuicoes=[];document.querySelectorAll("[data-allocation-printer]").forEach(card=>{const id=card.dataset.allocationPrinter;const quantidade=Number(alocacaoQuantidades[id]||0);if(quantidade<=0)return;distribuicoes.push({impressoraId:id,quantidade,filamentosSelecionados:[...card.querySelectorAll("[data-material-id]")].map(select=>{const local=FilamentIntegration.localDoRolo(select.value);const carregadoAqui=local&&String(local.impressoraId)===String(id);return {materialReceitaId:select.dataset.materialId,filamentoId:select.value,permitirCorAlternativa:select.selectedOptions[0]?.dataset.alternativo==="true",tipoCarregamento:carregadoAqui?local.tipo:"manual",slotAms:carregadoAqui&&local.tipo==="ams"?local.slotAms:"",preparacaoNecessaria:!carregadoAqui};})});});return distribuicoes;}
function atualizarQuantidadeAlocacao(id,valor){alocacaoQuantidades[id]=Math.max(0,Number(valor)||0);renderAlocacaoBody();}
function confirmarAlocacaoOperacao(){try{const lotes=Producao.criarAlocacao(alocacaoOperacaoId,capturarSelecoesAlocacao(),alocacaoLoteBaseId||"");Modal.fechar();renderProducao();Toast.show(`${lotes.length} lote(s) alocado(s) com reservas criadas.`);}catch(e){console.error(e);Toast.show(e.message||"Falha ao alocar.");}}

async function iniciarLoteUI(id){try{Toast.show("Validando impressora e reservas...");await Producao.iniciarLoteExecucao(id);Modal.fechar();renderProducao();Toast.show("Produção iniciada!");}catch(e){console.error(e);Toast.show(e.message||"Não foi possível iniciar.");}}
function pausarLoteUI(id){try{Producao.pausarLoteExecucao(id);Modal.fechar();renderProducao();Toast.show("Produção pausada.");}catch(e){Toast.show(e.message);}}
function retomarLoteUI(id){try{Producao.retomarLoteExecucao(id);Modal.fechar();renderProducao();Toast.show("Produção retomada.");}catch(e){Toast.show(e.message);}}
function moverFilaUI(id,d){try{Producao.moverLoteFila(id,d);abrirDetalhesOrdemProducao(Storage.buscarLoteExecucaoPorId(id).ordemProducaoId);Toast.show("Fila reordenada.");}catch(e){Toast.show(e.message);}}
function realocarLoteUI(id){try{const lote=Producao.prepararRealocacaoLote(id);abrirModalAlocarOperacao(lote.operacaoId,lote.id);}catch(e){Toast.show(e.message);}}
function removerFilaUI(id){try{const lote=Producao.removerLoteFilaExecucao(id);abrirDetalhesOrdemProducao(lote.ordemProducaoId);Toast.show("Lote removido e reserva liberada.");}catch(e){Toast.show(e.message);}}

function abrirPreparacaoLote(id){const lote=Storage.buscarLoteExecucaoPorId(id);const impressora=lote?Storage.buscarImpressoraPorId(lote.impressoraId):null;if(!lote||!impressora)return Toast.show("Lote ou impressora não encontrado.");Modal.abrir("Preparar filamentos",`<div class="preparationOverview"><strong>${escaparProducao(impressora.nome)}</strong><p>Carregue cada rolo reservado no local indicado antes de iniciar.</p>${FilamentReservationSummary.render(lote)}</div>${PrinterFilamentSetup.render(impressora)}<div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Fechar</button><button class="btn" onclick="confirmarPreparacaoLoteUI('${id}')">Validar preparação</button></div>`);lucide.createIcons();}
function confirmarPreparacaoLoteUI(id){try{Producao.confirmarPreparacaoLote(id);Modal.fechar();renderProducao();Toast.show("Preparação concluída. Lote pronto para iniciar!");}catch(e){console.error(e);Toast.show(e.message||"A preparação ainda está incompleta.");}}

function abrirModalConcluirLote(id){const lote=Storage.buscarLoteExecucaoPorId(id);if(!lote)return;Modal.abrir("Concluir produção",`<div class="completionOverview"><div><span>Previsto</span><strong>${formatarMinutosProducao(lote.tempoPrevistoMinutos)}</strong></div><div><span>Tempo real</span><strong>${formatarMinutosProducao(Producao.calcularTempoDecorrido(lote))}</strong></div></div><div class="automaticConsumptionNotice"><i data-lucide="spool"></i><div><strong>Consumo automático pela receita</strong><p>${(lote.filamentosSelecionados||[]).map(m=>`${escaparProducao(m.material)} ${escaparProducao(m.cor)}: ${Number(m.pesoPrevistoGramas||0).toFixed(1)} g`).join(" · ")}</p></div></div><label class="inputGroup"><span>Resultado</span><select id="resultadoLote"><option value="sucesso">Sucesso</option><option value="parcial">Parcial</option></select></label><div class="erpFormGrid"><label class="inputGroup"><span>Quantidade concluída</span><input id="qtdConcluida" type="number" min="0" max="${lote.quantidade}" value="${lote.quantidade}"></label><label class="inputGroup"><span>Peças com defeito</span><input id="qtdDefeito" type="number" min="0" value="0"></label></div><label class="inputGroup"><span>Observações</span><textarea id="obsConclusao" rows="3"></textarea></label><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarConclusaoLote('${id}')">Concluir e atualizar estoque</button></div>`);lucide.createIcons();}
function confirmarConclusaoLote(id){try{const r=Producao.concluirLoteExecucao(id,{resultado:document.getElementById("resultadoLote").value,quantidadeConcluida:document.getElementById("qtdConcluida").value,pecasDefeito:document.getElementById("qtdDefeito").value,observacoes:document.getElementById("obsConclusao").value});Modal.fechar();renderProducao();Toast.show(r.pedido?.statusPedido==="pronto"?"Produção concluída e pedido pronto!":"Lote concluído com consumo previsto da receita!","success");}catch(e){console.error(e);Toast.show(e.message,"error");}}

function abrirModalFalhaLote(id){const lote=Storage.buscarLoteExecucaoPorId(id);if(!lote)return;Modal.abrir("Registrar falha",`<label class="inputGroup"><span>Motivo</span><select id="motivoFalha">${["Soltou da mesa","Entupimento","Falta de energia","Erro de filamento","Falha de camada","Problema mecânico","Cancelado pelo usuário","Outro"].map(v=>`<option>${v}</option>`).join("")}</select></label><div class="failureConsumptionChoice"><strong>Como tratar o filamento?</strong><label><input type="radio" name="estrategiaConsumoFalha" value="previsto" checked><span><b>Usar consumo previsto</b><small>Recomendado · usa os pesos da receita</small></span></label><label><input type="radio" name="estrategiaConsumoFalha" value="nao_descontar"><span><b>Não descontar agora</b><small>Mantém o saldo físico do rolo</small></span></label><label><input type="radio" name="estrategiaConsumoFalha" value="ajustar_depois"><span><b>Ajustar o peso depois</b><small>Usa o previsto e permite corrigir em Filamentos</small></span></label><p>O PrimeDocs usará o consumo previsto da receita. Você poderá corrigir o peso do rolo depois.</p></div><label class="inputGroup"><span>Quantidade perdida</span><input id="qtdPerdida" type="number" min="0" max="${lote.quantidade}" value="${lote.quantidade}"></label><label class="inputGroup"><span>Observações</span><textarea id="obsFalha" rows="3"></textarea></label><label class="favoriteToggle"><input id="repetirFalha" type="checkbox" checked><span>Criar nova tentativa</span></label><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn dangerButton" onclick="confirmarFalhaLote('${id}')">Registrar falha</button></div>`);}
function confirmarFalhaLote(id){try{const lote=Storage.buscarLoteExecucaoPorId(id),estrategia=document.querySelector("[name='estrategiaConsumoFalha']:checked")?.value||"previsto",consumos=estrategia==="nao_descontar"?(lote.filamentosSelecionados||[]).map(m=>({materialReceitaId:m.materialReceitaId,pesoRealGramas:0})):undefined;Producao.registrarFalhaLote(id,{motivoFalha:document.getElementById("motivoFalha").value,pecasDefeito:document.getElementById("qtdPerdida").value,observacoes:document.getElementById("obsFalha").value,repetir:document.getElementById("repetirFalha").checked,estrategiaConsumo:estrategia,consumos});Modal.fechar();renderProducao();Toast.show(estrategia==="nao_descontar"?"Falha registrada sem descontar filamento.":"Falha registrada usando o consumo previsto.","success");}catch(e){console.error(e);Toast.show(e.message,"error");}}
function novaTentativaUI(id){try{Producao.criarNovaTentativa(id);Modal.fechar();renderProducao();Toast.show("Nova tentativa criada. Faça uma nova alocação.");}catch(e){Toast.show(e.message);}}

function executarAcaoManual(id,acao){try{if(acao==="iniciar")Producao.iniciarOperacaoManual(id);else Producao.concluirOperacaoManual(id);const ordem=Storage.buscarOperacaoProducaoPorId(id)?.ordemProducaoId;abrirDetalhesOrdemProducao(ordem);Toast.show(acao==="iniciar"?"Tarefa iniciada.":"Tarefa concluída.");}catch(e){Toast.show(e.message);}}
function abrirHistoricoOperacao(id){const eventos=Storage.listarHistoricoProducao().filter(e=>String(e.operacaoId)===String(id)).sort((a,b)=>new Date(b.criadoEm)-new Date(a.criadoEm));Modal.abrir("Histórico da operação",`<div class="historyList">${eventos.map(e=>`<article><i data-lucide="history"></i><div><strong>${escaparProducao(e.descricao||e.tipo)}</strong><span>${new Date(e.criadoEm).toLocaleString("pt-BR")}</span></div></article>`).join("")||estadoVazioProducao("history","Sem eventos")}</div>`);lucide.createIcons();}
function abrirResultadoLote(id){const l=Storage.buscarLoteExecucaoPorId(id);if(!l)return;Modal.abrir("Resultado do lote",`<div class="productionOrderMeta"><div><span>Status</span><strong>${rotuloStatusLote(l.status)}</strong></div><div><span>Tempo real</span><strong>${formatarMinutosProducao(l.tempoRealMinutos||Producao.calcularTempoDecorrido(l))}</strong></div><div><span>Custo real</span><strong>${Utils.moeda(l.custoReal||0)}</strong></div><div><span>Resultado</span><strong>${escaparProducao(l.resultado||"-")}</strong></div></div>`);}

function cardLoteAtivo(lote){const op=Storage.buscarOperacaoProducaoPorId(lote.operacaoId);const ordem=Storage.buscarOrdemProducaoPorId(lote.ordemProducaoId);const imp=Storage.buscarImpressoraPorId(lote.impressoraId);const dec=Producao.calcularTempoDecorrido(lote);const prog=Producao.calcularProgressoLote(lote);const restante=Math.max(0,Number(lote.tempoPrevistoMinutos||0)-dec);const termino=new Date(Date.now()+restante*60000);const excedeu=dec>Number(lote.tempoPrevistoMinutos||0),contexto=ordem?.origem==="estoque"?"Produção para estoque":`Pedido #${String(lote.pedidoId).slice(-5)} · ${escaparProducao(ordem?.clienteNome||"")}`;return `<article class="activePrinterCard" data-live-lote="${lote.id}"><header><div><span class="liveDot"></span><strong>${escaparProducao(imp?.nome||lote.impressoraNome)}</strong></div><span class="erpBadge printer-${lote.status==='pausada'?'pausada':'imprimindo'}">${lote.status==='pausada'?'Pausada':'Ocupada'}</span></header><h3>${escaparProducao(ordem?.produtoNome||op?.produtoNome)}</h3><p>${contexto}</p><div class="activePrinterMeta"><div><span>Operação</span><strong>${escaparProducao(op?.nome||"")}</strong></div><div><span>Quantidade</span><strong>${lote.quantidade} un.</strong></div><div><span>Decorrido</span><strong data-live-time>${formatarMinutosProducao(dec)}</strong></div><div><span>Previsão</span><strong>${termino.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</strong></div></div><div class="productionProgress"><div><span>${excedeu?`Ultrapassou ${formatarMinutosProducao(dec-lote.tempoPrevistoMinutos)}`:`Restam ${formatarMinutosProducao(restante)}`}</span><strong data-live-progress>${prog}%</strong></div><i><b style="width:${prog}%"></b></i></div><div class="activeFilaments">${(lote.filamentosSelecionados||[]).map(m=>`<span><i data-lucide="spool"></i>${escaparProducao(m.material)} ${escaparProducao(m.cor)}</span>`).join("")}</div><footer>${botoesLote(lote)}</footer></article>`;}
function cardImpressoraProducao(imp){const lote=imp.operacaoAtualId?Storage.buscarLoteExecucaoPorId(imp.operacaoAtualId):null;if(lote)return cardLoteAtivo(lote);const fila=(imp.filaOperacoes||[]).map(id=>Storage.buscarLoteExecucaoPorId(id)).filter(Boolean);return `<article class="erpEntityCard printerQueueCard"><div class="erpEntityTop"><div class="printerIcon"><i data-lucide="printer"></i></div><div><h3>${escaparProducao(imp.nome)}</h3><p>${escaparProducao(imp.modelo||"")}</p></div><span class="erpBadge printer-${imp.status}">${STATUS_IMPRESSORAS[imp.status]||imp.status}</span></div><div class="printerQueueSummary"><span>${fila.length} na fila</span><strong>${formatarMinutosProducao(fila.reduce((t,l)=>t+Number(l.tempoPrevistoMinutos||0),0))}</strong></div>${fila.map((l,i)=>`<div class="queueItem"><b>${i+1}</b><span>${escaparProducao(Storage.buscarOperacaoProducaoPorId(l.operacaoId)?.nome||"Operação")}<small>${l.quantidade} un.</small></span></div>`).join("")}</article>`;}
function renderFilaGeral(lotes){const fila=lotes.filter(l=>["em_fila","pronta_para_iniciar","aguardando_preparacao","aguardando_alocacao"].includes(l.status)).sort((a,b)=>Number(a.posicaoFila||999)-Number(b.posicaoFila||999));return `<div class="queueGeneral">${fila.map(l=>`<article>${cardLoteCompacto(l)}</article>`).join("")||estadoVazioProducao("list-ordered","Fila vazia")}</div>`;}
function renderLotesLista(lotes,vazio){return `<div class="queueGeneral">${lotes.sort((a,b)=>new Date(b.concluidoEm)-new Date(a.concluidoEm)).map(l=>`<article>${cardLoteCompacto(l)}</article>`).join("")||estadoVazioProducao("package-check",vazio)}</div>`;}
function atualizarContadoresProducao(){document.querySelectorAll("[data-live-lote]").forEach(card=>{const lote=Storage.buscarLoteExecucaoPorId(card.dataset.liveLote);if(!lote)return;const tempo=Producao.calcularTempoDecorrido(lote);const progresso=Producao.calcularProgressoLote(lote);const t=card.querySelector("[data-live-time]");const p=card.querySelector("[data-live-progress]");const b=card.querySelector(".productionProgress b");if(t)t.textContent=formatarMinutosProducao(tempo);if(p)p.textContent=`${progresso}%`;if(b)b.style.width=`${progresso}%`;});}
function rotuloStatusLote(status){return {aguardando_alocacao:"Aguardando alocação",aguardando_preparacao:"Preparação necessária",pronta_para_iniciar:"Pronto para iniciar",em_fila:"Em fila",em_execucao:"Em execução",pausada:"Pausada",concluido:"Concluído",falhou:"Falhou",cancelado:"Cancelado"}[status]||status;}
function formatarMinutosProducao(min){const total=Math.max(0,Math.round(Number(min)||0));return total>=60?`${Math.floor(total/60)}h${String(total%60).padStart(2,"0")}`:`${total} min`;}
function escaparProducao(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
const ProductionStatusCard={render:cardOrdemProducao};
window.ProductionStatusCard=ProductionStatusCard;
