let producaoView = "atual";
let producaoTimer = null;
let alocacaoOperacaoId = null;
let alocacaoQuantidades = {};
let alocacaoLoteBaseId = null;

function renderProducao() {
    Producao.migrarDados();
    clearInterval(producaoTimer);
    const ordens = Storage.listarOrdensProducao().filter(o => o.ativo !== false);
    const lotes = Storage.listarLotesExecucao();
    const impressoras = Storage.listarImpressoras().filter(i => i.ativa !== false);
    const hoje = Utils.hoje();
    const atrasadas = lotes.filter(l => ["em_execucao", "pausada"].includes(l.status) && Producao.calcularTempoDecorrido(l) > Number(l.tempoPrevistoMinutos || 0)).length;
    const falhasHoje = lotes.filter(l => l.status === "falhou" && String(l.concluidoEm || "").startsWith(hoje)).length;
    const horasPendentes = lotes.filter(l => !["concluido", "falhou", "cancelado"].includes(l.status)).reduce((t,l)=>t+Number(l.tempoPrevistoMinutos||0),0)/60;
    app.innerHTML = `<button class="back" onclick="navegar('home')"><i data-lucide="arrow-left"></i> Voltar</button>${Page.titulo("🏭 Produção", "Execução real, impressoras, filas e consumo de filamentos.")}
        <section class="erpSummaryGrid productionSummary">${cardResumoERP("activity",lotes.filter(l=>l.status==="em_execucao").length,"Em execução")}${cardResumoERP("printer",impressoras.filter(i=>["imprimindo","pausada"].includes(i.status)).length,"Impressoras ocupadas")}${cardResumoERP("circle-check",impressoras.filter(i=>i.status==="livre").length,"Impressoras livres")}${cardResumoERP("list-ordered",lotes.filter(l=>l.status==="em_fila").length,"Em fila")}${cardResumoERP("timer-off",atrasadas,"Atrasadas")}${cardResumoERP("triangle-alert",falhasHoje,"Falhas hoje")}${cardResumoERP("clock",`${horasPendentes.toFixed(1)} h`,"Horas pendentes")}</section>
        <nav class="productionTabs">${[["atual","Produção atual"],["fila","Fila geral"],["impressoras","Por impressora"],["pedidos","Por pedido"],["concluidas","Concluídas"],["falhas","Falhas"]].map(([v,l])=>`<button class="${producaoView===v?"isActive":""}" onclick="alterarVisaoProducao('${v}')">${l}</button>`).join("")}</nav>
        <div id="conteudoProducao">${renderVisaoProducao(ordens,lotes,impressoras)}</div>`;
    lucide.createIcons();
    producaoTimer = setInterval(atualizarContadoresProducao, 30000);
}

function alterarVisaoProducao(visao){producaoView=visao;renderProducao();}

function renderVisaoProducao(ordens,lotes,impressoras){
    if(producaoView==="impressoras")return `<div class="productionPrinterGrid">${impressoras.map(cardImpressoraProducao).join("")||estadoVazioProducao("printer","Nenhuma impressora cadastrada")}</div>`;
    if(producaoView==="fila")return renderFilaGeral(lotes);
    if(producaoView==="concluidas")return renderLotesLista(lotes.filter(l=>l.status==="concluido"),"Nenhuma produção concluída.");
    if(producaoView==="falhas")return renderLotesLista(lotes.filter(l=>l.status==="falhou"),"Nenhuma falha registrada.");
    if(producaoView==="pedidos")return `<div class="erpCardGrid productionGrid">${ordens.map(cardOrdemProducao).join("")||estadoVazioProducao("factory","Nenhuma ordem de produção")}</div>`;
    const ativos=lotes.filter(l=>["em_execucao","pausada"].includes(l.status));
    const aguardando=ordens.filter(o=>o.status!=="concluida");
    return `<section class="productionSection"><div class="productionSectionHeader"><div><span>AGORA</span><h3>Impressões em andamento</h3></div></div><div class="productionPrinterGrid">${ativos.length?ativos.map(l=>cardLoteAtivo(l)).join(""):estadoVazioProducao("coffee","Nenhuma impressão em execução")}</div></section><section class="productionSection"><div class="productionSectionHeader"><div><span>ORDENS</span><h3>Produção pendente</h3></div></div><div class="erpCardGrid productionGrid">${aguardando.map(cardOrdemProducao).join("")||estadoVazioProducao("circle-check","Tudo produzido")}</div></section>`;
}

function estadoVazioProducao(icone,texto){return `<div class="erpEmpty"><i data-lucide="${icone}"></i><strong>${texto}</strong></div>`;}

function cardOrdemProducao(ordem){const operacoes=Storage.listarOperacoesProducao().filter(o=>String(o.ordemProducaoId)===String(ordem.id));const concluidas=operacoes.filter(o=>o.status==="concluida").length;const progresso=operacoes.length?Math.round(concluidas/operacoes.length*100):0;return `<article class="erpEntityCard productionCard"><div class="erpEntityTop"><div class="orderNumber">#${String(ordem.pedidoId).slice(-5)}</div><div><h3>${escaparProducao(ordem.produtoNome)}</h3><p>${escaparProducao(ordem.clienteNome)} · ${ordem.quantidade} unidade(s)</p></div><span class="erpBadge status-${ordem.status}">${Producao.STATUS_ORDEM[ordem.status]||ordem.status}</span></div><div class="productionProgress"><div><span>${concluidas} de ${operacoes.length} operações</span><strong>${progresso}%</strong></div><i><b style="width:${progresso}%"></b></i></div><div class="productionOpsPreview">${operacoes.slice(0,4).map(op=>`<span><i data-lucide="${op.tipo==='impressao'?'printer':'circle-dot'}"></i>${escaparProducao(op.nome)} <small>${op.quantidade}×</small></span>`).join("")}</div><div class="erpCardActions"><button class="primaryAction" onclick="abrirDetalhesOrdemProducao('${ordem.id}')"><i data-lucide="workflow"></i> Operações</button><button onclick="navegar('pedidos')"><i data-lucide="clipboard-list"></i> Pedido</button></div></article>`;}

function abrirDetalhesOrdemProducao(id){const ordem=Storage.buscarOrdemProducaoPorId(id);if(!ordem)return Toast.show("Ordem não encontrada.");const operacoes=Storage.listarOperacoesProducao().filter(o=>String(o.ordemProducaoId)===String(id)).sort((a,b)=>a.ordem-b.ordem);const porId=new Map(operacoes.map(o=>[String(o.id),o]));Modal.abrir(`Ordem — ${ordem.produtoNome}`,`<div class="productionOrderMeta"><div><span>Pedido</span><strong>#${String(ordem.pedidoId).slice(-5)}</strong></div><div><span>Cliente</span><strong>${escaparProducao(ordem.clienteNome)}</strong></div><div><span>Prazo</span><strong>${ordem.prazo?formatarDataBR(ordem.prazo):"-"}</strong></div><div><span>Progresso</span><strong>${Number(ordem.progresso||0)}%</strong></div></div><div class="operationExecutionList">${operacoes.map((op,i)=>cardOperacaoDetalhe(op,i,porId)).join("")}</div>`);lucide.createIcons();}

function cardOperacaoDetalhe(op,index,porId){const lotes=Storage.listarLotesExecucao().filter(l=>String(l.operacaoId)===String(op.id)&&l.status!=="cancelado");const dependencias=(op.dependencias||[]).map(dep=>porId.get(String(dep))?.nome||dep);const manual=op.tipo!=="impressao";let acao="";if(manual){if(["aguardando","pronta_para_iniciar"].includes(op.status))acao=`<button class="btn" onclick="executarAcaoManual('${op.id}','iniciar')">Iniciar tarefa</button>`;else if(op.status==="em_execucao")acao=`<button class="btn" onclick="executarAcaoManual('${op.id}','concluir')">Concluir tarefa</button>`;}else if(!lotes.length)acao=`<button class="btn" onclick="abrirModalAlocarOperacao('${op.id}')">Alocar</button>`;return `<article class="operationExecutionCard"><header><div class="operationIndex">${index+1}</div><div><strong>${escaparProducao(op.nome)}</strong><p>${Producao.TIPOS[op.tipo]||op.tipo} · ${op.quantidade}× · ${Math.round(Number(op.tempoPrevistoMinutos)||0)} min</p></div><span class="erpBadge status-${op.status}">${Producao.STATUS_OPERACAO[op.status]||op.status}</span></header>${dependencias.length?`<small>Depende de: ${dependencias.map(escaparProducao).join(", ")}</small>`:""}<div class="operationLots">${lotes.map(cardLoteCompacto).join("")}</div><footer>${acao}<button class="btnSecondary" onclick="abrirHistoricoOperacao('${op.id}')">Histórico</button></footer></article>`;}

function cardLoteCompacto(lote){const impressora=Storage.buscarImpressoraPorId(lote.impressoraId);const progresso=Producao.calcularProgressoLote(lote);return `<article class="executionLot"><div><strong>${lote.quantidade} un. · ${escaparProducao(impressora?.nome||"Sem impressora")}</strong><span>${rotuloStatusLote(lote.status)} · ${Math.round(lote.tempoPrevistoMinutos||0)} min</span></div><div class="miniProgress"><b style="width:${progresso}%"></b></div><div class="lotActions">${botoesLote(lote)}</div></article>`;}

function botoesLote(lote){const menu=`<button class="btnGhost lotMore" onclick="abrirMenuLote('${lote.id}')" aria-label="Mais ações"><i data-lucide="ellipsis"></i></button>`;if(lote.status==="aguardando_alocacao")return `<button class="btn" onclick="abrirModalAlocarOperacao('${lote.operacaoId}','${lote.id}')">Alocar tentativa</button>`;if(["pronta_para_iniciar","em_fila"].includes(lote.status))return `<button class="btn" onclick="iniciarLoteUI('${lote.id}')">Iniciar</button>${menu}`;if(lote.status==="em_execucao")return `<button class="btn" onclick="abrirModalConcluirLote('${lote.id}')">Concluir</button>${menu}`;if(lote.status==="pausada")return `<button class="btn" onclick="retomarLoteUI('${lote.id}')">Retomar</button>${menu}`;if(lote.status==="falhou")return `<button class="btn" onclick="novaTentativaUI('${lote.id}')">Nova tentativa</button><button class="btnGhost" onclick="abrirResultadoLote('${lote.id}')">Resultado</button>`;return `<button class="btnGhost" onclick="abrirResultadoLote('${lote.id}')">Ver detalhes</button>`;}

function abrirMenuLote(id){const lote=Storage.buscarLoteExecucaoPorId(id);if(!lote)return;let itens="";if(["pronta_para_iniciar","em_fila"].includes(lote.status))itens=`${lote.status==="em_fila"?`<button onclick="Modal.fechar();moverFilaUI('${id}',-1)"><i data-lucide="arrow-up"></i><span><strong>Subir na fila</strong><small>Antecipar esta impressão</small></span></button><button onclick="Modal.fechar();moverFilaUI('${id}',1)"><i data-lucide="arrow-down"></i><span><strong>Descer na fila</strong><small>Adiar esta impressão</small></span></button>`:""}<button onclick="Modal.fechar();realocarLoteUI('${id}')"><i data-lucide="move"></i><span><strong>Mover de impressora</strong><small>Libera a reserva atual e realoca</small></span></button><button class="danger" onclick="Modal.fechar();removerFilaUI('${id}')"><i data-lucide="trash-2"></i><span><strong>Remover da fila</strong><small>Cancela o lote e libera reservas</small></span></button>`;if(lote.status==="em_execucao")itens=`<button onclick="Modal.fechar();pausarLoteUI('${id}')"><i data-lucide="pause"></i><span><strong>Pausar</strong><small>Manter impressora e reservas vinculadas</small></span></button><button class="danger" onclick="Modal.fechar();abrirModalFalhaLote('${id}')"><i data-lucide="triangle-alert"></i><span><strong>Registrar falha</strong><small>Informar perdas e consumo real</small></span></button>`;if(lote.status==="pausada")itens=`<button onclick="Modal.fechar();abrirModalConcluirLote('${id}')"><i data-lucide="check"></i><span><strong>Concluir</strong><small>Confirmar consumo e liberar impressora</small></span></button><button class="danger" onclick="Modal.fechar();abrirModalFalhaLote('${id}')"><i data-lucide="triangle-alert"></i><span><strong>Registrar falha</strong></span></button>`;Modal.abrir("Ações do lote",`<div class="compactActionMenu">${itens}<button onclick="Modal.fechar();abrirResultadoLote('${id}')"><i data-lucide="eye"></i><span><strong>Ver detalhes</strong><small>Tempos, consumo e custos</small></span></button></div>`);lucide.createIcons();}

function abrirModalAlocarOperacao(operacaoId,loteBaseId=""){const {operacao,ordem,pedido}=Producao.contextoOperacao(operacaoId);const loteBase=loteBaseId?Storage.buscarLoteExecucaoPorId(loteBaseId):null;alocacaoOperacaoId=operacaoId;alocacaoLoteBaseId=loteBaseId||null;alocacaoQuantidades={};Modal.abrir(loteBase?"Alocar nova tentativa":"Alocar operação",`<div class="allocationIntro"><strong>${escaparProducao(operacao.nome)}</strong><span>${escaparProducao(ordem.produtoNome)} · Pedido #${String(ordem.pedidoId).slice(-5)} · ${escaparProducao(pedido?.clienteNome||ordem.clienteNome)}</span><div><b>${loteBase?.quantidade||operacao.quantidade} un.</b><b>${Math.round(loteBase?.tempoPrevistoMinutos||operacao.tempoPrevistoMinutos||0)} min</b><b>${Number(loteBase?.pesoPrevistoGramas||operacao.pesoPrevistoGramas||0).toFixed(1)} g</b></div></div><div id="allocationBody"></div><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarAlocacaoOperacao()">Confirmar alocação</button></div>`);renderAlocacaoBody();}

function renderAlocacaoBody(){const {operacao}=Producao.contextoOperacao(alocacaoOperacaoId);const loteBase=alocacaoLoteBaseId?Storage.buscarLoteExecucaoPorId(alocacaoLoteBaseId):null;const alvo=loteBase?.quantidade||operacao.quantidade;const operacaoAlvo=loteBase?{...operacao,quantidade:alvo,filamentosSelecionados:loteBase.filamentosSelecionados||operacao.filamentosSelecionados}:operacao;const impressoras=Storage.listarImpressoras().filter(i=>i.ativa!==false);const grupos=[["livre","Livres"],["imprimindo","Ocupadas"],["pausada","Pausadas"],["manutencao","Em manutenção"],["offline","Offline"]];const el=document.getElementById("allocationBody");if(!el)return;el.innerHTML=`<div class="allocationBalance"><span>Distribuído</span><strong>${Object.values(alocacaoQuantidades).reduce((t,v)=>t+Number(v||0),0)} / ${alvo}</strong></div>${grupos.map(([status,titulo])=>{const lista=impressoras.filter(i=>i.status===status);return lista.length?`<section class="allocationGroup"><h4>${titulo}</h4>${lista.map(i=>cardImpressoraAlocacao(i,operacaoAlvo)).join("")}</section>`:""}).join("")}`;lucide.createIcons();}

function cardImpressoraAlocacao(impressora,operacao){const compativel=Producao.impressoraCompativel(impressora,operacao);const indisponivel=["manutencao","offline"].includes(impressora.status)||!compativel;const preferencial=String(operacao.impressoraPreferencialId||"")===String(impressora.id);const qtd=Number(alocacaoQuantidades[impressora.id]||0);const atual=impressora.operacaoAtualId?Storage.buscarLoteExecucaoPorId(impressora.operacaoAtualId):null;const atualOp=atual?Storage.buscarOperacaoProducaoPorId(atual.operacaoId):null;const liberaEm=atual?Math.max(0,Number(atual.tempoPrevistoMinutos||0)-Producao.calcularTempoDecorrido(atual)):0;return `<article class="allocationPrinter ${indisponivel?"isDisabled":""} ${preferencial?"isPreferred":""}" data-allocation-printer="${impressora.id}"><header><div><strong>${escaparProducao(impressora.nome)} ${preferencial?`<small>Preferencial</small>`:""}</strong><span>${escaparProducao(impressora.modelo||"")} · bico ${escaparProducao(impressora.bico||"-")}</span></div><span class="erpBadge printer-${impressora.status}">${STATUS_IMPRESSORAS[impressora.status]||impressora.status}</span></header><p>${escaparProducao((impressora.materiaisPermitidos||[]).join(", ")||"Todos os materiais")} · ${Number(impressora.horasDesdeManutencao||0).toFixed(1)} h desde manutenção${atual?` · atual: ${escaparProducao(atualOp?.nome||"operação")} · libera em ${formatarMinutosProducao(liberaEm)}`:""}</p><label class="allocationQuantity"><span>Quantidade neste lote</span><input type="number" min="0" max="${operacao.quantidade}" value="${qtd}" ${indisponivel?"disabled":""} onchange="atualizarQuantidadeAlocacao('${impressora.id}',this.value)"></label>${qtd>0?`<div class="allocationMaterials">${(operacao.filamentosSelecionados||[]).map(m=>seletorFilamentoAlocacao(impressora,m,qtd,operacao.quantidade)).join("")}</div>`:""}</article>`;}

function seletorFilamentoAlocacao(impressora,material,qtd,total){const necessaria=Number(material.pesoPrevistoGramas||0)*qtd/Math.max(1,total);const filamentos=Storage.listarFilamentos().filter(f=>f.ativo!==false&&(!material.material||String(f.material).toLowerCase()===String(material.material).toLowerCase())&&(!material.cor||String(f.cor).toLowerCase()===String(material.cor).toLowerCase()));return `<label class="allocationFilament"><span>${escaparProducao(material.material)} ${escaparProducao(material.cor)} · ${necessaria.toFixed(1)} g</span><select data-material-id="${material.materialReceitaId}" required><option value="">Selecione o rolo</option>${filamentos.map(f=>{const disp=Producao.pesoDisponivelFilamento(f.id);return `<option value="${f.id}" ${String(material.filamentoPreferencialId)===String(f.id)?"selected":""} ${disp<necessaria?"disabled":""}>${escaparProducao(f.marca||"Sem marca")} · ${disp.toFixed(0)} g disponíveis · ${Utils.moeda(f.precoKg)}/kg</option>`}).join("")}</select><input data-slot-material="${material.materialReceitaId}" placeholder="Slot AMS (opcional)" value="${escaparProducao(material.slotAms??"")}"></label>`;}

function capturarSelecoesAlocacao(){const distribuicoes=[];document.querySelectorAll("[data-allocation-printer]").forEach(card=>{const id=card.dataset.allocationPrinter;const quantidade=Number(alocacaoQuantidades[id]||0);if(quantidade<=0)return;distribuicoes.push({impressoraId:id,quantidade,filamentosSelecionados:[...card.querySelectorAll("[data-material-id]")].map(select=>({materialReceitaId:select.dataset.materialId,filamentoId:select.value,slotAms:card.querySelector(`[data-slot-material="${select.dataset.materialId}"]`)?.value||""}))});});return distribuicoes;}
function atualizarQuantidadeAlocacao(id,valor){alocacaoQuantidades[id]=Math.max(0,Number(valor)||0);renderAlocacaoBody();}
function confirmarAlocacaoOperacao(){try{const lotes=Producao.criarAlocacao(alocacaoOperacaoId,capturarSelecoesAlocacao(),alocacaoLoteBaseId||"");Modal.fechar();renderProducao();Toast.show(`${lotes.length} lote(s) alocado(s) com reservas criadas.`);}catch(e){console.error(e);Toast.show(e.message||"Falha ao alocar.");}}

async function iniciarLoteUI(id){try{Toast.show("Validando impressora e reservas...");await Producao.iniciarLoteExecucao(id);Modal.fechar();renderProducao();Toast.show("Produção iniciada!");}catch(e){console.error(e);Toast.show(e.message||"Não foi possível iniciar.");}}
function pausarLoteUI(id){try{Producao.pausarLoteExecucao(id);Modal.fechar();renderProducao();Toast.show("Produção pausada.");}catch(e){Toast.show(e.message);}}
function retomarLoteUI(id){try{Producao.retomarLoteExecucao(id);Modal.fechar();renderProducao();Toast.show("Produção retomada.");}catch(e){Toast.show(e.message);}}
function moverFilaUI(id,d){try{Producao.moverLoteFila(id,d);abrirDetalhesOrdemProducao(Storage.buscarLoteExecucaoPorId(id).ordemProducaoId);Toast.show("Fila reordenada.");}catch(e){Toast.show(e.message);}}
function realocarLoteUI(id){try{const lote=Producao.prepararRealocacaoLote(id);abrirModalAlocarOperacao(lote.operacaoId,lote.id);}catch(e){Toast.show(e.message);}}
function removerFilaUI(id){try{const lote=Producao.removerLoteFilaExecucao(id);abrirDetalhesOrdemProducao(lote.ordemProducaoId);Toast.show("Lote removido e reserva liberada.");}catch(e){Toast.show(e.message);}}

function abrirModalConcluirLote(id){const lote=Storage.buscarLoteExecucaoPorId(id);if(!lote)return;Modal.abrir("Concluir produção",`<div class="completionOverview"><div><span>Previsto</span><strong>${formatarMinutosProducao(lote.tempoPrevistoMinutos)}</strong></div><div><span>Tempo real</span><strong>${formatarMinutosProducao(Producao.calcularTempoDecorrido(lote))}</strong></div></div><label class="inputGroup"><span>Resultado</span><select id="resultadoLote"><option value="sucesso">Sucesso</option><option value="parcial">Parcial</option></select></label><div class="completionMaterials">${(lote.filamentosSelecionados||[]).map(m=>`<label><span>${escaparProducao(m.material)} ${escaparProducao(m.cor)} · previsto ${Number(m.pesoPrevistoGramas||0).toFixed(1)} g</span><input data-consumo-material="${m.materialReceitaId}" type="number" min="0" step="0.1" value="${Number(m.pesoPrevistoGramas||0).toFixed(1)}"></label>`).join("")}</div><div class="erpFormGrid"><label class="inputGroup"><span>Quantidade concluída</span><input id="qtdConcluida" type="number" min="0" max="${lote.quantidade}" value="${lote.quantidade}"></label><label class="inputGroup"><span>Peças com defeito</span><input id="qtdDefeito" type="number" min="0" value="0"></label></div><label class="inputGroup"><span>Observações</span><textarea id="obsConclusao" rows="3"></textarea></label><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn" onclick="confirmarConclusaoLote('${id}')">Concluir e atualizar estoque</button></div>`);}
function confirmarConclusaoLote(id){try{const consumos=[...document.querySelectorAll("[data-consumo-material]")].map(el=>({materialReceitaId:el.dataset.consumoMaterial,pesoRealGramas:Number(el.value)||0}));const r=Producao.concluirLoteExecucao(id,{resultado:document.getElementById("resultadoLote").value,quantidadeConcluida:document.getElementById("qtdConcluida").value,pecasDefeito:document.getElementById("qtdDefeito").value,observacoes:document.getElementById("obsConclusao").value,consumos});Modal.fechar();renderProducao();Toast.show(r.pedido?.statusPedido==="pronto"?"Produção concluída e pedido pronto!":"Lote concluído, estoque e custos atualizados!");}catch(e){console.error(e);Toast.show(e.message);}}

function abrirModalFalhaLote(id){const lote=Storage.buscarLoteExecucaoPorId(id);if(!lote)return;Modal.abrir("Registrar falha",`<label class="inputGroup"><span>Motivo</span><select id="motivoFalha">${["Soltou da mesa","Entupimento","Falta de energia","Erro de filamento","Falha de camada","Problema mecânico","Cancelado pelo usuário","Outro"].map(v=>`<option>${v}</option>`).join("")}</select></label><div class="completionMaterials">${(lote.filamentosSelecionados||[]).map(m=>`<label><span>${escaparProducao(m.material)} ${escaparProducao(m.cor)} · consumido</span><input data-falha-material="${m.materialReceitaId}" type="number" min="0" step="0.1" value="0"></label>`).join("")}</div><label class="inputGroup"><span>Quantidade perdida</span><input id="qtdPerdida" type="number" min="0" max="${lote.quantidade}" value="${lote.quantidade}"></label><label class="inputGroup"><span>Observações</span><textarea id="obsFalha" rows="3"></textarea></label><label class="favoriteToggle"><input id="repetirFalha" type="checkbox" checked><span>Criar nova tentativa</span></label><div class="modalActions"><button class="btnSecondary" onclick="Modal.fechar()">Cancelar</button><button class="btn dangerButton" onclick="confirmarFalhaLote('${id}')">Registrar falha</button></div>`);}
function confirmarFalhaLote(id){try{const consumos=[...document.querySelectorAll("[data-falha-material]")].map(el=>({materialReceitaId:el.dataset.falhaMaterial,pesoRealGramas:Number(el.value)||0}));Producao.registrarFalhaLote(id,{motivoFalha:document.getElementById("motivoFalha").value,pecasDefeito:document.getElementById("qtdPerdida").value,observacoes:document.getElementById("obsFalha").value,repetir:document.getElementById("repetirFalha").checked,consumos});Modal.fechar();renderProducao();Toast.show("Falha registrada e recursos atualizados.");}catch(e){console.error(e);Toast.show(e.message);}}
function novaTentativaUI(id){try{Producao.criarNovaTentativa(id);Modal.fechar();renderProducao();Toast.show("Nova tentativa criada. Faça uma nova alocação.");}catch(e){Toast.show(e.message);}}

function executarAcaoManual(id,acao){try{if(acao==="iniciar")Producao.iniciarOperacaoManual(id);else Producao.concluirOperacaoManual(id);const ordem=Storage.buscarOperacaoProducaoPorId(id)?.ordemProducaoId;abrirDetalhesOrdemProducao(ordem);Toast.show(acao==="iniciar"?"Tarefa iniciada.":"Tarefa concluída.");}catch(e){Toast.show(e.message);}}
function abrirHistoricoOperacao(id){const eventos=Storage.listarHistoricoProducao().filter(e=>String(e.operacaoId)===String(id)).sort((a,b)=>new Date(b.criadoEm)-new Date(a.criadoEm));Modal.abrir("Histórico da operação",`<div class="historyList">${eventos.map(e=>`<article><i data-lucide="history"></i><div><strong>${escaparProducao(e.descricao||e.tipo)}</strong><span>${new Date(e.criadoEm).toLocaleString("pt-BR")}</span></div></article>`).join("")||estadoVazioProducao("history","Sem eventos")}</div>`);lucide.createIcons();}
function abrirResultadoLote(id){const l=Storage.buscarLoteExecucaoPorId(id);if(!l)return;Modal.abrir("Resultado do lote",`<div class="productionOrderMeta"><div><span>Status</span><strong>${rotuloStatusLote(l.status)}</strong></div><div><span>Tempo real</span><strong>${formatarMinutosProducao(l.tempoRealMinutos||Producao.calcularTempoDecorrido(l))}</strong></div><div><span>Custo real</span><strong>${Utils.moeda(l.custoReal||0)}</strong></div><div><span>Resultado</span><strong>${escaparProducao(l.resultado||"-")}</strong></div></div>`);}

function cardLoteAtivo(lote){const op=Storage.buscarOperacaoProducaoPorId(lote.operacaoId);const ordem=Storage.buscarOrdemProducaoPorId(lote.ordemProducaoId);const imp=Storage.buscarImpressoraPorId(lote.impressoraId);const dec=Producao.calcularTempoDecorrido(lote);const prog=Producao.calcularProgressoLote(lote);const restante=Math.max(0,Number(lote.tempoPrevistoMinutos||0)-dec);const termino=new Date(Date.now()+restante*60000);const excedeu=dec>Number(lote.tempoPrevistoMinutos||0);return `<article class="activePrinterCard" data-live-lote="${lote.id}"><header><div><span class="liveDot"></span><strong>${escaparProducao(imp?.nome||lote.impressoraNome)}</strong></div><span class="erpBadge printer-${lote.status==='pausada'?'pausada':'imprimindo'}">${lote.status==='pausada'?'Pausada':'Ocupada'}</span></header><h3>${escaparProducao(ordem?.produtoNome||op?.produtoNome)}</h3><p>Pedido #${String(lote.pedidoId).slice(-5)} · ${escaparProducao(ordem?.clienteNome||"")}</p><div class="activePrinterMeta"><div><span>Operação</span><strong>${escaparProducao(op?.nome||"")}</strong></div><div><span>Quantidade</span><strong>${lote.quantidade} un.</strong></div><div><span>Decorrido</span><strong data-live-time>${formatarMinutosProducao(dec)}</strong></div><div><span>Previsão</span><strong>${termino.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</strong></div></div><div class="productionProgress"><div><span>${excedeu?`Ultrapassou ${formatarMinutosProducao(dec-lote.tempoPrevistoMinutos)}`:`Restam ${formatarMinutosProducao(restante)}`}</span><strong data-live-progress>${prog}%</strong></div><i><b style="width:${prog}%"></b></i></div><div class="activeFilaments">${(lote.filamentosSelecionados||[]).map(m=>`<span><i data-lucide="spool"></i>${escaparProducao(m.material)} ${escaparProducao(m.cor)}</span>`).join("")}</div><footer>${botoesLote(lote)}</footer></article>`;}
function cardImpressoraProducao(imp){const lote=imp.operacaoAtualId?Storage.buscarLoteExecucaoPorId(imp.operacaoAtualId):null;if(lote)return cardLoteAtivo(lote);const fila=(imp.filaOperacoes||[]).map(id=>Storage.buscarLoteExecucaoPorId(id)).filter(Boolean);return `<article class="erpEntityCard printerQueueCard"><div class="erpEntityTop"><div class="printerIcon"><i data-lucide="printer"></i></div><div><h3>${escaparProducao(imp.nome)}</h3><p>${escaparProducao(imp.modelo||"")}</p></div><span class="erpBadge printer-${imp.status}">${STATUS_IMPRESSORAS[imp.status]||imp.status}</span></div><div class="printerQueueSummary"><span>${fila.length} na fila</span><strong>${formatarMinutosProducao(fila.reduce((t,l)=>t+Number(l.tempoPrevistoMinutos||0),0))}</strong></div>${fila.map((l,i)=>`<div class="queueItem"><b>${i+1}</b><span>${escaparProducao(Storage.buscarOperacaoProducaoPorId(l.operacaoId)?.nome||"Operação")}<small>${l.quantidade} un.</small></span></div>`).join("")}</article>`;}
function renderFilaGeral(lotes){const fila=lotes.filter(l=>["em_fila","pronta_para_iniciar","aguardando_alocacao"].includes(l.status)).sort((a,b)=>Number(a.posicaoFila||999)-Number(b.posicaoFila||999));return `<div class="queueGeneral">${fila.map(l=>`<article>${cardLoteCompacto(l)}</article>`).join("")||estadoVazioProducao("list-ordered","Fila vazia")}</div>`;}
function renderLotesLista(lotes,vazio){return `<div class="queueGeneral">${lotes.sort((a,b)=>new Date(b.concluidoEm)-new Date(a.concluidoEm)).map(l=>`<article>${cardLoteCompacto(l)}</article>`).join("")||estadoVazioProducao("package-check",vazio)}</div>`;}
function atualizarContadoresProducao(){document.querySelectorAll("[data-live-lote]").forEach(card=>{const lote=Storage.buscarLoteExecucaoPorId(card.dataset.liveLote);if(!lote)return;const tempo=Producao.calcularTempoDecorrido(lote);const progresso=Producao.calcularProgressoLote(lote);const t=card.querySelector("[data-live-time]");const p=card.querySelector("[data-live-progress]");const b=card.querySelector(".productionProgress b");if(t)t.textContent=formatarMinutosProducao(tempo);if(p)p.textContent=`${progresso}%`;if(b)b.style.width=`${progresso}%`;});}
function rotuloStatusLote(status){return {aguardando_alocacao:"Aguardando alocação",pronta_para_iniciar:"Pronto para iniciar",em_fila:"Em fila",em_execucao:"Em execução",pausada:"Pausada",concluido:"Concluído",falhou:"Falhou",cancelado:"Cancelado"}[status]||status;}
function formatarMinutosProducao(min){const total=Math.max(0,Math.round(Number(min)||0));return total>=60?`${Math.floor(total/60)}h${String(total%60).padStart(2,"0")}`:`${total} min`;}
function escaparProducao(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
